### ISSUE TITLE
Integration of Blog Picture

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#1]
The blog picture should be edited, viewed (in preview and blogview) to be possible to generate a complete blog.

**Comment by TheFive** [comment]
See Trello: https://trello.com/c/go4o9O3I

**Comment by TheFive** [comment]
Will add a markdown on blog level, that is rendered between date and first categorie in preview.

**Comment by TheFive** [comment]
Waiting for Team to say issue is closed with current solution.
may be a better GUI Integration is needed

**Comment by alexandre-mbm** [comment]
References about comunicate with Wordpress:
- [scottgonzalez/node-wordpress]
- [Working On: Node and WordPress](https://ramisayar.com/working-on-node-and-wordpress/)
- [How to set the filter for wordpress xmlrpc wp.getPosts while using node.js?](http://stackoverflow.com/questions/25432861/how-to-set-the-filter-for-wordpress-xmlrpc-wp-getposts-while-using-node-js-not)
- [Example of how to use node-wordpress]()

[scottgonzalez/node-wordpress]: https://github.com/scottgonzalez/node-wordpress

**Comment by alexandre-mbm** [comment]
I know that probably that will not be solution, but it's good know that there is: [mdfigcaption]

[mdfigcaption]: https://www.npmjs.com/package/mdfigcaption

**Comment by TheFive** [comment]
Thanks, this could be a helpfull remark.

**Comment by TheFive** [comment]
The picture has to be per language.

**Comment by alexandre-mbm** [comment]
Furthermore people use external images. If not, the images could be only Wordpress attachments, translated there.
