### ISSUE TITLE
Show, that there are new collections.

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#100]
Of course, you can be interested in new collections.

I think i have to enrich the data modell by a "last change" of reach object (to get the value easier than by the history).
This can be for
a) Collection
b) MarkdownDE .. Markdown PT

This time can be compared with the last login time, which has to be "defined" as there is now no real logoff, i suggest 10 Minutes of inactivity is a logoff.
Than you can mark everything thats newer than your logoff time. Every Translation, which needs update (on all directions)...
(So i put it on further languages..)

**Comment by TheFive** [comment]
I will write all new collections to a slack chanel. Then all problems, what as seen by a user, sen out mails, can be managed by slack.

**Comment by alexandre-mbm** [comment]
And if it was responsibility for the user changing the status for each article in the  blog view, through of click on rotatives buttons-images of status?
