### ISSUE TITLE
Possibilty to sort articles in a category.

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#101]
Question to the readers:
Do we need a sort per language, or should we sort "globally" for all languages ?

For your information: 
For now the articles are sorted by Title, and if you number the titles in a category, they are sorted by that number. This is a alphanumeric sort (not a numeric!), so there exists a small workaround, which implements a global sort.

**Comment by fredao** [comment]
The globally sort or all languages is OK.
Be aware: before OSMBC we had no sorting at all. ;-)

**Comment by TheFive** [comment]
In Rizzoma there was the possibility to sort, as it was a "text stream". You could put an article at the end or the beginning of a category. Now OSMBC decides that for you by a "hidden" algorithm.
To make this "deterministic", in my first version, the sorting was random, i have used the title for sorting. 
So i just want to make the hidden feature public.

**Comment by fredao** [comment]
The sorting in Rizzoma was a random(sort) ;-)

**Comment by TheFive** [comment]
Yes but it was allways the _same_ random order.

In my test i have learned, that postgres gives me the articles in a real random order, and the result WN result was allways different, which leads to test errors. 

If you do NOT use Title, you can have this random sort yet too.

**Comment by alexandre-mbm** [comment]
For now the sort mode can be a choice hardcoded, no? I talk like this because this can still be seen as a less important issue.

**Comment by fredao** [comment]
The sort is sooo unnecessary, we had it never, nobody asked for it and how do you distinguish an important mesaage and an unimportant one? If you like to sort it, then sort it in WordPress.

**Comment by alexandre-mbm** [comment]
> how do you distinguish an important mesaage and an unimportant one?

_"a less important issue"_ (me) `~` _"is sooo unnecessary, we had it never, nobody asked for it"_ (you)

**I am not arguing** in favor of ordering; I was showing something that happens on system and that affects the final results of each country
