### ISSUE TITLE
Markdown not correct converted

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#102]
This text 
```md
Howto place an issue in OSMBC? 

1. open OSMBC, 
1. click Collect,
1. choose a category from the pop up window
1. write a Titel: example: Lidar,
1. write at text or put a link
1. click OK
--- reday --- 
    
If you like to write the news directly, do as follows:

1. click Edit
2. write your news in English (you can see it in 
3. click OK and ...
... that's it.
```
is not converted correct, there is an ending < (from an capped </ol> insead of an capped </p>.

**Comment by alexandre-mbm** [comment]
I did not understand the problem.

> is not converted correct, there is an ending < (from an capped insead of an capped 

I do not know what means.

**Comment by fredao** [comment]
anyway, I have a workaround .... and can write the whoto's

**Comment by fredao** [comment]
@TheFive ... ich habe bei der Help - wohl was kaputtgespielt :(
Ich wollte dieses hinzufügen .. 
     {
          "DE": "HTML erzeugen",
          "EN": "Create HTML to transfer to WordPres"
     }

**Comment by TheFive** [comment]
Solved in commit d19038189068c56e299d54b6bb449125a86fc102

**Comment by TheFive** [comment]
for now only in development, so i reopen.

**Comment by TheFive** [comment]
https://github.com/TheFive/osmbc/commit/c274b6ec107d4ccff4f9c180e51fc9122ceece56
