### ISSUE TITLE
Add Spinner to Collect Save button, to inform about "in progress"

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#1021]
If you have entered and saved a link on your mobile phone, the screen remains open. 
This very often leads to a link being entered twice. (from the same mobile phone :-( )
It would be nice if the capture window would close after the save. 

![2024-02-11-185227_002](https://github.com/TheFive/osmbc/assets/1868849/1f296b53-5f98-46aa-a05c-de1d89338cfa)

**Comment by TheFive** [comment]
ah, may be a performance problem. I think about disabling save button, to have a direct reaction of UI.

**Comment by TheFive** [comment]
OK i do not understand the question.

If you enter a link, i assume you do that with Collect menu.

Collecing has an OK button and if you save your  collection (after validation with title length) OSMBC jumps to the Article Editor, to subscribe more of your article. Here the OK button is changed to SAVE, but disabled as long as nothing was changed.

so how did you manage to enter a new article twice ?
(or is it just that you where able to press two times OK, as button is not disabled).

**Comment by TheFive** [comment]
Will work with spinners to indicate that something is going on
