### ISSUE TITLE
remove pt-pt-t

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#1022]
Because weekly's automatic translations procduce PT-t

![grafik-buykjn51kty1xxfzcaki55jw8h](https://github.com/TheFive/osmbc/assets/1868849/f8de869c-e113-4fa7-ad9c-948ba94743c4)

**Comment by Strubbl** [comment]
Could we also add PT-PT here: https://osmbc.openstreetmap.de/config/languageflags and reuse the PT icon?

**Comment by fredao** [comment]
Just as you like it! I don't want to keep expecting myself and the two Portuguese to keep hitting the backspace button every time I do an automatic translation.

**Comment by TheFive** [comment]
<img width="468" alt="image" src="https://github.com/TheFive/osmbc/assets/6240370/75667361-1ae8-4c2c-a14c-291af45dca1b">
reason coud be, that - to have a correct deepl translation PT is replaces by PT-PT for translation:

But this is also done for EN, so does EN has the same problem ?

**Comment by TheFive** [comment]
<img width="1014" alt="image" src="https://github.com/TheFive/osmbc/assets/6240370/05ef0875-7517-4eb8-8229-c880f998ad76">
Deepl os supporting PT PT-BR and PT-PT

**Comment by fredao** [comment]
Then we would nevertheless still need an icon @Strubbl

**Comment by Strubbl** [comment]
I try to do this by this evening

**Comment by fredao** [comment]
No stress, we've been putting up with it for a while now, so we'll be able to endure it for a few more days.

**Comment by Strubbl** [comment]
the language icons are already existing since September 2022. I do not know why they are not configured in osmbc 🤷
So i just did this. Should work now.

**Comment by fredao** [comment]
solved! - thanks!
![image](https://github.com/TheFive/osmbc/assets/1868849/f2d3e703-e393-45c7-9843-14d84ce76ff7)
