### ISSUE TITLE
Cannot rad properties of null (reading '0')

### ISSUE THREAD

**Issue by westnordost** [TheFive/osmbc#1043]
When I go to https://osmbc.openstreetmap.de/, I only get an error message:

Cannot rad properties of null (reading '0')

![imagen](https://github.com/user-attachments/assets/f9beda15-ce68-4777-8e3f-ed5c5c9fd01d)

[Logout] lands me at the login page, but when I press on the login with OAuth 2.0 button, I get back to seeing that error message.

Clearing all cookies for that site doesn't help.

**Comment by Strubbl** [comment]
OSMBC was just down due to a crash. It is running again now.

**Comment by westnordost** [comment]
Jup, it does now, thanks!
