### ISSUE TITLE
Categories in Spanish

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#108]
Corriente
Acerca de nosotros
./.
Mapeando
Comunidad
Importaciones
Fundación OpenStreetMap
Eventos
OSM Humanitario
Mapas
#switch2OSM
Datos Abiertos
Licencias
Software
Software
Sabías que …
Otras cosas “geo”
./.
-- unpublished --

**Comment by fredao** [comment]
- means: not used in Spanish Version

**Comment by alexandre-mbm** [comment]
Withdrawal? Do we must give up #109?

**Comment by fredao** [comment]
sim Alexandre - resolvido  - veja:

{
     "-- no category yet --": {
          "EN": "-- no category yet --",
          "DE": "-- noch keine Kategorie --",
          "ES": "-- no category yet --",
          "FR": "-- no category yet --",
          "CZ": "-- no category yet --",
          "PT": "-- no category yet --",
          "JP": "-- no category yet --",
          "ID": "-- no category yet --"
     },
     "[Actual Category]": {
          "EN": "[Actual Category]",
          "DE": "[Aktuelle Kategorie]",
          "ES": "[Corriente]",
          "FR": "[Actualité]",
          "CZ": "[Actual Category]",
          "PT": "[Corriente]",
          "JP": "[Actual Category]",
          "ID": "[Actual Category]"
     },
     "About us": {
          "EN": "About us",
          "DE": "In eigener Sache",
          "ES": "Acerca de nosotros",
          "FR": "À notre propos",
          "CZ": "About us",
          "PT": "Sobre nós",
          "JP": "私たちについて",
          "ID": "Tentang kami"
     },
     "Weekly exerciseEN:": {
          "EN": "Weekly exerciseEN:",
          "DE": "Wochenaufruf",
          "ES": "Not Translated",
          "FR": "Not Translated",
          "CZ": "Not Translated",
          "PT": "Not Translated",
          "JP": "Not Translated",
          "ID": "Not Translated"
     },
     "Mapping": {
          "EN": "Mapping",
          "DE": "Mapping",
          "ES": "Mapeando",
          "FR": "Cartographie",
          "CZ": "Mapping",
          "PT": "Mappeamento",
          "JP": "マッピング",
          "ID": "Pemetaan"
     },
     "Community": {
          "EN": "Community",
          "DE": "Community",
          "ES": "Comunidad",
          "FR": "Communauté",
          "CZ": "Community",
          "PT": "Communidade",
          "JP": "コミュニティ",
          "ID": "Komunitas"
     },
     "Imports": {
          "EN": "Imports",
          "DE": "Importe",
          "ES": "Importaciones",
          "FR": "Importation",
          "CZ": "Imports",
          "PT": "Importações",
          "JP": "インポート",
          "ID": "Imports"
     },
     "OpenStreetMap Foundation": {
          "EN": "OpenStreetMap Foundation",
          "DE": "OpenStreetMap Foundation",
          "ES": "Fundación OpenStreetMap",
          "FR": "Fondation OpenStreetMap",
          "CZ": "OpenStreetMap Foundation",
          "PT": "Fundação OpenStreetMap",
          "JP": "OpenStreetMap Foundation",
          "ID": "Yayasan OpenStreetMap"
     },
     "Events": {
          "EN": "Events",
          "DE": "Veranstaltungen",
          "ES": "Eventos",
          "FR": "Événements",
          "CZ": "Events",
          "PT": "Eventos",
          "JP": "イベント",
          "ID": "Kegiatan"
     },
     "Humanitarian OSM": {
          "EN": "Humanitarian OSM",
          "DE": "Humanitarian OSM",
          "ES": "OSM Humanitario",
          "FR": "OSM et l'humanitaire",
          "CZ": "Humanitarian OSM",
          "PT": "OSM Humanitário",
          "JP": "OSM人道支援",
          "ID": "OSM untuk Kemanusiaann"
     },
     "Maps": {
          "EN": "Maps",
          "DE": "Karten",
          "ES": "Mapas",
          "FR": "Cartes",
          "CZ": "Maps",
          "PT": "Mapas",
          "JP": "地図",
          "ID": "Peta"
     },
     "#switch2OSM": {
          "EN": "#switch2OSM",
          "DE": "switch2OSM",
          "ES": "#switch2OSM",
          "FR": "#switch2OSM",
          "CZ": "#switch2OSM",
          "PT": "#switch2OSM",
          "JP": "#switch2OSM",
          "ID": "#switch2OSM"
     },
     "Open Data": {
          "EN": "Open Data",
          "DE": "Open-Data",
          "ES": "Datos Abiertos",
          "FR": "Ouverture des données",
          "CZ": "Open Data",
          "PT": "Dados abertos",
          "JP": "オープンデータ",
          "ID": "Open Data"
     },
     "Licences": {
          "EN": "Licences",
          "DE": "Lizenzen",
          "ES": "Licencias",
          "FR": "Licences",
          "CZ": "Licences",
          "PT": "Licenças",
          "JP": "ライセンス",
          "ID": "Lisensi"
     },
     "Software": {
          "EN": "Software",
          "DE": "Programme",
          "ES": "Software",
          "FR": "Applications",
          "CZ": "Software",
          "PT": "Software",
          "JP": "ソフトウェア,
          "ID": "Software"
     },
     "Programming": {
          "EN": "Programming",
          "DE": "Programmierung",
          "ES": "Software",
          "FR": "Applications",
          "CZ": "Programming",
          "PT": "Software",
          "JP": "ソフトウェア",
          "ID": "Software"
     },
     "Did you know …": {
          "EN": "Did you know …",
          "DE": "Kennst Du schon …",
          "ES": "Sabías que …",
          "FR": "Connaissez-vous …",
          "CZ": "Did you know …",
          "PT": "Você sabia...",
          "JP": "…ご存知でしたか？",
          "ID": "Apakah anda tahu …"
     },
     "Other “geo” things": {
          "EN": "Other “geo” things",
          "DE": "Weitere Themen mit Geo-Bezug",
          "ES": "Otras cosas “geo”",
          "FR": "Autres sujets géographiques",
          "CZ": "Other “geo” things",
          "PT": "Outras coisas "geo"",
          "JP": "その他の "ジオ" な事柄",
          "ID": "Berita "geo" lainnya"
     },
     "Not Translated": {
          "EN": "Not Translated",
          "DE": "Wochenvorschau",
          "ES": "Not Translated",
          "FR": "Not Translated",
          "CZ": "Not Translated",
          "PT": "Not Translated",
          "JP": "Not Translated",
          "ID": "Not Translated"
     },
     "--unpublished--": {
          "EN": "--unpublished--",
          "DE": "--unpublished--",
          "ES": "--unpublished--",
          "FR": "--unpublished--",
          "CZ": "--unpublished--",
          "PT": "--unpublished--",
          "JP": "--unpublished--",
          "ID": "--unpublished--"
     }
}
