### ISSUE TITLE
Is there some strategy for real use of the instances?

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#112]
A **question**.

Do I can use some of the instances with some guarantee of no data loss?
I would translate something. Is there some strategy for we (users) currently?

**Comment by TheFive** [comment]
Production environment will loose no data. Development Environment will loose data by design. It is a sandbox, where from time to time data from production will be copied in.

**Comment by alexandre-mbm** [comment]
> It is a sandbox, where from time to time data from production will be copied in.

About data moving, prod→dev or dev→prod?

**Comment by TheFive** [comment]
allways prod -> dev. Dev is a sandbox to allow the team (and me) to test anything without the risk of corrupting productive data.
