### ISSUE TITLE
possibilty to see the WN # in last changes

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#114]
![image](https://cloud.githubusercontent.com/assets/1868849/10931958/bd389f70-82cc-11e5-8d0c-688efd79df1d.png)

**Comment by TheFive** [comment]
Is it a information you really want to see every time, or do you need the information "sometime" to control people working on the right WN ?
In the second case you can click on the (i) to see the complete change description, there is a link to the article.
In the first case i assume, that mostly the current blog is displayed in history.

**Comment by fredao** [comment]
I know this i and the link to the article. If it is shown only the actual article, I really think we should talk an automatic "Fallbeil" ;-) to set version into review.
