### ISSUE TITLE
Differentiate style of translations not made

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#116]
**Suggestion:** font in gray light.

---

- [ ] ![osmbc-do-gray-1](https://github-cloud.s3.amazonaws.com/assets%2F957501%2F10957727%2Fbc00aad4-8345-11e5-9b08-2b3c9b147635.png)

- [ ] ![osmbc-do-gray-2](https://github-cloud.s3.amazonaws.com/assets%2F957501%2F10957730%2Fc5792c26-8345-11e5-8922-b640006421a5.png)

---

**Suggestion:** font in gray light.

**Comment by alexandre-mbm** [comment]
See a likely bug at https://github.com/TheFive/osmbc/issues/118#issuecomment-153962869

**Comment by TheFive** [comment]
In overview ther is no mark for missing text. Here missing text is shown by the edit link.

**Comment by alexandre-mbm** [comment]
I had noticed, but I wanted to suggest something more flashy such as style in gray light. These my least important hints I am collecting for possible pull requests.

**Comment by fredao** [comment]
I think, it is flashy enough ... It is very unostentatiously ... and everybody can see it very well ... nobody from the other teams complained an asked for clicky bunti ;-)

**Comment by alexandre-mbm** [comment]
> nobody from the other teams complained an asked for clicky bunti ;-)

Google and/or its Translator does not help me about what "clicky bunti" means.

**Comment by fredao** [comment]
E una palavra pejorativa para todos estes GUIs muliticlores vs commad line.

## Manfred Reiter - mobile - please excuse typos and brevity
Am 05.11.2015 23:27 schrieb "Alexandre Magno" <notifications@github.com>:

**Comment by alexandre-mbm** [comment]
> E una palavra pejorativa para todos estes GUIs muliticlores vs commad line.

If you can reference a text (even if in english), I appreciate it. To I try to know what you want to tell me.

**Comment by fredao** [comment]
Forget it, it was a joke.

## Manfred Reiter - mobile - please excuse typos and brevity
Am 05.11.2015 23:36 schrieb "Alexandre Magno" <notifications@github.com>:

**Comment by alexandre-mbm** [comment]
@fredao, I wanted to better feel the your tone in the joke.
