### ISSUE TITLE
Buttons "Edit" and "Download" have not action at Preview

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#117]
But direct links are working. Example:
http://thefive.sabic.uberspace.de/blog/304/preview?download=true&lang=PT

**Comment by TheFive** [comment]
I press the button and 
![image](https://cloud.githubusercontent.com/assets/6240370/10963219/b127df98-839e-11e5-8c49-6b36ee2fe276.png) is downloaded.

**Comment by fredao** [comment]
same here:
![image](https://cloud.githubusercontent.com/assets/1868849/10968876/c0bc6368-83c4-11e5-8625-be99ea9e2469.png)

**Comment by alexandre-mbm** [comment]
Here nothing happens. I am using Firefox 41.0.2 on Arch Linux.

**Comment by fredao** [comment]
Marc works with a Mac, I with Ubuntu and dowloaded with FF and Chrome without any problem

**Comment by TheFive** [comment]
May be you have to click the link in the button, not the button itself. Some buttons are still based on hyperlinks. This may change in future. Button itself is not working for me too.

**Comment by alexandre-mbm** [comment]
Here the mouse does not detect as link. I would not close the issue, the problem exists with a user.

**Comment by alexandre-mbm** [comment]
> I will clean the browser's cache to try.

I did it, but the problem continues.
