### ISSUE TITLE
Order of sentences changed by system

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#118]
I have the impression of that the system changed the order of these two items:

![osmbc-order-changed](https://github-cloud.s3.amazonaws.com/assets%2F957501%2F10958263%2F1aa905cc-834b-11e5-9c5c-e159f2795f5c.png)

**Comment by alexandre-mbm** [comment]
Seems that it is doing an **alphabetical order**, but this **is not cool**.

**Comment by fredao** [comment]
It is even more than cool! If you like to have a certain order, put a number in front, s you decide the order! Not the Germans or the British decide the order of the Brazilian, you do it.!!!

**Comment by alexandre-mbm** [comment]
No, we are stuck to the alphabet.

**Comment by fredao** [comment]
But you can number it! To change the order.Try it!

## Manfred Reiter - mobile - please excuse typos and brevity
Am 05.11.2015 05:13 schrieb "Alexandre Magno" <notifications@github.com>:

**Comment by alexandre-mbm** [comment]
The number will go to the final text, no?

**Comment by fredao** [comment]
Test it please

**Comment by alexandre-mbm** [comment]
Okay. Tested. All is right. Thank you and excuse me. You can label this issue as a `question`.

**Comment by fredao** [comment]
This should go to FAQ as well

**Comment by alexandre-mbm** [comment]
> ~~Okay. Tested. All is right. Thank you and excuse me. You can label this issue as a `question`.~~

No, sorry. I have changed **international** titles accidentally. See:

![osmbc-international-title](https://cloud.githubusercontent.com/assets/957501/10960854/092a31d8-8367-11e5-9de4-341e7ae202b2.png)

**Comment by fredao** [comment]
Use numbers only
1
2
3

Not
1)
2)
3)

Neither
#1
#2
#3

Only 1 2 3

**Comment by alexandre-mbm** [comment]
> Use numbers only

OK, but do I should not translate the title, right?

**Comment by fredao** [comment]
No, the title does not appear nowhere.
It is only for the editors.

**Comment by fredao** [comment]
Please test it until the export!

**Comment by alexandre-mbm** [comment]
Sorry, I will undo there. More one FAQ.

**Comment by alexandre-mbm** [comment]
@fredao edit:
```
#1
#2
#3
```
to:
<pre>```
#1
#2
#3
```</pre>

This will avoid references in those issues of GitHub.

**Comment by fredao** [comment]
OK, thank, I am an absolute dummy on github - sorry

**Comment by alexandre-mbm** [comment]
> Sorry, I will undo there. More one FAQ.

Done. All.

**Comment by alexandre-mbm** [comment]
@fredao:
> Use numbers only
>> Please test it until the export!

When I did this it changed the title and the order for all languages.

**Comment by TheFive** [comment]
Related: https://github.com/TheFive/osmbc/issues/101
