### ISSUE TITLE
Set links based on categories to nofollow

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#12]
This was a hint of Editors in Slack. Personally i would prefer not to do so. If we reference a link in our blog, i think it is totally OK that search engines put that link up.
This referencing is under human control, and there is no possibility of abuse.

**Comment by Nakaner** [comment]
I fully agree with you. If we want to add a nofollow flag to a single link, we can still do this at Wordpress. If we want to flag all links as nofollow, we can do this at http://blog.openstreetmap.de/robots.txt
