### ISSUE TITLE
Way of marking "LANGUAGE_X only"

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#120]
For that it can export a reduced preview (the "download" feature).

![osmbc-notranslation-mark](https://cloud.githubusercontent.com/assets/957501/10958871/5575bad2-8351-11e5-97aa-a176eb7e8b66.png)

**Comment by TheFive** [comment]
![image](https://cloud.githubusercontent.com/assets/6240370/10963369/2c9e2f82-83a0-11e5-9f55-8a676f755d7f.png)

I said, no one is reading documentation.

**Comment by alexandre-mbm** [comment]
@TheFive, please confirm us if are right:
- DE: normal text...
- EN: `no translation`
- PT: `no translation`

OK?

**Comment by fredao** [comment]
Come on slack I check your Konfiguration.

## Manfred Reiter - mobile - please excuse typos and brevity
Am 05.11.2015 19:07 schrieb "Alexandre Magno" <notifications@github.com>:

**Comment by alexandre-mbm** [comment]
Nothing was wrong with my bar of tabs. This issue is about something else.
