### ISSUE TITLE
Why the preview of source language becomes red at keyboard event?

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#121]
![osmbc-keyboard-event-does-red](https://cloud.githubusercontent.com/assets/957501/10958930/d3af48dc-8351-11e5-97dd-100321d8c15e.png)

**Comment by alexandre-mbm** [comment]
Mysteriously it is no longer happening.

**Comment by fredao** [comment]
And it will happens again when the [Text between the brackets is to] big.

It is a hint, to have a better readabilty in the finsl Text.

**Comment by alexandre-mbm** [comment]
I suggest label this issue as `question` or `faq`.

**Comment by fredao** [comment]
No mystery, a clever developer.

**Comment by alexandre-mbm** [comment]
Eu não usei a palavra em sentido pejorativo.

**Comment by fredao** [comment]
You are right!

How do you put these to a faq?
Is there an easy way to do it.

**Comment by fredao** [comment]
Can you please help to collect these items.

**Comment by alexandre-mbm** [comment]
Yes, I will see now if it is easy I or you add or edit help pages.

**Comment by fredao** [comment]
Btw I knew que o sentido não estava pejorativo ;-)

## Manfred Reiter - mobile - please excuse typos and brevity
Am 05.11.2015 05:52 schrieb "Alexandre Magno" <notifications@github.com>:

**Comment by alexandre-mbm** [comment]
@fredao, I believe that @TheFive wants we are writing and translating blogs as the [305](http://thefive.sabic.uberspace.de/blog/305). He is linking this page at Help menu as the "[Beginner's Howto](http://thefive.sabic.uberspace.de/blog/305/preview?lang=EN)". I began to translate it ([PT](http://thefive.sabic.uberspace.de/blog/305/preview?lang=EN)).

**Comment by fredao** [comment]
Yes, I did the Beginners howto. ;-)

## Manfred Reiter - mobile - please excuse typos and brevity
Am 05.11.2015 06:27 schrieb "Alexandre Magno" <notifications@github.com>:

**Comment by alexandre-mbm** [comment]
We can create a blog "FAQ" likewise.

**Comment by fredao** [comment]
As you like it. Where should it be?

## Manfred Reiter - mobile - please excuse typos and brevity
Am 05.11.2015 06:34 schrieb "Alexandre Magno" <notifications@github.com>:

**Comment by alexandre-mbm** [comment]
![osmbc-tips-and-faqs](https://cloud.githubusercontent.com/assets/957501/10961046/113b0990-8369-11e5-9f6e-54d53e6d0888.png)

**Comment by fredao** [comment]
Yepp :-)

**Comment by alexandre-mbm** [comment]
I begin to see that using blogs to pages Help is inflexible especially because of the categories...

**Comment by stephan75** [comment]
@TheFive ... what about some tiny help text that appears when hovering with the mouse over an element where some (new?) users want to know the deeper meaning?

Like the red background on that picture above, the blue and red lines that indicate that an item has an unsolved comment or a mentioning of each user,

or an explanation about the blog status (open, edit, ...) and maybe some action buttons.

(Best example of these hover-over help text are in the user interface of virtualbox! IMHO)

**Comment by alexandre-mbm** [comment]
There are Javascript APIs for "tooltips".

**Comment by TheFive** [comment]
If someone is interested to help me with the help, i will build a framework for that. 
I would suggest a standard help to read first. It is just  priority topic.
e.g. How Many new people to you want to integrate in the next year ?
versus
How often do you want to mark double collected articles as double ?

BTW: I do not believe that someone is reading manuals. And i do not believe that it is a good idea to let programmers (with a deep inner understanding of the program) write manuals.


BTW 2: Question is adressed without help by #129

**Comment by alexandre-mbm** [comment]
> I would suggest a standard help to read first. It is just priority topic.
> e.g. How Many new people to you want to integrate in the next year ?
> versus
> How often do you want to mark double collected articles as double ?

Do you're saying it's more important to teach about strategies to get advantage of the system?
