### ISSUE TITLE
Legend for types of comments

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#123]
![osmbc-legends](https://cloud.githubusercontent.com/assets/957501/10959360/5b40a562-8356-11e5-9954-c02e007be4c5.png)

**Comment by fredao** [comment]
Comment empty: nothing
Comment not empty; blue
Comment to you or #all: red

**Comment by fredao** [comment]
Comment empty: nothing
Comment not empty; blue
Comment to you or #all: red

**Comment by TheFive** [comment]
Short hint in:
http://thefive.sabic.uberspace.de/help.html
Long help has to be written by someone. But i do not believe anyone is reading it.
