### ISSUE TITLE
Hint about HTML exported: an initial comment declaring the charset

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#124]
Minor priority. But see example at line 1 below please:
```html
<!-- charset: utf-8 -->
<p>27/10/2015-2/11/2015</p>
<!--         place picture here              -->
<h2 id="wn276_mapeamento">Mapeamento</h2>
<ul>
<li>
...
```

**Comment by TheFive** [comment]
I do not do that, as the text should be as clean as possible to copy it to WP. It is not intended to be read directly by a browser. May be in future i will generate WP style to the HTML (e.g. for the picture).

**Comment by alexandre-mbm** [comment]
@TheFive, you can label this issue as `invalid` or `wontfix`, if prefer.
