### ISSUE TITLE
Enable pages Help translated

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#125]
See https://github.com/TheFive/osmbc/issues/121#issuecomment-153961952

~~Or is better following the `views/help.jade`'s strategy? Depends of the #126.~~

**Comment by TheFive** [comment]
I Think we should not start translating the help, i think it is more important to have a more complete help in one language.

**Comment by fredao** [comment]
+1

**Comment by alexandre-mbm** [comment]
OK, +1
