### ISSUE TITLE
 Why "Blog Missing Cat: -- no category yet --"?

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#127]
At end of http://thefive.sabic.uberspace.de/blog/305/preview?lang=EN:

---

![osmbc-missing-cat](https://cloud.githubusercontent.com/assets/957501/10962648/ac802c5a-8378-11e5-987d-cb2f778e2a9e.png)

**Comment by TheFive** [comment]
Thats just, because the Help Blog does not have the categor no category. Just click on the 10100 (the article) and add a category to the article, that exists in the blog.

**Comment by alexandre-mbm** [comment]
But the result of this procedure is unwanted (for me at least):

![osmbc-nocategory-at-help](https://cloud.githubusercontent.com/assets/957501/10976153/1df0e528-83c9-11e5-8c78-dccca4a9cdef.png)

**Comment by TheFive** [comment]
Hi Alexandre,

if my answers should fit more in what you want, you have to specify it here.
I have just told you, how to react on the given problem.

Christoph

**Comment by alexandre-mbm** [comment]
@TheFive, the blog 305 is published as Help. The image at https://github.com/TheFive/osmbc/issues/127#issuecomment-154129784 shows the problem.
