### ISSUE TITLE
Allow closing of blogs per language.

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#131]
Just to be more organised with the team, it would be good to be able to close a blog, if it is transferred to WP.

**Comment by alexandre-mbm** [comment]
My opinion: it is need foment the best practice of make only OSBMC→Wordpress moves. In future the OSMBC could feed the Wordpress. It is possible that there is Node.js module to making XMLRPC. While it does not happens, it appear that we can only leave the Wordpress versioning the final texts.
