### ISSUE TITLE
Better table of status at blog's Edit view

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#133]
Ref.: #132

The current table:

lang | review | close
--- | --- | ---
DE | review | close[Reopen]()
EN | - | -
ES | review | -
FR | - | -
PT | - | -
JP | - | -
ID | - | -
TR | - | -

Propose:

lang | status | open? | articles | untranslated | no translation
--- | --- | --- | --- | --- | ---
DE | published | close / [reopen]() | 10 | 2 | 4
EN | review | - | 12 | 0 | 2
ES | review | - | 8 | 5 | 1
FR | - | - |  - | 14 |
PT | edit | - | 11 | 8 | 3
JP | - | - | - | 14 |
ID | - | - | - | 14 |
TR | - | - | - | 14 |

Explications:

- The work begin with DE but other languages adds articles
- `total of blog's articles` = `articles` + `no translation`
- `untranslated` is contained in `articles`
- `no translation` are the articles marked for never be translated in that language (row)

**Comment by TheFive** [comment]
I will create the statistics per blog later. I am not sure in which form I present the results.
