### ISSUE TITLE
Improve navigation with new buttons and keyboard shortcuts

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#134]
What is below is proposed and @TheFive told me that will look the voting.

New buttons:
- [ ] At blog, in any tab, `Previous` and `Next` to go directly by Edit pages of articles untranslated
- [ ] In the horizontal bar, a button `Roulette` to give away an article untranslated (opening its Edit page)

In another issue I will propose "worktable" page containing other ways for start quickly editing recent articles still untranslated.

Keyboard shortcuts:
- [ ] `ESC` to take off the focus from text areas at article's Edit page
- [ ] At article's Edit page, without focus in text (or after of `ESC`):
  - [ ] `b` for focus in blog choose box
  - [ ] `c` for focus in category choose box
  - [ ] `s` (subject) for focus in title text field
  - [ ] `l` (links) for focus in collection text area
  - [ ] `t` (text/translation) for focus in markdown text area
  - [ ] `p` (paste) for copy&paste text in translation text area
  - [ ] `n` (note) for focus in comment text area
  - [ ] `ENTER` to click the button `OK`
- [ ] `r` to click the button `Roulette`*
- [ ] `<` to click the button `Previous`*
- [ ] `>` to click the button `Next`*

\* _read above about the new buttons_

I believe :grey_question: these keyboard shortcuts **will can increase in 5x the user's performance** for editing. :muscle:

**Comment by fredao** [comment]
Hi Alexandre,

Verynice proposal, (I like shortcuts as well) and good thoughts, I would vote for it, but the enhancement #29 imho has a higher priority

https://github.com/TheFive/osmbc/issues/29

**Comment by alexandre-mbm** [comment]
> I would vote for it, but the enhancement #29 imho has a higher priority

I do not understand the current voting as to put "priority" in the issue, but only to register  acceptance of a possible future feature. Surely there are other more important issues. I wanted to save the ideas and advance the discussions about if these are good ideas for a day be implemented on OSMBC.

**Comment by fredao** [comment]
Nós estamos falando sobre a mesma coisa. Eu messmo fiz essa integração várias vezes. Você pode acreditar em mim que eu sei do que eu estou falando.;-)

**Comment by TheFive** [comment]
BTW. looks like that Bootstrap is fully keyboard controllable in Chrome, just a matter of tab pressed.

**Comment by alexandre-mbm** [comment]
But if we will want it, lacks create the shortcuts, does not?

**Comment by TheFive** [comment]
I assume this is not an issue any longer. If there is some need in future, a new task can be opened.
