### ISSUE TITLE
Worktable page and/or RSS feeds

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#135]
What is below is proposed and @TheFive told me that will look the voting.

I think that is need notify users that there is work to make. Warn them about:
- [ ] Blog creation
- [ ] Article creation
- [ ] Changes in article previously edited (remember of #3)
- [ ] Blog marked to review

Mail notifications is expensive. RSS feeds can be alternative for more advanced users. But I defend creating a page named Worktable that would be the user's dashboard. As content, stats and  info in tables. Example (from #133):

blog | my lang | status | open? | articles | untranslated | no translation
--- | --- | --- | --- | --- | --- | ---
[WN276]() | EN | review | - | 12 | 0 | 2
[WN276]() | PT | edit | - | 11 | [8]() | 3

The click in `8` above would do one `Roulette` execution (see issue #134).
The click in `WN276` at row "review" would open the blog with the review tab (preconfigured).
The click in `WN276` at row "edit" would open the blog with the translation tab (preconfigured).

**Comment by alexandre-mbm** [comment]
Same thoughts of https://github.com/TheFive/osmbc/issues/134#issuecomment-154789460. The voting has no objective to change project's priorities. I seek only the approval for a future use case. Or open a discussion for interested individuals participatively come to an alternative.

**Comment by alexandre-mbm** [comment]
Also in Worktable page can exist  a table listing the last unstranslated articles (already existent in some language).

For PT as default/target language:

blog | category | from lang | text
--- | --- | --- | --- 
WN277 | Mapping | EN | OpenSolarMap is a crowdsourced project... ‒ [translate]()
WN277 | Open Data | ES | Las imágenes NAIP 2015 ahora están ... ‒ [translate]()

**Comment by alexandre-mbm** [comment]
> Mail notifications is expensive. RSS feeds can be alternative for more advanced users.

In the case of RSS feeds, the WeeklyOSM team could burn it with FeedBurner and so generate diary mail notifications (free).

**Comment by TheFive** [comment]
This issue adresses several topics.
a) Warn the user about what he is doing.
I prefer trained users, and the possibility to fix any error in the status by the system.
For now e.g.@fredao knows how to fix any status change, so an additional alert is not necessary ihmo.
b) User Information
Is done by a single mail for now. Slack will follow. If there is a usercount > 3 that like to have an RSS feed, i can do that to. 
c) For the list of undedited articles i have generated a separate issue.
https://github.com/TheFive/osmbc/issues/303

**Comment by alexandre-mbm** [comment]
Warn the user about what **others** are doing...
