### ISSUE TITLE
Create an untranslated & unedited Blog View

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#137]
Show only articles of a blog, that are unedited or untranslated.

Unedited: LEFT Article in a bicolumn blog is empty.
Untranslated: Right Article in bicolumn blog is empty.

**Comment by fredao** [comment]
Additional, yes
As standard please Not,

I often happens, that you look into an article even both are done.

Wilhelm Busch: Ein jeder Wunsch, wenn er erfüllt,
Kriegt augenblicklich Junge. ;-)

**Comment by TheFive** [comment]
I thought that as an alternative to overview, full and fullfinal

**Comment by fredao** [comment]
+1

**Comment by alexandre-mbm** [comment]
:+1: 

But also there is as option using colors. For example, a salmon for unedited, and a grey light for untranslated.

**Comment by TheFive** [comment]
There is also the possibility to use the article search, that is for now a little bit outdated (no language switch...).

**Comment by alexandre-mbm** [comment]
> There is also the possibility to use the article search, [...]

I think a something does not substitute the other.

**Comment by alexandre-mbm** [comment]
![osmbc-unclosed-filter](https://cloud.githubusercontent.com/assets/957501/11164934/9984966e-8ade-11e5-9545-29787bb3a123.png)

Is it this, isn't?

The table that is target of each edit link could be reduced and adapted to user language.

**Comment by fredao** [comment]
NO, THIS TABLE STAYS AS IT IS!!!

**Comment by alexandre-mbm** [comment]
> NO, THIS TABLE STAYS AS IT IS!!!

And stay as it is but create another table for that target?

PS.: I want that it have been a request for attention and not a cry in me.

**Comment by TheFive** [comment]
HI Alexandre,

you can, but please include an idea, what columns to put in. 
In the case you are referring markdownPT is Empty, so displaying markdownPT is senseless. 
displaying the collection values "can" make sense.

I can use the "main" language of a user configured in the user properties. I can use the "last use" language combination in the session for displaying a blog, or i can use the first language combination of a user defined in his properties ??
