### ISSUE TITLE
open the search part from Collect to the public

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#138]
only and idea - has nothing to do with OSMBC ... 
pro: could be an addtional service 
contra: performance

**Comment by TheFive** [comment]
may be, this should be done by the blog itself.
Like:
http://blog.openstreetmap.de/?s=TheFive

**Comment by TheFive** [comment]
If there is really a added value from OSMBC we can think about it, but first WP should do it.
BTW: i have thought about a similar thing:
"Open the Collection for everyone (with an OSM account that is not blocked in OSMBC) " (phase 1) and allow users to trace their collections (Phase 2). But thats very very future.

**Comment by fredao** [comment]
Phase 2 could be realised via a buffer. An editor could accept or refuse the proposal. This function could substitute the emails to blog@....

**Comment by TheFive** [comment]
Yes, but for now a minor problem, i assume. 
The Question for Phase2 is, what do we want to hide and why. 

But we are starting idea darwinism. Only the best or the one with the most pressure will survive :-)
