### ISSUE TITLE
What happens if someone [try] save article while other are editing?

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#139]
Or better: if someone is editing **or** translating the article.

**Comment by TheFive** [comment]
Just try it with to tabs. The second saver is loosing with an "Version Number Differs" Error (OSM Style). I thought, i have implemented an advise, how to work with this error, but i can not find it.

To Do: Set Error Message in router to:

"Conflict when saving article, please to back in browser, copy your last edit to clipboard and reload the page afterwards"

**Comment by TheFive** [comment]
But if you edit an article, that is already edited by another user, you get an warning (you can ignore).

There are still some "rare cases" possible, where the version number differs error may occur.

**Comment by alexandre-mbm** [comment]
> But if you edit an article, that is already edited by another user, you get an warning (you can ignore).

If I ignore, information will may be lost, or not?

The result of my test with tabs:

![osmbc-diff-conflict](https://cloud.githubusercontent.com/assets/957501/11027124/f2f138d0-8690-11e5-9344-c0b4147524b9.png)

**Comment by TheFive** [comment]
Oh, this occurs since the node_env is production, in the development version (with node_env=development) the error is shown correct.

**Comment by alexandre-mbm** [comment]
![osmbc-diff-conflict2](https://cloud.githubusercontent.com/assets/957501/11027566/5f5578d4-8695-11e5-8b2c-718e5f6c64c2.png)

**Comment by TheFive** [comment]
There was an error in the production error handler... Fixed now.

**Comment by alexandre-mbm** [comment]
Hint: label this issue also as `bug`.

**Comment by alexandre-mbm** [comment]
Would be good adding at end: 
> Or use the browser's "Back" button to retrieve (Control-C) your content.

Or better: a button in the page to perform the same action on browser.
