### ISSUE TITLE
Link to Google Translate

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#140]
More a issue **`To Vote`**, because I am not who talks the OSMBC's requirements.

At https://github.com/TheFive/osmbc/issues/29#issuecomment-154852799 I suggest a button-link "add". Now I want suggest near it a button-link "Google Translate" that would open the page in Google Translate.

Then below the collection's box we would have something like:

&nbsp;&nbsp;&nbsp;&nbsp;[http://a-link-from-collection]() - [add]() | [translate]()

**Comment by fredao** [comment]
+1

**Comment by alexandre-mbm** [comment]
Other use case related (by @fredao, from article [10226](https://thefive.sabic.uberspace.de/article/10226)):

![Image showing other use case related](https://cloud.githubusercontent.com/assets/957501/11038943/35c178fc-86e4-11e5-8462-073380a436ea.png)

Where the user would have a link to translation of the collection's text.

**Comment by alexandre-mbm** [comment]
Great! :100:
