### ISSUE TITLE
Error with search of articles

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#141]
When I do Article (menu) → Search (item menu):

![osmbc-search-bug](https://cloud.githubusercontent.com/assets/957501/11028457/7fafb4de-869d-11e5-80fe-ca319013e610.png)

**Comment by TheFive** [comment]
Fixed in development will be released with fix for #159 and #160.

**Comment by TheFive** [comment]
Grmpfhshsher.... This occured again.
