### ISSUE TITLE
More about flags

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#142]
Continuing #26, I want suggest also flags to adding while translating, and more countries.

**Comment by TheFive** [comment]
@fredao Please check, as it is decided not to use flags in weekly, i only show flags for editing when DE Langauge is shown.

**Comment by fredao** [comment]
weekly decided to not use flags, because they symbolise a country and not a language

**Comment by alexandre-mbm** [comment]
It is true, and there is a risk of a visual effect like "Christmas tree". I brought the suggestion because I have seen flags in some situations. When I wanted to flag for the mapper in the Spotlight, from Ireland, I have not found it.

Hint: if this is what you want, label this issue as `wontdo`.

**Comment by fredao** [comment]
if there was still one, I forgot to delete it!

**Comment by alexandre-mbm** [comment]
There are some at WN277→Community.

**Comment by fredao** [comment]
I will delete them after export

**Comment by alexandre-mbm** [comment]
Why not before?

**Comment by fredao** [comment]
because I have other - more important things to do - at the moment

**Comment by alexandre-mbm** [comment]
Okay, I thought that you were talking about a "process".

**Comment by TheFive** [comment]
The instant messenger to use for publishing weekly is called SLACK and position not here !!!.

I remember i have told you already. Please do not simply reply randomly to mails by github.
Thanks.
