### ISSUE TITLE
Not every pasting should be a hyperlink

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#143]
Continuing #29. After that the markdown code has at least a hyperlink, every pasting is creating markdown code for hiperlink.

**Comment by TheFive** [comment]
There is a regex to test on isURL befor pasting, can you document the text you are pasting, my NON url tests are working in production.

**Comment by alexandre-mbm** [comment]
Doing start of the translation for the article [10237](https://thefive.sabic.uberspace.de/article/10237?style=fullEN.PT) as test:

1. Pasting `Drag me to a markdown field,` is OK;
1. Pasting `http://www.hamburgsbruecken.de/uebersichtskarte/` on `markdown` word is OK:
  - Result: `Drag me to a [markdown](http://www.hamburgsbruecken.de/uebersichtskarte/) field,`
1. But pasting `or paste an` at end is wrong:
  - Result: `Drag me to a [markdown](http://www.hamburgsbruecken.de/uebersichtskarte/) field, [](or paste an)`

I have not looked at the code, but I am under the impression that you use regex on clipboard history.

**Comment by TheFive** [comment]
Please try again, i have changed the isURL function.

**Comment by alexandre-mbm** [comment]
It is doing `alert()` calls and it is not working.

**Comment by alexandre-mbm** [comment]
Now it only works in first time, with empty text area, or on the full text.

**Comment by TheFive** [comment]
I have to investigate and try to get a mocha test for that function. Crazy.

**Comment by alexandre-mbm** [comment]
It is least efficient but I would go try to do it working by using a strategy of parts (steps).

**Comment by TheFive** [comment]
Should be fixed in 0.3.6e.
