### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#144]
Of the Markdown code.

**Comment by TheFive** [comment]
I think, that is not necessary.

**Comment by alexandre-mbm** [comment]
OK. It is not. Perhaps in an distant future?

**Comment by alexandre-mbm** [comment]
I know that probably you will not change the idea, but it's good know that there is: [markdown-it-highlightjs]

[markdown-it-highlightjs]: https://www.npmjs.com/package/markdown-it-highlightjs

**Comment by TheFive** [comment]
OK, as you are more interested i use the good old GTD State (Getting Things Done) "Someday Maybe" for such hints.

**Comment by TheFive** [comment]
Discussed on the fossgis hacking event in Essen. Markdown is a language that is per design readable without syntax highlighting. To keep the interface clean, this will not be implemented.
