### ISSUE TITLE
Publish directly on Wordpress

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#145]
See https://github.com/TheFive/osmbc/issues/1#issuecomment-154776029.

**Comment by TheFive** [comment]
The time the exporter is sparing is not in relation to the development and integration time. 
Please build a pull request for it, than i can decide to integrate, if someone wants to use it.

**Comment by alexandre-mbm** [comment]
I think that a label `wontdo` would be better.
