### ISSUE TITLE
Error storing session object.

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#151]
if you click on WN260 in 
![image](https://cloud.githubusercontent.com/assets/1868849/11091475/0c98b2ae-887b-11e5-9415-89b243d8e6f5.png)

then 
![image](https://cloud.githubusercontent.com/assets/1868849/11091505/3e6fa814-887b-11e5-9408-3f129fffc91e.png)

**Comment by fredao** [comment]
SORRY erledigt, war ein Fehler, der (offensichtlich) - vom Brauser verursacht wurde. Please close the issue.

**Comment by alexandre-mbm** [comment]
Expired login for a previous deploy?

**Comment by TheFive** [comment]
There is an error in the session store object:
```
{
  "cookie": {
    "originalMaxAge": 31535999999,
    "expires": "2016-11-10T12:48:10.198Z",
    "httpOnly": true,
    "path": "/"
  },
  "passport": {
    "user": "derFred"
  },
  "returnTo": "/osmbc.html",
  "__lastAccess": 1447246090199,
  "articleReturnTo": "/blog/307"
}
}
````

The last } is unnecessary, but someone wrote that to the file.

**Comment by alexandre-mbm** [comment]
> The last } is unnecessary, but someone wrote that to the file.

Bug in library?

**Comment by TheFive** [comment]
it looks like the session file store has concurrency problems. node.js is not supporting file locking 
An alternative could be this simple store with postgres
https://github.com/voxpelli/node-connect-pg-simple

**Comment by TheFive** [comment]
https://github.com/valery-barysok/session-file-store/issues/21

**Comment by valery-barysok** [comment]
see  valery-barysok/session-file-store#18. It was fixed in 0.0.21 but in your package specified 0.0.20

**Comment by TheFive** [comment]
Hi @valery-barysok Thanks for you unexpected cross support :-) i will update my packages. I remember i had trouble with passport last time i tried, so i did a complete rollback of the update.

**Comment by TheFive** [comment]
With 0.21 and 0.24 I get the following Error
```
[session-file-store] will retry, error on last attempt: SyntaxError: sessions/zSYE82jaBCkl3MyZoFKhmtXDQqyfcgpY.json: Unexpected end of input
```

**Comment by valery-barysok** [comment]
you will get it in any case.

But you can decrease chance to get it by filter out urls like /css/*, /js/* etc from service by session. It happens due to concurrent access to the session file through write operation and if it happens it message about that and retries to read it again (5 times by default but you can change it. see available options).

**Comment by TheFive** [comment]
@valery-barysok ah, there is no authentication / session for standard files, but i have routing, that uses the authentication for "/" and later for (/all other), so session is adress twice. not changing the session object will hopefully not write it, so the simplification here hopefully helps. Thanks a lot.
