### ISSUE TITLE
Proposal sign a comment with ~~ which OSMBC expands to username, ...

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#152]
as I can generate with a "-" in the English Markdown Box a text "german only", it would be nice to sign a comment in the Comment box with an abbreviation.

I know from other software to sign with ~~
The two tildes ~~ could generate username, date and time ... or even only/at least the username ;-)

**Comment by alexandre-mbm** [comment]
+1, but in minor priority, I think. (please not close issues of minor priority)

**Comment by TheFive** [comment]
I am thinking about a more user oriented comment (not one field, but one field per comment) as the feature Is more used, than I thought.

**Comment by alexandre-mbm** [comment]
@TheFive, why does not integrate Disqus as way for cheapen? Does the their license allow the  private use?

**Comment by TheFive** [comment]
Conventions how to use OSMBC has to be done by the editors. Disqus can be a solution, but i like to have everything under my own control.

**Comment by TheFive** [comment]
I replace this requirement with
https://github.com/TheFive/osmbc/issues/304
