### ISSUE TITLE
Is there how to do "comment" in the markdown?

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#153]
I am doing my temporary workaround for #145. I do not want to waste time editing the Wordpress. I am doing "my solution" of integration: **OSMBC → Wordpress with image integrated** (ref. #1) from WP.

It will be a small and simple utility of command line centered in two commands: 
```console
$ paicemana prepare 276  # does downloads and checks
$ paicemana put          # feeds the wordpress
```

I am doing partial browser's automation to get some authentications. ← This is done and tested!

But I am wanting it with a HTML comment like in the artcile [10191](http://thefive.sabic.uberspace.de/devosmbc/article/10191?style=overviewPT) at the development instance.

I had begun in Python because I already have knowledge and experiments with it, but the same _know how_ will can be availed for a Node.js module (after¹).

@TheFive, do you can allow that I (all users) have like `<!-- image=1234 -->` in articles?

One per blog only, for the anchor to image. Where `1234` is a Wordpress media ID.

---

1 ‒ In future, the Node.js module will can start being used as CLI, before the library enter within OSMBC.

**Comment by alexandre-mbm** [comment]
PS.: I will manage the images fully and only in the Wordpress (as media).

**Comment by TheFive** [comment]
OSMBC is using: https://markdown-it.github.io/ so if there is a possiblilty to comment, it is in OSMBC:

**Comment by alexandre-mbm** [comment]
```js
var md = require('markdown-it')({ html: true });
```
Does you want do it?

And if I do a simple plugin to get something like a "~~empty~~ **HTML comment** [emoji](/markdown-it/markdown-it-emoji)" from code like `:image=1234`. Does would you accept use it?

**Comment by alexandre-mbm** [comment]
I had an overview on a [collection] of plugins, and and found two particularly interesting projects:

1. [mdvariables] ‒ usable?
1. [markdown-it-hashtag] ‒ an example of plugin "simple"

[markdown-it-hashtag]: https://www.npmjs.com/package/markdown-it-hashtag
[mdvariables]: https://www.npmjs.com/package/mdvariables
[collection]: https://www.npmjs.com/browse/keyword/markdown-it-plugin

**Comment by TheFive** [comment]
As it changes the tool, editors are working with i will ask them.

**Comment by TheFive** [comment]
It looks like you experience with html=true is not so good. The other plugin does not got positive feedback of the editor team i have asked.

**Comment by alexandre-mbm** [comment]
Today I know that we need use Wordpress for proofreading, then this issue lost its meaning. But does **not** "delete/erase" it please. My paicemana program continues without this.
