### ISSUE TITLE
Turkish translation of categories are wrong

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#154]
How can I help to fix it?-or the direct way would be via "canunen" in slack.

**Comment by alexandre-mbm** [comment]
Which are the symptom?

**Comment by TheFive** [comment]
Check mit Translate:
Açık Cadde Haritasının Kurulumu -> Installation of OpenStreetMap (a google translate crazyness ??)
Lisans -> Führerschein (google translate crazyness)

Unterscheidung Yazılım (Programme / Software) wird nicht gemacht.

So it looks like that the only "problem" is that there is no difference between Programme & Software. 

I close the ticket until there is new information.

**Comment by alexandre-mbm** [comment]
> I close the ticket until there is new information.

And the CHANGELOG?
