### ISSUE TITLE
Need a better display of blogs that are in EDIT status

### ISSUE THREAD

**Issue by stephan75** [TheFive/osmbc#155]
![osmbc status](https://cloud.githubusercontent.com/assets/5250044/11139651/57538cb2-89d2-11e5-9805-10820396c539.png)

See the screenshot above taken on 12. Nov. 2015

The section under "Blogs to work on" is listing blogs that are "open" and those in "review".

Between these two status options we have "Edit" in general.

But when setting the status of a blog from open to edit, we have NO more listing under "Blogs to work on", but only in in the grey headline above.

So would it be possible to list also blogs at "Blogs to work on" with status EDIT exactly between the ones with status Open and Review there?

**Comment by alexandre-mbm** [comment]
I prefer only a link to https://thefive.sabic.uberspace.de/blog/list

**Comment by TheFive** [comment]
Or a little bit shorter list:
http://thefive.sabic.uberspace.de/blog/list?status=!=closed

**Comment by alexandre-mbm** [comment]
:+1:

**Comment by stephan75** [comment]
The more I think about the table at http://thefive.sabic.uberspace.de/blog/list?status=!=closed I start to like it as well.
Is there any possibility to have this table in a compact or compressed form on the main OSMBC page?

**Comment by alexandre-mbm** [comment]
>  Is there any possibility to have this table in a compact or compressed form on the main OSMBC page?

Or in the Worktable page that is proposed at #135?

**Comment by alexandre-mbm** [comment]
:+1:
