### ISSUE TITLE
Prevent or give warning when a user wants to edit a blog with Status "Review"

### ISSUE THREAD

**Issue by stephan75** [TheFive/osmbc#156]
After the status "open" for collecting new blog items
and after status "edit"
(what means: only write or complete markdown text for existing items, and do translations, right?)
we are in "review" status that means: content has been copied to an external tool (like Wordpress) for review purposes.

But I noticed that editing that whole blog is still possible in OSMBC. But in most cases any edits done after the "export for external review" will be lost or no more paid attention to, I assume.

As this has happend in reality in the last weeks, I would like to have at least a warning message when a user wants to edit a blog that is already in review status.

That warning could be:

"You want to edit a blog that has already been exported to an external review tool. For your edits. you should use that external tool. Continue or Cancel?" ... or similar

**Comment by alexandre-mbm** [comment]
:+1: 

And more: "... If you can **and want* it, you may edit both, but is in the tool that will be the final version"

**Comment by TheFive** [comment]
I just have to find a solution to "unreview" a blog.

**Comment by TheFive** [comment]
I have choosen the following Model.

reviewComment => not editable
reviewComment && closed=true => not editable
reviewComment && closed=false => editable (a reopen modus)

**Comment by alexandre-mbm** [comment]
:+1: It was better so.
