### ISSUE TITLE
Languages in dropdown menu at article's view

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#157]
Even with tabs existing at blog's views, it would be interesting if we could see rapidly other languages.

**Comment by TheFive** [comment]
please configure a tab for every language (the number of tabs is near "unlimited", and can easily be increase). I would like to keep the clean 2 column user interface.

**Comment by alexandre-mbm** [comment]
Did you understood the purpose?

See:

![osmbc-dropdown-menu-here](https://cloud.githubusercontent.com/assets/957501/11159808/e54d2be4-8a41-11e5-9b33-54f4b24c7e45.png)

**Comment by alexandre-mbm** [comment]
Then #162 like #136 please.
