### ISSUE TITLE
Not renders the markdown, and there is not collection's links

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#158]
### After #156 be closed?

Details:

![osmbc-no-markdown-rendering](https://cloud.githubusercontent.com/assets/957501/11161329/50d17e4a-8a58-11e5-85a8-b56ace5e6604.png)

---

### Although it have saved the edit.

**Comment by TheFive** [comment]
May be an link to the article would be helpfull. I have tested it in the live version and no problem occurred. Java Script in the browser ignores every line behind an error, this sometimes "skips" functionality online.
But i have prepared something for #140. May be this solves this issue indirect.

**Comment by TheFive** [comment]
Still waiting for a link.

**Comment by TheFive** [comment]
http://thefive.sabic.uberspace.de/article/10246

It is this article. It does not have to do with the link, as the link is working in an new article.

**Comment by TheFive** [comment]
Fixed, stabilized front end code by filtering null vallues.

**Comment by alexandre-mbm** [comment]
Sorry, I've been sleeping during this time.
http://thefive.sabic.uberspace.de/article/10246?style=fullEN.PT

But now it **is fixed!** It is true. Thanks.
