### ISSUE TITLE
Install a backup for all DB

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#16]

**Comment by TheFive** [comment]
Done with https://wiki.uberspace.de/database:postgresql

**Comment by alexandre-mbm** [comment]
No english?

**Comment by TheFive** [comment]
ah, sorry the link is in german as the server provider is a german one, that seems to adress german people.

**Comment by alexandre-mbm** [comment]
But the tool used for do the backup have a english site or documentation?

**Comment by TheFive** [comment]
It is just a script, that is regulary called, maintained by the hoster, that calls pg_dumpall (Postgres Dump) every 24 hours.
The standard file backup of the hoster can't be used with postgres files.
