### ISSUE TITLE
A Cancel button near the OK button would be helpful

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#161]
![image](https://cloud.githubusercontent.com/assets/1868849/11164840/81f17652-8afc-11e5-9735-21ce76b757de.png)

**Comment by alexandre-mbm** [comment]
+1 :+1:

**Comment by TheFive** [comment]
I will do, if the user is not able to decide where to go next, i will ad a button, which will open the last saved Blog / Article List view :-). As the window is not modal, a cancel button is not necessary ( it is more an intelligent back button). Hope my guess will fit users need.

**Comment by fredao** [comment]
+1

**Comment by TheFive** [comment]
fixed in 0.3.9
