### ISSUE TITLE
But there are not differences...

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#163]
...[here](http://thefive.sabic.uberspace.de/changes/40685).

In really, I did [this](http://thefive.sabic.uberspace.de/changes/40686) and [this](https://thefive.sabic.uberspace.de/changes/40683).

**Comment by TheFive** [comment]
Description to short.

**Comment by alexandre-mbm** [comment]
I did edits from of access through URL. I do not changed markdownEN (see first link).

**Comment by TheFive** [comment]
May be i have to .trim the values before comparing for logging.

**Comment by TheFive** [comment]
i have introduced a .trim for all markdowns in version 0.3.10. Can you inform me, if the problem will occur again ?

**Comment by alexandre-mbm** [comment]
For this issue I do not know it. I do not believe that it have the same solution of the #171.

**Comment by TheFive** [comment]
This will be related to #181 wich is closed.
