### ISSUE TITLE
A common tail in URL title and URL leads to a wrong []() separation.

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#164]
Continuing #29 like #143, a wrong result: 

- [ ] Example 1: [Antuérpia](https://pt.wikipedia.org/wiki/Antu%C3%A9rpia)
```md
[Antué](https://pt.wikipedia.org/wiki/Antu%C3%A9)rpia
```

Certainly the `é` is out of the _regex_.

---

Other cases unwanted:
- [ ] Example 2: [Paul Norman](https://github.com/pnorman)
```md
[Paul N](https://github.com/pn)orman
```
- [ ] Example 3: [dia internacional das pessoas com deficiência](https://pt.wikipedia.org/wiki/Dia_internacional_das_pessoas_com_defici%C3%AAncia)
```md
[dia internacional das pessoas com deficiê](https://pt.wikipedia.org/wiki/Dia_internacional_das_pessoas_com_defici%C3%AA)ncia
```
- [ ] Example 4: [Georreferenciamento](https://pt.wikipedia.org/wiki/Georreferenciamento)
```md
[](https://pt.wikipedia.org/wiki/)Georreferenciamento
```
- [ ] Example 5: [georreferenciamento](https://pt.wikipedia.org/wiki/Georreferenciamento)
```md
[g](https://pt.wikipedia.org/wiki/G)eorreferenciamento
```

**Comment by TheFive** [comment]
Second problem is known, i hoped it is more seldom, than your examples explain, it comes out of my insert algorithm wich is not taken the selected_start and selected_end of a textfield into account.

First problem is a regex problem, i try to find a better regex taking the é into account.

**Comment by TheFive** [comment]
If you have a suggestion for the Regex ? 

 function isURL(t) {
    
      var isUrlRegex = /^(http|ftp|https):\/\/[\w-]+(\.[\w-]+)+([\w.,@?^=%&amp;:\/~+#-]*[\w@?^=%&amp;\/~+#-])?/


      if (t) return isUrlRegex.test(t);
      return isUrlRegex;
    }

**Comment by TheFive** [comment]
I think it is only the selection problem.
