### ISSUE TITLE
The articles table when coming from overview of blogs

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#167]
I'm coming from https://github.com/TheFive/osmbc/issues/137#issuecomment-156811486.

I gave up to proposing what I had in mind. Some ideas already are in others issues; in fact, for others screens, others use cases.

I think that it would be interesting you using the "main" language of a user configured in the user properties. And more so if each of the two columns have at header a dropdown menu to select the language (with page refresh).

If exists a title in this page query for an unique blog, the "blog" column is dispensable. 

I come back behind regarding the "collection" column. It is better be there.

My two last suggestions:

1. Text as HTML rendered
1. Tootip for mouseover on texts, to show the full text (or then onclick event to open windows modal)

**Comment by TheFive** [comment]
Im still thinking about this. On the one hand, i would like to have the article editor as simple as possible, and would not like to put to many switches in it. On the other hand i understand, that a more experienced user would like to change the languages out of the editor directly.
May be it is just a matter of finding the right GUI Elements.

**Comment by alexandre-mbm** [comment]
Remember https://github.com/TheFive/osmbc/issues/157#issuecomment-156583735

**Comment by TheFive** [comment]
In an article it is now easily possible to switch the language. I hope this addresses the topic.
