### ISSUE TITLE
fullTextSearch for https does not find http Links

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#17]
On the search or collect page you can search for http://something.about.osm. There is no mechanism to search for https://something.about.osm in the same question yet,
This is may be a dictionary and "normalisation" problem, that can be solved with postgres methods.

**Comment by alexandre-mbm** [comment]
Is it the same #24?

**Comment by TheFive** [comment]
https://github.com/TheFive/osmbc/commit/2835af461d971e9b21991c281c4d43fc974f8c86
