### ISSUE TITLE
Hint, that Review takes place in WordPress

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#170]
alle hints are not engough - I think we should mention it here

![image](https://cloud.githubusercontent.com/assets/1868849/11311765/2c6807e8-8fd2-11e5-82cb-bd0a78018c8e.png)

maybe here behind the text
![image](https://cloud.githubusercontent.com/assets/1868849/11311799/5b2741ca-8fd2-11e5-859e-877b9e2f120e.png)

or here below the buttons 
![image](https://cloud.githubusercontent.com/assets/1868849/11311817/8515f378-8fd2-11e5-8bef-8d0cb32bb054.png)

and maybe in RED

**Comment by alexandre-mbm** [comment]
I do not know of which way, but yes, +1 :+1:  for let more clear that revision is happening on Wordpress.
