### ISSUE TITLE
Unknown behavior with an closed article

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#171]
![osmbc-whereisit](https://cloud.githubusercontent.com/assets/957501/11315284/1484ace8-8fce-11e5-8524-02cce358756c.png)

Auxiliary links for this issue:
https://thefive.sabic.uberspace.de/article/10294?style=fullES.PT
https://thefive.sabic.uberspace.de/article/10294?style=fullEN.PT ←

**Comment by alexandre-mbm** [comment]
This is problem... see at 279:

![osmbc-whereisit2](https://cloud.githubusercontent.com/assets/957501/11316505/cc5a7662-8fe8-11e5-90c7-7efc83d3f5c7.png)

**Comment by alexandre-mbm** [comment]
There are blank spaces or non visible characters. See:

![osmbc-whereisit3](https://cloud.githubusercontent.com/assets/957501/11316536/f5ebcd68-8fe9-11e5-9903-e9cb76b86264.png)

I suggest a cleaning function.

**Comment by TheFive** [comment]
i have introduced a .trim for all markdowns in version 0.3.10. Can you inform me, if the problem will occur again ?

**Comment by alexandre-mbm** [comment]
Seems OK [now](https://thefive.sabic.uberspace.de/article/10368?style=fullEN.PT).

**Comment by TheFive** [comment]
Thanks for feedback.
