### ISSUE TITLE
Generate Wochenvorschau out of wiki markdown

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#174]
The wiki markdown for the Wochenvorschau will be copied to the collection, OSMBC should parse the content to the Wochenvorschau table. 
The markdown will be generated for every language, and the translator has to skip unwanted lines.

**Comment by alexandre-mbm** [comment]
What is Wochenvorschau?

**Comment by fredao** [comment]
I explained it, extract from calendar. Check slack.

**Comment by alexandre-mbm** [comment]
@TheFive, will **[this](http://wiki.openstreetmap.org/w/index.php?title=Template:Calendar&action=edit)** be copied?

**Comment by alexandre-mbm** [comment]
Maybe be useful knowing that exists:
- [Markdown Tables Generator](http://www.tablesgenerator.com/markdown_tables)
- [CSV To Markdown Table Generator](https://donatstudios.com/CsvToMarkdownTable), based on Node.js module **[CsvToMarkdownTable](https://github.com/donatj/CsvToMarkdownTable)**
