### ISSUE TITLE
Create a Webhook to read information from slack for collection.

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#175]
Create a web hook that listens to a channel in Slack that creates a new article for every link posted in that channel, that does not exist in OSMBC yet.
If it already exists retweet, that to the channel. Do ignore anything, that is not recognized as an URL.

**Comment by alexandre-mbm** [comment]
Doing like a IRC bot will demand time for development. I suggest labeling this with `someday maybe`.
