### ISSUE TITLE
Set language of spellchecker for browser.

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#176]
Firefox supports a language oriented spell-checker. Try to set the language of the markdown to the correct one.

**Comment by alexandre-mbm** [comment]
+1 :+1:  I think it is a HTML attribute.

**Comment by TheFive** [comment]
I have tried to set the markdown field to a specific language, but my brower (firefox & chrome) seems only to support one language per article.
If someone can use this language per markdown feature, i would like to have positive feedback.

**Comment by alexandre-mbm** [comment]
I did not got good results.

It seems a limitation of the spell checker extension. But I think that you are doing right.

References:

- [Declaring Languages in HTML 5](http://nimbupani.com/declaring-languages-in-html-5.html)
- [HTML lang Attribute](http://www.w3schools.com/tags/att_global_lang.asp) + [HTML Language Code Reference](http://www.w3schools.com/tags/ref_language_codes.asp) ‒ _w3cshools.com_
- [Why use the language attribute?](http://www.w3.org/International/questions/qa-lang-why.en.php) ‒ _W3C_

But see this that I did not understood:

- [What <html lang=“”> attribute value should I use for a mixed language page?](http://stackoverflow.com/questions/7076837/what-html-lang-attribute-value-should-i-use-for-a-mixed-language-page)
- [RFC 5646, Language Tags, eptember 2009](http://www.ietf.org/rfc/bcp/bcp47.txt)

Who want help to testing, should install [dictionaries](https://addons.mozilla.org/pt-BR/firefox/language-tools/).

**Comment by TheFive** [comment]
Stopped working on this issue, found no browser supporting it.
