### ISSUE TITLE
Slack Integration

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#18]
Build a bot, that listens to a special channel (like #wncollection) and that searchs for the text (in most cases a http link) in the current blog.
If the link is not in the current blog, generate a new article with the link
If the link is in an older blog, generate a new article with the link and the comment, where the link was used.
Goal of this function is, to use the "SendTo" Funktion of mobile phones to send links directly to OSMBC.

Heres a link how to write a node.js Bot for slack.
https://scotch.io/tutorials/building-a-slack-bot-with-node-js-and-chuck-norris-super-powers

Furthermore the bot can send information to slack, that has to be defined. e.g. comments on articles can be posted to slack, to do the discussion here.

**Comment by alexandre-mbm** [comment]
I think that the bot must have interactivity also. Like IRC bots. For example, a command to enjoy and get the information from a last message (filtred by nick or not).

**Comment by fredao** [comment]
If a slack integration is possible
then the comments should be transferred to slack as well

Example: @marc Gemis @escada ... I think he asks to map the Mexican Flags and he does't aks the Mexican Community?

**Comment by Nakaner** [comment]
I suggest to write a XMPP or IRC bot instead of a Slack bot because Slack is a propietary platform which has an XMPP and IRC gateway. Or do we want to drive into a lock-in effect (as all those people using propietary software and data formats)?

**Comment by fredao** [comment]
I meant ... simply inform the person ... which way - for me it is unimportant ;-)

**Comment by TheFive** [comment]
If i use XMPP i have to take care about integration of XMPP to OSMBC and of integration to XMPP to Slack, if i use slack, one integration is skipped. As Instant messenger do not contain information "for long life", but just for the moment, the can change easily. If the editor team will use another system, OSMBC will change.
(Thats my opinion as OSMBC developer).

**Comment by TheFive** [comment]
P.s. Hopefully i have succesfull switched if some proprietary software in the editorial process.

Everyone is allowed to do the same by offering alternatives that are accepted by the team.  :-)

**Comment by alexandre-mbm** [comment]
Doing with Slack is more easy. But it can be as plugin.
