### ISSUE TITLE
Remove Whitespace from Input Field

### ISSUE THREAD

**Issue by Nakaner** [TheFive/osmbc#181]
Currently every input field which is empty (because no text of that language has been written yet) contains a single whitespace. This whitespace should be removed.

**Comment by Nakaner** [comment]
It looks as only the English input field is affected, not the German one.

**Comment by alexandre-mbm** [comment]
I think the important is the system work correctly. I think the better strategy to accomplish this is eliminate spaces and so seek normalized writes.
