### ISSUE TITLE
translationPT

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#186]
![osmbc-translationbug-1](https://cloud.githubusercontent.com/assets/957501/11611656/74a5f2c2-9bb7-11e5-9417-285470d5cadf.png)

![osmbc-translationbug-2](https://cloud.githubusercontent.com/assets/957501/11611657/795d3712-9bb7-11e5-92ed-718194d36509.png)

**Comment by TheFive** [comment]
Step 2 is a bug, i meant to use PT.EN instead of the non existing style translationPT.EN in the article view.
Article view is supporting any LANG1.LANG2 combinations, styles with text before are more restricted.

**Comment by alexandre-mbm** [comment]
If it is "translate from", the style should be EN.PT and not PT.EN. Do you agree?

Now I see that are the title. It would be interesting a way to indicate that exists PT translation already.

**Comment by TheFive** [comment]
The Left Column is PT and it is expanded by the right column with EN. so PT.EN is exactly what i want.

**Comment by TheFive** [comment]
P.S. for (1): this is in english, as it displays the Title, that is collected as an english texxt.

**Comment by alexandre-mbm** [comment]
> so PT.EN is exactly what i want.

When I am translating from EN to PT, I use a EN.PT configuration. But OK, I and others can get used to.

> this is in english, as it displays the Title,

I understand it. It would be interesting it be in light gray when non translated, for saving clicks (and demands to server).
