### ISSUE TITLE
Translate feature - switch the languages i.e. left: source language right: target language

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#188]

**Comment by alexandre-mbm** [comment]
Do it duplicate the issue #186?

**Comment by fredao** [comment]
#186 is labelled as a bug.

My proposal is a feature, because I see it more helpful to translate from left to right. ;-)

**Comment by alexandre-mbm** [comment]
The "bug" already was fixed there. A https://github.com/TheFive/osmbc/issues/186#issuecomment-162342797 "ask" your feature. But OK.

**Comment by alexandre-mbm** [comment]
I am using `translationPT`. When I click `translate from EN`, it opens DE.EN.
