### ISSUE TITLE
Mark long HTML Links in Text in Warning or Danger.

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#19]
Markdown offers a interface, to integrate own rendering decisions in their process. Find out how to mar all links > 20 Chars (to be discussed) in HTML Bootstrap Warning or Danger Class (in Edit Mode, not in preview or export).

**Comment by TheFive** [comment]
Yeah Done :-). Current Value is 30.

**Comment by alexandre-mbm** [comment]
You could refer the issue number at the commit's message.

**Comment by TheFive** [comment]
Is there a common way to do so ?

Link, #numer, Issue{number} ?

**Comment by alexandre-mbm** [comment]
`anything #number` is a reference, and there are commands: [Closing issues via commit messages](https://help.github.com/articles/closing-issues-via-commit-messages/)
