### ISSUE TITLE
Fixes for image preview

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#195]
Case: https://thefive.sabic.uberspace.de/article/10571?style=DE.EN

Do the `width` configuration in the both columns:
```html
<div style="width: 85%;" class="wp-caption alignnone"> 
```
```html
<img alt="Roads to Rom" src="URL" width="100%">
```
Firefox says as an unique CSS selector:
```
#previewRIGHT > ul:nth-child(1) > div:nth-child(1)
```

---

![osmbc-image-before](https://cloud.githubusercontent.com/assets/957501/11771444/ee42f80e-a1ee-11e5-9a72-919df0ab97ca.png)

![osmbc-image-after](https://cloud.githubusercontent.com/assets/957501/11771446/f4b5f614-a1ee-11e5-9949-550a426c4b98.png)

**Comment by TheFive** [comment]
Mm, first i have to get the libraries running in browser (not under node.js). As long as this is not working, and it still looks like "alsdökjföadsjkföjadfs" i will disable the preview in article for pictures.

**Comment by alexandre-mbm** [comment]
![osmbc-tableswidth](https://cloud.githubusercontent.com/assets/957501/12024487/30db6cf6-ad83-11e5-8b67-7e0efcbd1c3c.png)

Is it this?
