### ISSUE TITLE
Integration of Calender

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#2]
The OSM Calender should be read and integrated in the Blog Preview.

**Comment by alexandre-mbm** [comment]
Do you speak about "[Current events]" at wiki?

[Current events]: http://wiki.openstreetmap.org/wiki/Current_events

**Comment by fredao** [comment]
No,

Please See blog.wochennotiz.de and scroll to the end

We have it each Werk, but only in the German one

**Comment by fredao** [comment]
No,

Please See blog.wochennotiz.de and scroll to the end

We have it each week, but only in the German one

**Comment by fredao** [comment]
...  or yes, we copy the German events to the German weekly ... see at the end.

**Comment by alexandre-mbm** [comment]
![osmbc-kalender](https://cloud.githubusercontent.com/assets/957501/11019589/bc5112b2-85de-11e5-8138-c81d335a45a7.png)

**Comment by fredao** [comment]
Yes

**Comment by alexandre-mbm** [comment]
How would be this integration?

**Comment by fredao** [comment]
What do you mean? I think this one is very difficult - it is done as a manual extract form http://wiki.openstreetmap.org/wiki/Current_events

I have no idea wheather an automatism is feasable or not.

**Comment by alexandre-mbm** [comment]
@fredao, eu estou perguntando o que vocês estão chamando de "integrar" o calendário. Antes de me responder, por favor certifique-se com @TheFive de que estão a falar da mesma coisa.

**Comment by fredao** [comment]
@alexandre-mbm, sim, nós estamos falando sobre a mesma coisa. Eu fiz essa integração já várias vezes, eu mesmo.Você pode acreditar em mim que eu sei do que eu estou falando, ;-)

**Comment by TheFive** [comment]
Just to remind you both.
This is an issue tracker, that is designed to make changes and bugs and their work on tracable and understandable for everyone, that would like to participate at development (with ideas, testing or programming). So the language has to be english. Anything that is better done in IM should be done in IM. And all text MUST be On Topic, if there is something for the tracker, that is not ON Topic, just create a new issue.

Thanks for your help.

**Comment by alexandre-mbm** [comment]
@fredao:
> @alexandre-mbm, sim, nós estamos falando sobre a mesma coisa.

@TheFive:
> the language has to be english

Okay, in english. What is integrate the calendar? I don't know what it is.

**Comment by alexandre-mbm** [comment]
@TheFive at Slack:
> just an information about importing the calender. It is published on a daily basis as iCal, you can ask for regions (only rectangular) where the event is placed. More is explained in OSM Wiki 

I found the modules [peterbraden/ical.js] and [mozilla-comm/ical.js].

[peterbraden/ical.js]: https://github.com/peterbraden/ical.js
[mozilla-comm/ical.js]: https://github.com/mozilla-comm/ical.js/wiki

**Comment by alexandre-mbm** [comment]
See #174
