### ISSUE TITLE
a prepared Markdown - table in the section "Other "geo" things with the title You are looking for a new job

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#201]
![image](https://cloud.githubusercontent.com/assets/1868849/11869787/916058f8-a4c2-11e5-91fe-76085d940ca3.png)

would be nice to have ;-)

**Comment by fredao** [comment]
additional idea: 
maybe OSMBC should offer a form, where interesed could post vacancies?
without logging in to OSMBC

**Comment by alexandre-mbm** [comment]
Or this formulary could be cheaper by using the Google Spreadsheets.

**Comment by TheFive** [comment]
May be it would be a nice sister project collecting and offering jobs in the GEO area, and may be this sister project is able to export markdown :-), or it should be done in a way, the calender is handled by the community. In the second case i build a variant of the calender2markdown Tool in OSMBC.
As osmcount is still collecting data more and more and i do not find the time to take care about my first baby, i do not volunteer for this project :-)

The Idea is to make editing of formated text simple on an ascii base with markdown. If user is expecting a wysiwyg Editor, i may be have to search for a plugin, doing that, and throw out any markdowning. But may be i should do that in 2.0, and should be discussed in the editor team. And it is important to find a good wysiwyg Editor, Rizzoma has not met my criteria for a good editor. 

I think it is more important do have the text edit field, thats supports horizontal scrolling, if you plan to have more and more tables in the Weekly, is it a need to have articles without a bullet in front ?

**Comment by TheFive** [comment]
Closed after Discussion with @fredao
