### ISSUE TITLE
Allow horizontal Scrolling for markdown that contains table.

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#202]
If a markdown contains a "|-----" is containing a markdown table.
Switch on horizontal scrolling in this cases.

**Comment by TheFive** [comment]
Exactly i took the string "|----" and put the "undocumented?" feature wrap ON and OFF.
It works on Chrome Mac.

See:
http://www.w3schools.com/tags/att_textarea_wrap.asp.

**Comment by alexandre-mbm** [comment]
I do not see it. Where is it?

**Comment by TheFive** [comment]
On a mac i just scroll with my touchpad. I do not have an idea, how it is solved on non proprietary or Windows Plattforms. :-(
The solutions changes the wrap argument of the textfield. I have read, that it is "mainly" supported on different plattforms.

**Comment by alexandre-mbm** [comment]
Do you can share a screenshot of the solution that has satisfied you?

**Comment by TheFive** [comment]
![image](https://cloud.githubusercontent.com/assets/6240370/12024739/acaff22e-ada7-11e5-96f2-c906ad6d9bbd.png)

**Comment by alexandre-mbm** [comment]
So it do not happens here.

**Comment by TheFive** [comment]
I will have to set the fontFamily to monospace. Then we can see, that it is working, and may be find out, how the wrap field is working on other systems.

**Comment by TheFive** [comment]
tested by freadao works on FF and Chrome on his machine.
