### ISSUE TITLE
Support easierer Review in OSMBC by opening the article edit mode out of fullFinalLL

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#203]
Is it possible to Connecticut the ... Link in translate directly with the possibity to edit in Markdown 

typo - sorry "to connect" ... never again I write such important issues on my moblile phone ;-)

**Comment by TheFive** [comment]
What is Connecticut and how does it relate to the ] ( Problem ?

**Comment by alexandre-mbm** [comment]
I also do not understand what you means.
