### ISSUE TITLE
The output from OSM calender2Markdown should be sorted

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#207]
![image](https://cloud.githubusercontent.com/assets/1868849/11912144/f89a451a-a62f-11e5-9390-571b581c0299.png)

**Comment by alexandre-mbm** [comment]
+1

**Comment by TheFive** [comment]
@fredao I will do that change language independent.

**Comment by alexandre-mbm** [comment]
@TheFive, date format per language?

**Comment by TheFive** [comment]
Yes.

**Comment by TheFive** [comment]
of course, do you mean i will publish this ugly 09/09/2015 in the German Wochennotiz :-)

**Comment by TheFive** [comment]
But one Formating string for all languages. The wonder is called moment.js
