### ISSUE TITLE
Implement a Tool like the calender tool to simplify Image Integration.

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#211]

**Comment by alexandre-mbm** [comment]
- [ ] What is bellow is normal?

![osmbc-toolimage-messages](https://cloud.githubusercontent.com/assets/957501/12053068/1fd483f8-aef4-11e5-9534-1dc8908a05b2.png)

- [ ] What is bellow is not cool...

![osmbc-toolimage-licenses](https://cloud.githubusercontent.com/assets/957501/12053071/2fa6c75a-aef4-11e5-8b6f-5124e62642ff.png)

Exact codes is better!

**Comment by TheFive** [comment]
Please read the hint at the start of the page.
