### ISSUE TITLE
Copy & Paste of Markdown table without line breaks

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#214]
Ref.: https://thefive.sabic.uberspace.de/article/10642?style=fullEN.PT

![osmbc-copypaste-table](https://cloud.githubusercontent.com/assets/957501/11946535/75d96a2c-a83a-11e5-80ba-bd4b91bd054a.png)

**Comment by TheFive** [comment]
Browser Problem ?

**Comment by alexandre-mbm** [comment]
Tested **Chromium** 46.0.2490.86 and **Firefox** 42.0. On **Arch Linux**. The problem happens **in both**.

**Comment by TheFive** [comment]
OK, if you copy something without line breaks and paste it, then of course no linebreaks are pasted, as there are no linebreaks in the clipboard.
I testet copy & paste with linebreaks (simple TestLine1\nTestLine2), that worked.
I can't exclude (i have no idea) what is happening, if systems with different linebreaks (as far as i know mac, unix and windows do not have a common understanding of "linebreaks") will disable them.

If you can generate more information, it may be can easier fixed.

One hint: 
as long as the table is a 4 column table, you can prettify it with the calender2markdown tool. Just Copy it to the tool.

**Comment by alexandre-mbm** [comment]
Test: http://thefive.sabic.uberspace.de/devosmbc/article/10656?style=fullEN.PT

Here the copy from EN to PT happened well.

**Comment by TheFive** [comment]
ad Update 1 and Update 2. Looks like a "Display" Problem, as the markdown should not be editable in export state.
It looks like, that the origin from wambacher did not contain linefeeds. So i ask him in wich format he copied the values in.
If i just take his text, Add some linebreaks with sublime on mac and put that to the Development Environment. I can copy and paste the table correct.
http://thefive.sabic.uberspace.de/devosmbc/blog/WN285?style=overviewDE.EN

**Comment by TheFive** [comment]
I have tried to reproduce this, but i was not able to do so.

**Comment by fredao** [comment]
only to know --- I did it several times and it worked fine! - so from my part no complains!

**Comment by alexandre-mbm** [comment]
Seems that is or was when copying from non editable blogs.
