### ISSUE TITLE
Use WN issue number for id of HTML <h2> tags

### ISSUE THREAD

**Issue by Nakaner** [TheFive/osmbc#22]
Currently the "View Preview" button exports an HTML which is as good as the HTML created from Rizzoma-Markdown via multimarkdown or dillinger.io. But one thing is missing.

To have unique HTML IDs, the ID of every `<h2>` tag at HTML should contain the WN number.

Current:
`<h2 id="mapping">Mapping</h2><ul><li>Benutzer glibbertorsten <a href="http://www.openstreetmap.org/user/glibbertorsten/diary/35887">beschreibt</a>, wie man das Tag addr:housename missbrauchen kann um eine in OsmAnd eine bessere Suche zu erreichen. Auf den Missbrauch wird er auch umgehend in den Kommentaren hingewiesen.</li>`

Better:
`<h2 id="271-mapping">Mapping</h2><ul><li>Benutzer glibbertorsten <a href="http://www.openstreetmap.org/user/glibbertorsten/diary/35887">beschreibt</a>, wie man das Tag addr:housename missbrauchen kann um eine in OsmAnd eine bessere Suche zu erreichen. Auf den Missbrauch wird er auch umgehend in den Kommentaren hingewiesen.</li>`

Or:
`<h2 id="WN271-mapping">Mapping</h2><ul><li>Benutzer glibbertorsten <a href="http://www.openstreetmap.org/user/glibbertorsten/diary/35887">beschreibt</a>, wie man das Tag addr:housename missbrauchen kann um eine in OsmAnd eine bessere Suche zu erreichen. Auf den Missbrauch wird er auch umgehend in den Kommentaren hingewiesen.</li>`

**Comment by TheFive** [comment]
I have implemented version OR, with lowercase function.

**Comment by alexandre-mbm** [comment]
Suggestion:
```html
BEGIN
<p>Code in HTML</p>
END
```
Where:
- BEGIN is <tt>```html</tt>
- END is <tt>```</tt>

**Comment by TheFive** [comment]
Hi Alexandre,
I do not understand ?

Michael just has tried to imporove the existing output id for <h2> tags. He is just interested in having more precise ID tags in the id (for whatever reason, i do not know WP)
<h2 id="mapping"> 
more detailed by <h2 id="wn???_mapping">.

**Comment by Nakaner** [comment]
@TheFive The reason why `<h2>` tags should contain unique IDs is a bit difficult to understand.

Our Wordpress installation shows multiple articles at its [start page](http://blog.openstreetmap.de/). `id="mapping"` is unique at one article but it is not unique at the start page. That's why links like
```<p class="wp-caption-text">
Mit dem OSM Marketing Lastenrad durch Dresden <a href="#karten">[1]</a>
</p>```
are not unique any more and would not work at the overview page.

**Comment by TheFive** [comment]
a, thanks for explanation.

**Comment by alexandre-mbm** [comment]
@TheFive, yes.
