### ISSUE TITLE
Add a link to the generated Author text for the Weekly.

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#223]
This weekly was produced by Alexandre Magno, Laura Barroso, MoiArcSan, Nakaner, derFred, escada, malenki, mgehling, wambacher.

linked with ...
https://wiki.openstreetmap.org/wiki/WeeklyOSM#Languages

**Comment by alexandre-mbm** [comment]
I think be better link to a public page of statistics regarding authorship.
