### ISSUE TITLE
a list with all articles per blog, sortable by persons who initally collected the article

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#227]

**Comment by TheFive** [comment]
I should update the Article Menu to fullfill this request.

**Comment by alexandre-mbm** [comment]
Hint: add a parameter "by blog". Example: <tt>?myArticles=true&<b>blog=WN284</b></tt>

**Comment by TheFive** [comment]
Should not be as much, as only not exported and not closed blogs are shown. The Blog Number is displayed in the articles list. I think with OSMBC all languages will get closer together in their number, and this problem will be reduced by nature. Main problem is to have a clean GUI, the filter is not a problem. (e.g. i could add any language to filter on too, but than it is a query matrix of 2-3 blogs multiplied with 6 languages, not easy to handle in a GUI, and of course, one can make the user configurable to...).

But you can easily get a list of all articles, you participated in collection per blog by going via the STAT view, I released today to.

**Comment by alexandre-mbm** [comment]
Yes, I understand this.

And now I can see: [/article/list?blog=**WN284**&user=**Alexandre%20Magno**&property=**collection**](http://thefive.sabic.uberspace.de/article/list?blog=WN284&user=Alexandre%20Magno&property=collection)
