### ISSUE TITLE
bug during editing articles on OSX with Chrome and Safari - NOT with FF

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#232]
problems
-- unpredictable line breaks 
-- the "] (" problem appeared now here as well 

speculation: maybe a different treatment of CR/LF, if a [text](link) needs a line break at the end of a line -  

Summary of our tests:
* problems caused by 
-- Chrome on Win7 and Apple
-- Safari on Apple

* NO problems with 
-- Chrome and FF on Ubuntu
-- FF on Apple

**Comment by TheFive** [comment]
Do you have an article, where it happend

**Comment by fredao** [comment]
in slack - yes ... will link it to your account

**Comment by TheFive** [comment]
It looks like it depends to the new feature for "good readable markdown for tables" (#202).
I have used a partially documented feature wrap of html5. Hopefully now in the correct manner. Tested with enforced line breaks by horizontal size reduces markdown editors.
