### ISSUE TITLE
divergence between end date in blog setting and shown up date in the blog itself

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#233]
blog setting - end date: 2015-12-28 
![image](https://cloud.githubusercontent.com/assets/1868849/12033919/cc62862c-ae29-11e5-814e-4b6c8fc07c15.png)

end date in blog itself: 
![image](https://cloud.githubusercontent.com/assets/1868849/12033932/efae520a-ae29-11e5-8b3f-33ddd85b27db.png)

hint: if the divergence should be caused by Zulu time, we should do the dead line 23:59 local time

**Comment by alexandre-mbm** [comment]
I think that using local time is bad. Showing local time is good. Because real time for all is the right.

**Comment by fredao** [comment]
Hi Alexandre, we use UTC = Universial Rime Corrected - and we don't show the time (nowhere), we only use it to close the blog for new edits. ;-) ... and btw what is real time?

**Comment by alexandre-mbm** [comment]
UTC as reference, each time zone per user.
