### ISSUE TITLE
how to prevent?

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#237]
![image](https://cloud.githubusercontent.com/assets/1868849/12048369/c6b32aae-aeda-11e5-9181-7a99e615140b.png)

**Comment by TheFive** [comment]
mm.

How can we prevent people doing something, that has to be done, but later ?

a) Teaching
b) permissions (there are no permissions in OSMBC yet, and thats fine to me).

**Comment by fredao** [comment]
done -

manfred [9:55 AM] 
@xxx: @xxx pushed the exported button in the English version unvolutanry (at least I hope so) :wink:
I had to reopen the blog again - so we can continue our review in OSMBC

xxx [9:56 AM] 
@manfred: Thank you :simple_smile:
...
​[9:57] 
I think @xxx would say, that he exported the html to translate it into xxxn :wink: but that is not meant with this button. :simple_smile:

xxx [9:58 AM] 
sorry i have made mistake but do not understan how reroll it
manfred [9:59 AM] 
 very easy ... I closed the whole blog and could reopen it

xxxx [10:00 AM] 
I had to write to you immediately

manfred [10:01 AM] 
no problem - I think I saw it quickly, but I suppose that Jinal would review - because we have still an issue in 284 to rewrite :simple_smile:
