### ISSUE TITLE
Proxy Error with request GET /changes/46283

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#238]
![osmbc-proxyerror-after-jsdiff](https://cloud.githubusercontent.com/assets/957501/12052427/bfd9a86c-aeed-11e5-8b96-3fd9bd5a352c.png)

---

The page do not have jsdiff (?). See #3.

**Comment by TheFive** [comment]
@400000005683f42e3293e61c /home/thefive/production/osmbc/node_modules/diff/lib/diff/base.js:171
@400000005683f42e329ba294     return value.split('');
@400000005683f42e329c796c                  ^
@400000005683f42e32fcf4a4 TypeError: Object true has no method 'split'
@400000005683f42e32fcfc74     at Object.tokenize (/home/thefive/production/osmbc/node_modules/diff/lib/diff/base.js:171:18)
@400000005683f42e32fd005c     at Object.diff (/home/thefive/production/osmbc/node_modules/diff/lib/diff/base.js:36:39)
@400000005683f42e32fd0444     at Object.diffChars (/home/thefive/production/osmbc/node_modules/diff/lib/diff/character.js:17:24)
@400000005683f42e32fd0c14     at generateHTMLDiff (/home/thefive/production/osmbc/routes/changes.js:13:21)
@400000005683f42e32fdfa5c     at /home/thefive/production/osmbc/routes/changes.js:39:40
@400000005683f42e32fe022c     at null.<anonymous> (/home/thefive/production/osmbc/model/pgMap.js:355:7)
@400000005683f42e32fe0614     at emit (events.js:95:17)
@400000005683f42e32fe0614     at Query.handleReadyForQuery (/home/thefive/production/osmbc/node_modules/pg/lib/query.js:91:8)
@400000005683f42e32fe09fc     at null.<anonymous> (/home/thefive/production/osmbc/node_modules/pg/lib/client.js:163:19)
@400000005683f42e32fe504c     at emit (events.js:117:20)

**Comment by TheFive** [comment]
```
{"oid":"314","blog":"WN284","user":"Alexandre Magno","table":"blog","property":"closeEN","from":true,"to":false,"timestamp":"2015-12-30T14:50:14.592Z"}
```
This is the compared changeset. It looks like, bool from or to values are not supported, of course.

**Comment by alexandre-mbm** [comment]
Errors yet. See https://thefive.sabic.uberspace.de/changes/46283

**Comment by TheFive** [comment]
fixed. Update tool more than 1 minute. sorry.

**Comment by alexandre-mbm** [comment]
:+1:
