### ISSUE TITLE
Error: Artcile does not exist

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#24]
![osmbc-error-article](https://cloud.githubusercontent.com/assets/957501/10256945/d73b4b72-692a-11e5-9d36-006490dd0386.png)

I don't remember the circunstance. It was not today.

**Comment by TheFive** [comment]
This happens, if you click on an article, and the article ID is not found. In this case, the series of parsing the route was "broken" and OSMBC tried to use the ID "search" to find an article, but the route was intended to call the search router.
This has been fixed some time ago.

I just add the "missing" ID in the error Message, to have more information in future.
