### ISSUE TITLE
Ugly HTML at Contributors List

### ISSUE THREAD

**Issue by Nakaner** [TheFive/osmbc#242]
Currently the contributors list is exportet like this

    <h2><i>Diese Wochennotiz wurde erstellt von Nakaner, Rogehm, Manfred, 
     escada, mgehling, stephan75, wambacher.</i></h2>

Sorry, but this is very ugly HTML. :scream: This is not a heading, it is just simple text. Use `<p>` with a CSS to modify appearance and neither `<h2>` nor `<i>`.

From my point of view the default font size is large enough, i.e. ```<p>Diese Wochennotiz wurde erstellt von …</p>``` would be good.

**Comment by alexandre-mbm** [comment]
+1

**Comment by TheFive** [comment]
I have to correct. The string is exported as:

``` html
<p align="right"><i>Diese Wochennotiz wurde erstellt von Alexandre Magno, Hedaja, Nakaner, <a href="http://blog.openstreetmap.de/blog/author/christoph">TheFive</a>, <a href="http://blog.openstreetmap.de/blog/author/manfred">Manfred</a>, escada, malenki, mgehling, stephan75, wambacher.</i></p>
```
No H2 Tag is used, just a small <i> to differ it from the normal text.

It is no problem to export et as <p class="EditorStringClassWP">, and to do the CSS in WP.
Please suggest a class string for that. I just need the info, how to format it.

The text is defined in https://github.com/TheFive/osmbc/blob/master/data/editorStrings.js. If you like, you can do a pull request.

**Comment by TheFive** [comment]
May be the WP Team has to look, how the data should be provided best way ?
Of course it is better, to have the author as native "Author" in WP, so that in his Author History the blog is shown.
Here several plugins will exist, e.g. http://pressengers.de/plugins/mehrere-benutzer-auf-eurem-blog-verwalten/ but thats not the only one i found.

**Comment by TheFive** [comment]
@nakaner How to proceed here ? Placing wrong claims in this task management, but no visible start to solve the issue on WP level, does not bring the topic to an end.

**Comment by fredao** [comment]
@TheFive @Nakaner --- I exported and imported 285 - for me it looks OK - but I did not check the html ;)

**Comment by TheFive** [comment]
I reclassify it as question. No reaction from questioner =>> closed. The Problem has to be solved on WP infrastructure. If subsequently OSMBC has to change it authors export, please open an new request.
