### ISSUE TITLE
!urgent! - OSMCalender2Markdown

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#247]
shouls collect all events please - including Mapping Parties, Hackweekends and Conferences

![image](https://cloud.githubusercontent.com/assets/1868849/12103880/82c8d792-b346-11e5-8a73-e474e6c068a7.png)

**Comment by TheFive** [comment]
I think they just have not used the correct format. Wich is missing ?

**Comment by TheFive** [comment]
Have to check, why the regex does not take that events. I do not find the difference to the other events, and there is no filter, that the events are not taken.

As alternative i suggest to copy those events by manual. I

**Comment by TheFive** [comment]
Looks like another date problem. Now you have to delete the first Events. I start 3 days earlier.

**Comment by TheFive** [comment]
If you would like to show old blog entries in the calender, you have not to delete them from the markdown :-)
