### ISSUE TITLE
new blog should start with two standard categories

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#248]
* Bild / Picture
and
* Wochenvorschau / Upcoming Events

* because we use these two categories always

**Comment by TheFive** [comment]
Can you suggest the standard text of the article, i have to generate for it.

**Comment by fredao** [comment]
if possible during Blog creation one they could containt the headers for the Upcomming Events like follows: 

|Wo                     |Was                           |Wann          |Land                      |
|---------------------|---------------------------|----------------|------------------------|

|Where                |What                         |When           |Country                  |
|---------------------|---------------------------|----------------|-------------------------|

|Dónde                |Qué                           |Fecha           |País                    |
|---------------------|---------------------------|-----------------|----------------------|

but only - if possible :) ... I will visite Galapagos still this year - to remember Darwin ;-)

**Comment by fredao** [comment]
the content in Bild / Picture would be helpful

![Logo](here the link from WordPress)
caption [[1]](#wnXXX_bild_XXX) | additonal Info []()

**Comment by TheFive** [comment]
I suggest to rename the link in the picture, not the article.

**Comment by fredao** [comment]
like that?

`![Logo](here the link to the uploaded picture in WordPress)
caption [[1]](#wnXXX_HereTheTitleOfTheArticle) | additonal Info []()`
