### ISSUE TITLE
blog difference in shown date and blog date

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#249]
blog date
![image](https://cloud.githubusercontent.com/assets/1868849/12104078/3eba7482-b348-11e5-83fa-f9514957cab7.png)

shown date
![Uploading image.png…]()

**Comment by TheFive** [comment]
Yes, of course. The time is London time, the date is taken with Berlin Timezone. please try 22:59 as time. I will try to use the timezone berlin in that editor.

**Comment by fredao** [comment]
what about delete the "Z" in time?

**Comment by fredao** [comment]
I changed the date for the current blog as follows 

![image](https://cloud.githubusercontent.com/assets/1868849/12109889/aa7ae538-b386-11e5-8990-2efb5a6d2e7e.png)

**Comment by fredao** [comment]
Tests in DEV looking good - please don't change the code.

**Comment by alexandre-mbm** [comment]
What about change the format from the `2015-12-29T01:00:00.000Z` to `2015-12-29 01:00`?

**Comment by TheFive** [comment]
See https://github.com/TheFive/osmbc/issues/249#issuecomment-168917319

**Comment by alexandre-mbm** [comment]
And things like `2015-12-29 01:00 UTC` and `2015-12-28 22:00 GMT-3`?

**Comment by TheFive** [comment]
I will change the display in NON Edit mode to the same as in blog display. Same timezone. 
I hope as a first step it helps, as after the time is put in correct, the automatism will work without any support (i hope :-))
