### ISSUE TITLE
Error: [home page] Not found

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#25]
![osmbc-error-not-found](https://cloud.githubusercontent.com/assets/957501/10256985/18d21b42-692b-11e5-9990-b7bdc0609ab7.png)

When I clicked the button for "back" at browser. It was not today.

**Comment by TheFive** [comment]
You have to use osmbc.html to call the Homepage of OSMBC, i will make the routes more "tolerant", and accept the /osmbc route as homepage.

**Comment by alexandre-mbm** [comment]
I didn't written the URL, I clicked the "back" button
