### ISSUE TITLE
blog difference in shown date and blog date

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#250]
blog date
![image](https://cloud.githubusercontent.com/assets/1868849/12104078/3eba7482-b348-11e5-83fa-f9514957cab7.png)

shown date
![image](https://cloud.githubusercontent.com/assets/1868849/12104123/b2b42a36-b348-11e5-854d-0ac3875a82a2.png)

**Comment by fredao** [comment]
why the hell I closed the issue - it should be open! :)

**Comment by alexandre-mbm** [comment]
If it is equal to #249, this (closed) can be erased.
