### ISSUE TITLE
Data pushed with Word Wrap from some browsers in article markdown.

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#251]
See also #232.

It looks like that in some cases, browsers are adding whitespace to a textfield. There are different WRAP options in HTML5, that may be interpreded different by different browsers. 
Typically this error can be reproduced, by resizing your browser and saving article data.

I have colored the article diff detailled view, that the effect can be visualized.

This issue is to collect all environments the problem is occuring in, and give any additional helfull hint to the developer.

**Comment by TheFive** [comment]
@fredao is this still a problem with some browser ?

**Comment by fredao** [comment]
Resolved - pse close the Issue
