### ISSUE TITLE
links with non standard characters are not identified in full in article screen

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#252]
please see the example:

![image](https://cloud.githubusercontent.com/assets/1868849/12156717/ff352880-b4cc-11e5-8b45-be70aa337b22.png)

**Comment by TheFive** [comment]
hast du einen link zum Artikel ? Danke Die osmbc Suche mag nur ganze Worte.

**Comment by fredao** [comment]
sorry, dass ich Dich nicht anschlussfähig machte :( 

http://thefive.sabic.uberspace.de/article/10762?style=overviewDE(EN)&edit=true
und der komplette Link ins Netz: http://www.openstreetmap.org/user/Severák/diary/37681

HTH

**Comment by TheFive** [comment]
I thought i can avoid UTF8 F.. O... 
But java Script regex in browser does not eadily support it. Will search for a library for it.

**Comment by fredao** [comment]
Not as important ;-)

**Comment by TheFive** [comment]
Ah, as UTF8 Characters are allowed in OSM User Names, and OSM User Names are in the interest focus of WN + Weekly i will try to find a simple solution. And as i damn all software providers, that does not support UTF8, i have to use this measure against OSMBC too as long as there is no valid excuse.

**Comment by fredao** [comment]
+1
