### ISSUE TITLE
Hint: in diffs, green for new content

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#256]
Ref.: http://thefive.sabic.uberspace.de/changes/47348

**Comment by fredao** [comment]
It was green and switched for people who suffer red green blindness

**Comment by TheFive** [comment]
I will put in a legend, and change the history in the article to the new colored mode too.

**Comment by alexandre-mbm** [comment]
And cyan?

**Comment by alexandre-mbm** [comment]
Or: would not be better using background colors?
