### ISSUE TITLE
is there any possibility to integrate Conferences into the 3 weeks preview of the Upcoming Events?

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#257]
![image](https://cloud.githubusercontent.com/assets/1868849/12220965/7955d940-b787-11e5-9d2e-865809df5d87.png)

as it is done in the calendar?
![image](https://cloud.githubusercontent.com/assets/1868849/12220971/085946c2-b788-11e5-9811-dc828cde3c83.png)

**Comment by TheFive** [comment]
ALL upcoming events are integrated in the calendar. If something is missing, please tell me exactly what you miss, and i try to find out why :-)

**Comment by fredao** [comment]
I am not missing anything. ;-) In the 2nd screenshot you can see items for August and September - these are Confernences. They are displayed even the date is far in the future. :) ... See above the second screen ... I the wiki-calendare there are a lot of appointments "normal" appointments between 30-31. Jan and they are not shown, because that are unimportment meetings. HTH ;-)

**Comment by TheFive** [comment]
So you would like to have the time window based on the type of the event ?

**Comment by fredao** [comment]
no, no 
additinonal hint: http://wiki.openstreetmap.org/wiki/Template:Calendar
here you can see, that these conferences have a certain priority - to be shown up always ... let as say a a permanent reminder :)

**Comment by fredao** [comment]
... but to be fair ... I think, it looks to complicated because OSMBC must check the whole wiki-calender and display for the weekly the upcoming events + the conferences - even if they are in a very distant future.

**Comment by TheFive** [comment]
OSMBC is checking the whole calender and throws everything out, that is not in the next 3 weeks.
So if i have a definition, which kind of event i have to use another throw out critera for, i can do that.

**Comment by TheFive** [comment]
Normal Event -> 3 Weeks
Special Event -> 1 Year ?
Stammtisch ? -> two weeks ?

**Comment by TheFive** [comment]
But this will result in reminding to a big conference EVERY week.

**Comment by fredao** [comment]
yes, that was the idea ... as it is here in "current events"
but I withdraw the idea - please close the issue ... and sorry for bothering ...
this idea falls into  Darwin's categorie :)
... what stays ... "good, that we talked about it" :)
