### ISSUE TITLE
bug - http://thefive.sabic.uberspace.de/language?lang2=EN

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#259]
if you choose any language you always see this as a result:

![image](https://cloud.githubusercontent.com/assets/1868849/12222207/9c54f682-b7b5-11e5-87c1-77489d87d37e.png)

**Comment by alexandre-mbm** [comment]
Use it is impossible.

**Comment by TheFive** [comment]
Hi Alexandre, i didn't see you on the testenvironment, otherwise you would have know, that nothing is instable.
There was only a defect routing in the .httpaccess.

**Comment by alexandre-mbm** [comment]
Okay. Thanks. Yes, I use only the stable instance.
