### ISSUE TITLE
Create a static page which holds code snippets for flags

### ISSUE THREAD

**Issue by Nakaner** [TheFive/osmbc#26]
Wochennotiz prints country flags after links which are neither German nor English. Please create a page which offers codes snippets for copy past (currently hosted at Rizzoma).

    ![(Japanisch)](http://blog.openstreetmap.de/wp-uploads//2015/02/jp.svg)
    ![(Französisch)](http://blog.openstreetmap.de/wp-uploads//2015/01/fr.svg)
    ![(Spanisch)](http://blog.openstreetmap.de/wp-uploads//2015/01/es.svg)
    ![(Brasilianisches Portugiesisch)](http://blog.openstreetmap.de/wp-uploads//2015/01/pt-br.svg)
    ![(Tschechisch)](http://blog.openstreetmap.de/wp-uploads//2015/01/cz.svg)
    ![(Russisch)](http://blog.openstreetmap.de/wp-uploads//2015/07/ru.svg)
    ![(Niederländisch)](http://blog.openstreetmap.de/wp-uploads//2015/07/nl.svg)

Extensions to this list could be requested via a Github issue, i.e. the pages does not have to be modifiable by users.

**Comment by TheFive** [comment]
First i thougth, i extend markup, but that will be a compatibilty problem, using our markup with other converters. 
Just edit an article and you will find the solution.

OK ?

**Comment by alexandre-mbm** [comment]
And if it was in a fast action menu?

**Comment by TheFive** [comment]
Current solution is:

Flags are shown in edit mode and copy the text to the clipboard when clicked on it.
I was not able to execute the paste command in the last focus field yet.

**Comment by alexandre-mbm** [comment]
I want suggest also flags to adding while translating, and more countries.
