### ISSUE TITLE
would it be possible create the attached table parsing the data from http://wiki.openstreetmap.org/wiki/Proposed_features/*

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#262]
![image](https://cloud.githubusercontent.com/assets/1868849/12241257/7d0ffaf0-b892-11e5-8337-85832e02988d.png)

**Comment by TheFive** [comment]
I think that is a good idea for additional development power. Very small interface.

Requirement: it should be a asynchronos java script function, thst just generates markdown from wiki.

See calender parser as sample.

**Comment by TheFive** [comment]
I can not find the list in a compact form in the wiki. I think this inflate OSMBC to much.
