### ISSUE TITLE
Upcomming events should have country flags.

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#267]
discussion in WN channel has the following result:

Stadt (Flagge@Land) Was Datum

Countries should be represented by a flag, and not in words:  in favor 3 of 3 ;-)

**Comment by TheFive** [comment]
Question, is the list of used countrys in calender wiki a subset of the list of language flags ?

What is with Switzerland, Austria, Belgium ?

**Comment by fredao** [comment]
They all have only one flag representing that country.

**Comment by TheFive** [comment]
Yes, but not in the list of flags, that is supported by blog.openstreetmap.de, i just need the svg of the countrys.

**Comment by fredao** [comment]
ok, now I got it :) ... have to talk to Nakaner :)


2016-01-14 10:16 GMT+01:00 TheFive <notifications@github.com>:

> Yes, but not in the list of flags, that is supported by
> blog.openstreetmap.de, i just need the svg of the countrys.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TheFive/osmbc/issues/267#issuecomment-171581738>.
>



-- 
## Manfred Reiter - -
## www.weeklyOSM.eu

**Comment by TheFive** [comment]
weitere Länder haben in den nächsten 9 Monaten keine Events

**Comment by TheFive** [comment]
Folgende Flaggen sind jetzt in WP: tw, ch, it, us, at, ph, be, ar.svg
