### ISSUE TITLE
Prevent user duplication

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#268]
The user named [pizzaiolo] was created by @fredao. It was right. But when the real user tried use the system, he was duplicated in the [usert/83]. This probably is fixed now.

Okay, I also know that it doesn't happen very often, and that to fix it, it would necessary to write code... but I want submit this issue to the TheFive's insight. It is possible the new code be minimal, perhaps.

[pizzaiolo]: http://thefive.sabic.uberspace.de/usert/76
[usert/83]: http://thefive.sabic.uberspace.de/usert/83

Today already are many "ztrash" and "Missing Name" users.

**Comment by TheFive** [comment]
See https://github.com/TheFive/osmbc/issues/96
