### ISSUE TITLE
Why have two switches to change languages?

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#269]
![osmbc-visual-pollution](https://cloud.githubusercontent.com/assets/957501/12340922/c4cab0e4-bafc-11e5-9392-2cebbadf9484.png)
**My opinion:** it is a visual pollution and also unnecessary complexity.

**My hint:** we having only the top switch.

**Comment by fredao** [comment]
Thanks for opinion and hint.
It is temporary and there is a reason.

**Comment by fredao** [comment]
@Alex: What about writing some documentation for newbies? Maybe nice screenshots with explanation s?

**Comment by alexandre-mbm** [comment]
> What about writing some documentation for newbies? Maybe nice screenshots with explanations?

I spoken that I would do this, but I do not did. I do not want the same mistake, then I will not promise. I speak just that "I would want to do it". Certainly I will need teach something to Nicolas through e-mail. Some orientation I will send with CC to you (but will be messages in portuguese, and for demand).

**Comment by TheFive** [comment]
Just to let everyone realize the change. Will be switched off in a future upgrade.
