### ISSUE TITLE
WNAuthor: change unwanted

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#273]
![osmbc-wnauthor-change-unwanted](https://cloud.githubusercontent.com/assets/957501/12463526/b2ac1f6a-bfa2-11e5-8e33-8009181ee16b.png)

I had not typed in that field. Surely.

**Comment by TheFive** [comment]
Will review Jade Code & trim values. i think this helped in article.

**Comment by TheFive** [comment]
Oh, may be i have to review the only spaces added function. This is the change in detail.
![image](https://cloud.githubusercontent.com/assets/6240370/12473362/ec2e4b36-c011-11e5-93c3-6c450b91979d.png)

**Comment by TheFive** [comment]
BTW as there are no visible users in the weekly, these fields are unused now.

**Comment by alexandre-mbm** [comment]
I would want to use just "Alexandre" at OSMBC.

**Comment by TheFive** [comment]
I just render OSM User Name or blog.openstreetmap.de names now.
Warning: this task will automatic be closed by github, as doon as the fix goes live.
