### ISSUE TITLE
would it be possible to have the number of "all" articles in that blog?

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#275]
![image](https://cloud.githubusercontent.com/assets/1868849/12510357/a60670ea-c109-11e5-8eef-c8589611e5ec.png)

i. e. WN288  50 37 33

**Comment by alexandre-mbm** [comment]
In a box when a mouseover event.

**Comment by TheFive** [comment]
Will put that in the (more) part of the overview blog list. I will try to put that "quickly" == "untested" online, so could you please to some sample counting for me (@fredao)
