### ISSUE TITLE
is it possible to to *not export* the Blog Missing Cat: --unpublished-- 

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#276]
![image](https://cloud.githubusercontent.com/assets/1868849/12522278/10463d50-c150-11e5-9e7d-1f6dc8a3ee82.png)

**Comment by alexandre-mbm** [comment]
+1 :+1:

**Comment by TheFive** [comment]
of course, if i know that the system is broken here, i will fix it.

**Comment by TheFive** [comment]
I think i will revert this fix. Uncategorized articles are waiting for a move to unpublish, future, next WN or someone who writes an article. The given link list helps in quickly doing that (moving to unpublish).
My Idea is, that the data in OSMBC is close to what is published, so i would like to have this decision docuemted in OSMBC.

**Comment by TheFive** [comment]
The not and the meta not in the brain. Will extend tests and fix it again :-)
