### ISSUE TITLE
Make hyperlink Button for markdown.

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#29]
Build a button that puts selected text in [] followed by ().

**Comment by TheFive** [comment]
After thinking about it, and throwing away 3 ideas, i would like to follow the following.

If you paste a Hyperlink to a markdown field, it is pasted with [](), only if there is no bracket around the link. If you paste a hyperlink and there is removed text, this text becomes the visible part of the link, so that [selected text](copy from clipboard text) is the result.

**Comment by fredao** [comment]
+1000

**Comment by fredao** [comment]
This feature would spare hours of stupid editing!
Please vote!!!

**Comment by alexandre-mbm** [comment]
:+1: 

Hint: a integrated editor like a subset of the editor Jetpack for Wordpress. The full Jetpack is like this:

![Jetpack for Wordpress as example of integrated editor ](http://cdn.elegantthemes.com/blog/wp-content/uploads/2014/10/Jetpack-Editor.jpg)

- [ ] Remember of [syntax highlighting](https://en.wikipedia.org/wiki/Syntax_highlighting)

**Comment by alexandre-mbm** [comment]
cef823fae099f0363eff1fae34837e224eae77a2?

**Comment by alexandre-mbm** [comment]
> - Pasting on word selected creates `[word ](link )` "wrong" codes.

Now it is happening:
```
[word
](link
)
```

Line break instead of spaces.

**Comment by alexandre-mbm** [comment]
Seems that it is the character at front of word: space, line break, comma...

**Comment by TheFive** [comment]
I have fixed it, but it is not a good idea to report errors on a closed issue, without email notification github is not informing you.

**Comment by alexandre-mbm** [comment]
Informing you or me? I am watching the repository and I receives the notifications for this issue.
