### ISSUE TITLE
Filter @Name

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#291]
doesn't work

**Comment by TheFive** [comment]
mm in my testcase it works for @DE later in a comment, but not at the first character with @ES.

**Comment by TheFive** [comment]
![image](https://cloud.githubusercontent.com/assets/6240370/12697724/5564608e-c78a-11e5-909e-6d99caa077a9.png)
Working with @ES in front to. (tested on localhost, not development).

**Comment by fredao** [comment]
it works even for @wambacher ;-)
