### ISSUE TITLE
the existing links those we can drag to Markdown should generate the complete *Text* including the link itself

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#292]
Example – DE
(automatische Übersetzung) 
`(automatische [Übersetzung](https://translate.google.de/translate?sl=auto&tl=%20DE&u=http://www.geografiainfinita.com/2016/01/la-evolucion-del-mapa-de-carreteras-en-espana/))`

Example – EN
(automatic translation)
`(automatic [translation](https://translate.google.de/translate?sl=auto&tl=EN&u=http://www.geografiainfinita.com/2016/01/la-evolucion-del-mapa-de-carreteras-en-espana/))`

**Comment by TheFive** [comment]
Start working on it.
The first try: Convert HTML Drag & Drop content to markdown when dropping looks not promising yet,  in the next step i will try to catch the correct markdown while dragging something. This may lead to drag & drop for country flags too.
