### ISSUE TITLE
Use kpdecker/jsdiff to show differences in Change Object

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#3]

**Comment by alexandre-mbm** [comment]
Repo: https://github.com/kpdecker/jsdiff &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Demo: http://kpdecker.github.io/jsdiff

**Comment by alexandre-mbm** [comment]
Ref.: https://thefive.sabic.uberspace.de/changes/46290

![osmbc-jsdiff-fullgreen](https://cloud.githubusercontent.com/assets/957501/12052410/87072320-aeed-11e5-90ac-7712009d2194.png)

It is not right.

**Comment by TheFive** [comment]
it is.

**Comment by alexandre-mbm** [comment]
Ah! It is true. Sorry. I had in mind other change:

![osmbc-jsdiff-ok](https://cloud.githubusercontent.com/assets/957501/12052532/b14a7dca-aeee-11e5-817d-32350050da99.png)

**Comment by TheFive** [comment]
What is the problem here ?
if you are not attired in jsdiff results, please contact them directly :-)

**Comment by alexandre-mbm** [comment]
None. My mistake. I saw that all is right.

I in my last message:
> Ah! **It is true. Sorry.** I had in mind other change:
