### ISSUE TITLE
Restrict empty article search on OPEN Blog

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#30]
Empty article now searches for articles of all categories. It should only find empty articles in open blogs. (Review articles should not have empty articles).

While doing it, it may be better to have the following search.

a) Empty Article (no markdown and markdownEN)
b) Translate EN -> DE (markdownEN exists, but markdown not)..
c) Translate DE -> EN (markdonw exists, but markdownEN not).

**Comment by fredao** [comment]
IMHO the signs in the OVERVIEW 
-> Edit& Translate 
or Edit 
or Translate 
are absolutely sufficient!

**Comment by TheFive** [comment]
There is no a search for the current open and current review blog.
