### ISSUE TITLE
successful email change should be confirmed

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#306]
Example: "OSMBC now use ....

**Comment by TheFive** [comment]
Via mail ?,
I have added a log to the log file, and the email in the email field is always a validated one.

**Comment by TheFive** [comment]
Is it OK to document it in the history like this ?
![image](https://cloud.githubusercontent.com/assets/6240370/13018825/3aab7ec0-d1cc-11e5-86c8-9e39a6f79d49.png)

**Comment by TheFive** [comment]
@fredao 
Is the entry from https://github.com/TheFive/osmbc/issues/306#issuecomment-183469527 OK, or did you mean to send out a "had worked" email.

**Comment by fredao** [comment]
yes, "worked" "subscribed" or what ever
