### ISSUE TITLE
Begin and End of a blog should be correct

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#308]
![image](https://cloud.githubusercontent.com/assets/1868849/12929540/91bb5740-cf73-11e5-8ab6-2b1a8174211b.png)

1. start is incorrect
2. the end is incorrect
correct would be: 09.02.2016 until 15.02.2016

and the start time should not be 23:59:00 but 00:00:00

**Comment by alexandre-mbm** [comment]
The page should declare the timezone.

**Comment by TheFive** [comment]
Looks like the add 24 hours rules troubles with timezone.

End Date WN290: 2016-02-08T23:59:00.000
Start Date WN291: 2016-02-09T23:59:00.000Z

**Comment by TheFive** [comment]
It is important to use TRUE ISO String for the blog time. 
The software is using 2 different interpreter, the standard date object and momemt.js. As moment.js is a little bit more tolerant than the date object, the differences occur.

**Comment by TheFive** [comment]
See #355 to switch the software to momemt.js.
