### ISSUE TITLE
email on status switch is buggy

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#311]
I did not receive an email neither from
Open -> Edit
nor from
Edit -> Review

**Comment by TheFive** [comment]
That is implemented, but has no implemented frontend. 
There was a @fredao that said, that feature is not important, so I did not publish it to keep OSMBC simple.

**Comment by TheFive** [comment]
But Edit -> Review should work, because Review is only a language specific information. So for wich language you did not receive the review status ?

**Comment by TheFive** [comment]
This is an testemail send out from my local system to me, because of startreview ES:
![image](https://cloud.githubusercontent.com/assets/6240370/12941508/641e87b6-cfd3-11e5-8933-ee4914543cf9.png)
BTW. is buggy is not really a helpful changelog message, when the bug is fixed.

**Comment by TheFive** [comment]
Looks funny. 
http://thefive.sabic.uberspace.de/changes/mail/2016-02-09
(i will add a sort by timestamp), there is no mail gone out after 15:00
The earliest mail from today ist after 08:33.

As i could not beleave, that there was no OSMBC change in the time between, i have to check the mailsender mechamism.
