### ISSUE TITLE
Blog Charts are not recalculated and frozen.

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#312]
http://thefive.sabic.uberspace.de/blog/WN290

**Comment by fredao** [comment]
Sorry I see only untranslated and only one translated

**Comment by alexandre-mbm** [comment]
unstranslated = those markes as "no translation"

**Comment by TheFive** [comment]
Its a bug, sometimes (may be at first review) OSMBC stores the numbers in the database and stops recalculating.

**Comment by alexandre-mbm** [comment]
Label it.

**Comment by alexandre-mbm** [comment]
:+1:
