### ISSUE TITLE
Only e-mails regarding collections (in really: translations) that can be translated by me

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#316]
I am only translator, not writer. I can create collections exceptionally, only. For who is like me,  it is not interesting receiving e-mails for each collection created, but about those that already can be translated from your (my) languages.

**Comment by TheFive** [comment]
Just switch the field off in your user settings.

**Comment by alexandre-mbm** [comment]
Like are [today](http://thefive.sabic.uberspace.de/usert/13)? Would I see new articles in English to be translated into Portuguese?

**Comment by TheFive** [comment]
Thats not implemented yet, if there is a need, i will do.
