### ISSUE TITLE
Diary mail

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#321]
Summary. To economize mail server and mail boxes.

**Comment by TheFive** [comment]
If you are not interested in the mails, please disable the feature and wait for the Slack integration.
This feature is not on my plan now, as mails are direct send out, when something changed, this is a bigger change request.

**Comment by alexandre-mbm** [comment]
Done. The feature is suggestion to be optional. I presume that the project is paying for emails...

**Comment by TheFive** [comment]
I have a pay what _I_ like Flat rate provider :-).

**Comment by alexandre-mbm** [comment]
But is it based in limits, is not?

**Comment by TheFive** [comment]
Limits in memory usage, drive space and - haven't recognized - connection speed.

**Comment by TheFive** [comment]
https://uberspace.de

**Comment by fredao** [comment]
@alexandre-mbm stupp discussions, study! :)
you can get all these info even when you get the job. ;-)

**Comment by alexandre-mbm** [comment]
@fredao, you have reason. Thank you very much. Bye all!

**Comment by fredao** [comment]
@alexandre-mbm volta sempre depois da entrevista :)

**Comment by TheFive** [comment]
I put it on to vote, to give other user the possibility to indicate a need.
