### ISSUE TITLE
Double click on review comment results in two slack messages

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#325]
zweimal DOPPEL 

![image](https://cloud.githubusercontent.com/assets/1868849/13020915/45b9e854-d1d8-11e5-9059-3380d1f24acb.png)

Erklärung: Es ist Doppel oder Dreifachklick auf dem Button möglich.
Dies löst eine Email aus! :)

**Comment by TheFive** [comment]
Du tstest Sachen, Schutz vor Doppelklick ist natürlich nur halbherzig implementiert.

**Comment by fredao** [comment]
Vergiss es.;-)
Machen nur staatlich geprüfte ß-Tester

**Comment by TheFive** [comment]
kenn genug, die so am computer sitzen. Und ich muss ja sicherstellen, das er sich nicht auf die Nase legt

**Comment by fredao** [comment]
Du meinst jetzt aber nicht Tattergreise ;-)
