### ISSUE TITLE
Redirect to article after login

### ISSUE THREAD

**Issue by malenki** [TheFive/osmbc#328]
When clicking a article link (e.g. from an OSMBC mail) and needing to login, after the login the user lands on the OSMBC main page instead at the article. A redirect in this case would be nice.

**Comment by TheFive** [comment]
I tried it in several combinations (with or without https).
It works for my on my local machine / test environment & production.

Do you have more information, when the problem occures ?

**Comment by malenki** [comment]
I use the https links provided in the notification emails.

On Firefox 44.0.2 with several protect-privacy-plugins (though most
OSM-foo is allowed) usually the first login try results in
"failed to find request token in session", probably due to some missing
rule in NoScript (doesn't bother me much).
Clicking on "go back" then again on "grant access" results in showing
http://thefive.sabic.uberspace.de/osmbc.html

With Chromium 48.0.2564.82 (Adblock plus, whitelisted for vanilla)
after login I am redirected to http://thefive.sabic.uberspace.de/

TheFive wrote
on Sat, 20 Feb 2016 03:20:02:

> I tried it in several combinations (with or without https).
> It works for my on my local machine / test environment & production.
> 
> Do you have more information, when the problem occures ?

**Comment by TheFive** [comment]
I am a little bit helpless on that.

The root http://thefive.sabic.uberspace.de is never set by the loginsoftware, the page is used to route to osmbc, so i assume this can be a client redirect.

In case of new authentification need, I store the link in the session. You got an error message, that CAN be interpreted, that this fails. 
If there is no redirect in the session, the login reroutes to the OSMBC Home Page.

**Comment by TheFive** [comment]
Seems to be a problem in the combination of 
http(s) & reverse proxy on uberspace.

**Comment by TheFive** [comment]
I have enabled a redirect to HTTPS in the .htaccess file from uberspace. It looks like, that this can fix the issue. Can you please check ?

**Comment by malenki** [comment]
Tested on FF 45.0.2 and Chromium 50.0.2661.75:
Works like a charm.

Thanks!

**Comment by TheFive** [comment]
Fine, thanks for feedback.
