### ISSUE TITLE
parsing countryFlags.js

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#339]
**maybe** a bug:

Error during convert

Unrecognized
| {{cal|conference}} || {{dm|Feb 22-23}} || TAF & CR+ID Crowd-sourced Mapping Workshop using OSM, [[Prosperidad]], Agusan del Sur, [[Philippines]] {{SmallFlag|Philippines}}
| {{cal|conference}} || {{dm|Feb 23-24}} || TAF & CR+ID Crowd-sourced Mapping Workshop using OSM], Tandag City, Surigao del Sur, [[Philippines]] {{SmallFlag|Philippines}}

**Comment by TheFive** [comment]
Can you check the syntax in the wiki, looks like that there are many commas in the string, and OSMBC, so that the string could not be parsed.

**Comment by fredao** [comment]
I checked it, Harry Wood checked it, but I will do again it right now ... - to be save :) -

**Comment by fredao** [comment]
can you please tell me what are the separaters for your parsing?
I deleted all commata now ... same result

**Comment by fredao** [comment]
same result:

Unrecognized
| {{cal|conference}} || {{dm|Feb 22-23}} || TAF & CR+ID Crowd-sourced Mapping Workshop using OSM, [[Prosperidad]] Agusan del Sur, [[Philippines]] {{SmallFlag|Philippines}}
| {{cal|conference}} || {{dm|Feb 23-24}} || TAF & CR+ID Crowd-sourced Mapping Workshop using OSM], Tandag City Surigao del Sur, [[Philippines]] {{SmallFlag|Philippines}}

**Comment by fredao** [comment]
NOT A BUG!!!!

**Comment by TheFive** [comment]
The Regex for parsing can be found here:
https://github.com/TheFive/osmbc/blob/master/model/parseEvent.js

There are several regex, if the string does not fit to anyone it is put to unrecognized.
