### ISSUE TITLE
once a textbox in Markdown is set to any content (normally: no translation)  it not possible to clean it up

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#342]
please try to clean up the Markdown textbox
http://thefive.sabic.uberspace.de/article/11248?style=OVERVIEW&edit=true

**Comment by TheFive** [comment]
Can you describe the case in a little bit more detail. if i click on that link, i do not see anything looking wrong to me.

**Comment by TheFive** [comment]
The grey text is - standard html feature - a placeholder. this is not field text, but displayed as soon as the text is empty. If there is anything IN the field, the content is taken.
You are not allowed in just entering spaces, they are trimmed away. a "-" should work.

**Comment by TheFive** [comment]
Now i understand. Yes it is not possible to clean an entered markdown, but this makes sense, of course.
