### ISSUE TITLE
Implement Marketing for Weekly

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#343]
Allow a marketing per language.

e.g. Mailing Lists, Twitter, Forum (?) ..

it should allow highlighting of special topics.

**Comment by fredao** [comment]
+1

with the possiblity to _merge_ standard text with an individual text each week
Standard text is in standard text markup - indivual added text is in **bold**

Example: 
the weekly round-up of OSM news, issue # 291, is now available online in English, giving as always a summary of all things happening in the OpenStreetMap world:

http://www.weeklyosm.eu/archives/6924

**Among others:
* Know more about the volunteer- provided local information in OSM helps individuals ...
* Know more about the WMS offering leafless aerial imagery ...
* Know more about the solution for a strange GUI error in JOSM when used in Debian/Ubuntu ...
* There is a video tutorial about how to use ImproveOSM ...
* Know more about the plans of Arun Maharajan to map and help small and lesser known businesses in slums of Mumbai, India ...
**
Enjoy! weeklyOSM is brought to you by ... https://wiki.openstreetmap.org/wiki/WeeklyOSM Cheers,

Jinal Foflia

**Comment by TheFive** [comment]
I skip this request. I think Forum & Twitter announcment would be better to do "personally" and my support for mailing lists is "Well Known".
