### ISSUE TITLE
No Translation

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#37]
the delivered list should show only issues which are not in --unpublished--

**Comment by TheFive** [comment]
Can you put a Link as example.
In Preview mode the --unpublishied-- is Filtered, as soon as it is not in "Edit" Mode. In Download "--unpublished--" is extracted, too.

**Comment by fredao** [comment]
sorry to not as precise as one should be ... shame on me :( 
http://thefive.sabic.uberspace.de/article/list?markdown=
or
http://thefive.sabic.uberspace.de/article/list?markdownEN=
Reason: I searched for not written articles and missing translations ... and if the --unpublished-- would be filtered that would be great ...

**Comment by TheFive** [comment]
You are right, these search finds trash article also and has to be improved.

To ease the time until impementation put a - or an other char in the translation. I did it for some trash articles too.

**Comment by TheFive** [comment]
See #41.

**Comment by TheFive** [comment]
I just add that only open articles are found.

**Comment by TheFive** [comment]
Implementet, waiting for rollout.
