### ISSUE TITLE
Tagging unpublished/trashed posts

### ISSUE THREAD

**Issue by PedaB** [TheFive/osmbc#371]
Whenever articles are moved to unpublished or to trash, it is hard for others to judge if that decision was correct. We had cases where stuff got moved accidentally. So it would be nice to tag such articles with a reason. Some of us are doing this by prefixing the title with something e.g. "[doublette]" or "[old]".

It would be great if that happens automatically. E.g. whenever something gets moved to unpublished or trash, the user should be queried to select one or more reasons from a checkbox for the reason. And these reasons should be added to the title.

**Comment by fredao** [comment]
check boxes:
# old
# not relevant / no reference to OSM
# doublette
# merged in an other article
# we reported about it earlier
# free text (if possible)

**Comment by TheFive** [comment]
OK, Comment function is not enough ?

As long as there is no need for statistics on trash or unpublished articles (e.g. Author X has the highest doublette count) i am a fan of free text.

I can force the user to add a text in brackets [] to the title (as i assume, you would like to see the reason in the blog views.
I can add an additional field with no problem, but the question is, when to pop this field up. I can show that field, as soon as an article is "unpublished" or in "trash", but that is showed AFTER moving to unpublished, or i have to implement a more dynamic behavior, that the reason field is shown as soon as the user tries to move the article, but moving can only be closed, if the field is filled out.

**Comment by PedaB** [comment]
I have no problem with free text if you prefer that. As you correctly assumed: The reason why I'm asking is to have a quick overview in the blog view / trash view. This way there wouldn't be a need to click on every single item again to be sure.

**Comment by TheFive** [comment]
i have to solve one design question, before i start.
is the comment more like a change comment in git, documenting why you did something, or is it more a status on an article, that is historised like the other values.

**Comment by PedaB** [comment]
I'm not quite sure, but I think it's more of a status on an article. 

As I said, my use-case would be to have a quick overview of why a article got unpublished. I sometimes see such articles with meaningful and good titles and I wonder "why did this one got removed" or "shouldn't that be rather in Future than in Trash" and so on. If I quickly see that this one's a doublette it would make the progress of checking the articles more quickly.

**Comment by TheFive** [comment]
OK, as my experience is, that every concept will be used for further things, that was not though of in design, later, i just want to go in the right direction. Than i will go for "Status" and may be do some suggestions by a selector in combination with free text.

**Comment by fredao** [comment]
here you see good and bad expamples: 
![image](https://cloud.githubusercontent.com/assets/1868849/13631152/672877d4-e5e3-11e5-92ab-a7830601fabf.png)
