### ISSUE TITLE
OSMBC stops counting for all other languages, if one language is set to review

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#372]

**Comment by fredao** [comment]
![image](https://cloud.githubusercontent.com/assets/1868849/13634907/c71f3e2e-e5f8-11e5-857d-f7a0321562b5.png)

**Comment by TheFive** [comment]
See although https://github.com/TheFive/osmbc/issues/312

**Comment by TheFive** [comment]
mm same blog, same OSMBC Version, different results in counting
![image](https://cloud.githubusercontent.com/assets/6240370/13646489/fd9fde2c-e62f-11e5-8b31-7076fed4c700.png)

**Comment by TheFive** [comment]
Do you have more information, when this occured ?

**Comment by TheFive** [comment]
Closed because missing information. Please open a new issue, if this occurs again.
