### ISSUE TITLE
Allow entering an email address for an invite to OSMBC, default the mail options pragmatic.

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#374]
As you only have the right to show your email address or not - please put your email here ....

**Comment by fredao** [comment]
Anmerkung: das sollte gemacht werden, weil man keine "Neuen" mehr mit Email erfassen kann.

**Comment by TheFive** [comment]
I suggest to allow entering an email for new users.

**Comment by TheFive** [comment]
Can you suggest some good defaults for the mail configuration. I think the current ones are horrible.

**Comment by fredao** [comment]
Mail a new Collection:  OFF
Mail All Comments: OFF
Mail defined comments: corresponding to Language AND to OSM-Name
Mail Status Change: corresponding to Language

**Comment by TheFive** [comment]
mm, looks like, that i have to default all to 0, as language & username is not known, when i like to default the values (in creation process).
