### ISSUE TITLE
Sort doesn't work

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#389]
http://thefive.sabic.uberspace.de/usert/list?access=full&sort=lastAccess&desc=true&lastAccess=!=never

**Comment by TheFive** [comment]
mm this link looks OK to me, how did you get there ?
![image](https://cloud.githubusercontent.com/assets/6240370/13790343/46b16d4e-eae8-11e5-8a70-b2b99b4d3b8b.png)

**Comment by fredao** [comment]
In the link I added to the issue (see above) the sort doesn't work.

![image](https://cloud.githubusercontent.com/assets/1868849/13790893/cfb61c96-eaea-11e5-9171-46c5e823d0b7.png)

nevertheless it works in all other Lists.
so please close the issue.

**Comment by TheFive** [comment]
No i would like to understand your issue. Basis for that is information and not a pure link.

Which field do you want to sort and for which field the result is wrong ?

**Comment by TheFive** [comment]
P.S. i do not sort for OSM Changes for two reasons: 
a) data model
b) think it is unnecessary to have "ranking" lists of contribution. The idea is, that newbees can see, who is more active or not.

**Comment by fredao** [comment]
the issue is as follows:
The side above contains links.
You know user. - They click on links. ;-)
Maybe you can erase the links from that side.

**Comment by TheFive** [comment]
now I got it, all links are not working. thats crazy (the all worked before i published)

**Comment by TheFive** [comment]
fixed
