### ISSUE TITLE
User [[]] wiki syntax in full for calender parser for town / country

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#394]
Here is an example where people use wiki syntax for the town specification ```[[Santiago,_Chile|Santiago]]``` that is not correct handled by OSMBC.

```
 {{cal|pizza}} || {{dm|Apr 22|Apr 24}} || [http://spaceapps.cl International Space Apps Challenge], [[Santiago,_Chile|Santiago]], [[Chile]] {{SmallFlag|Chile}} {{SmallFlag|Santiago,_Chile|Escudo_de_Santiago_(Chile).svg}} 
```

**Comment by TheFive** [comment]
@fredao das muss jemand aus dem Weekly Team erstmal von Hand flicken. Da muss ich am Parser basteln. Die jetztige Variante stolpert über das Komma in dem [[]], was ich aber als richtig bezeichnen würde. (ist das erste mir bekannte Komma in einem Städteeintrag im Wiki). @rest sorry for the german.

**Comment by fredao** [comment]
ok, aber wen meinst Du mit jemand? ;-)

**Comment by TheFive** [comment]
It looks lite the parser is correct, butvthe wiki symbol | in the santiago reference is conusing the markdown table.

**Comment by TheFive** [comment]
Fixed, Santiago kommt jetzt richtig raus.

**Comment by fredao** [comment]
+1
