### ISSUE TITLE
keep language settings

### ISSUE THREAD

**Issue by Haikuch** [TheFive/osmbc#401]
currently, everytime I login, I have to choose again english as second language (blu button top right) next to my default language. I would like to keep this setting.

**Comment by TheFive** [comment]
upps. i store the data in the login session, that is allowed tonrun a year. Do you have to login each time ? Than it works as programned, but not as intended. 

i can put the information to the user object, i assume the firts language will be the same on mobile and desktop. i would like to keep the one language restriction in mobile.

**Comment by Haikuch** [comment]
yes I login every time, cause all my sessions and cookies are deleted after closing firefox :)
