### ISSUE TITLE
show open comments only when done by other persons

### ISSUE THREAD

**Issue by Haikuch** [TheFive/osmbc#415]
in overview, open comments are marked with a blue line. That ist even the case, when the last comment has been made by the user herself. But it should be nice to know, if there are new comments since I did the last one. Or since I opened the page last time.

To be honest, I know there are different colors sometimes, and this function might already be implemented somehow but I didn't recognize it..

**Comment by TheFive** [comment]
I am working on #411, where i try to get a "read" state for comments, and a user inbox.
My idea is, that there is a read line (like in slack) to mark comments as read. Of course, own comments has to be set as read while writing.
So i can distinguish between unread and read comments, and try to mark them in another way in the blog view.
There will be three states.
* open & unread
* open & read
* solved
of course with all "mentioning colours", Blue for yourself and orange for your team.

**Comment by TheFive** [comment]
I have added an envelope to indicate unread messages. Own messages are read by default.
