### ISSUE TITLE
Indicate and display comments in review mode

### ISSUE THREAD

**Issue by PedaB** [TheFive/osmbc#417]
Right now, you don't know, if an article contains (open) comments or not if you're in review mode. So it might happen that you change an article in a way, that's not reasonable and the comments might tell you why.

Thus, it would be great, if we could have an indication that an article contains comments. E.g. at the end of the text you could have a speech bubble if there are comments for this article. The bubble might contain a number, indicating how much comments there are. And it might additionally have a color scheme: grey bubble for '#solved', blue for open ones, yellow if it contains your language and red if it contains my name.

This wouldn't blow up the UI very much, but might help when in review mode. And the best would be, if one could even read the comments. Not directly in the current UI but as a tooltip-text as a mouse-over effect for the speech bubble.

**Comment by TheFive** [comment]
See also #411
