### ISSUE TITLE
browser collect button plugin

### ISSUE THREAD

**Issue by Haikuch** [TheFive/osmbc#419]
maybe someone would like to create a plugin that collects the current tab to osmbc :)

**Comment by TheFive** [comment]
I will help, if someone has interest.

**Comment by TheFive** [comment]
#18 Would this help, i have thougth, that i will "collect" any item, sent to the osmbcarticle channel in Slack. On iPhone it is simple to send a link to the slack app, i assume on android it is the same, but i have not taken a look, if this is possible on pc. 
This would gave the possibility to "collect" a link via different plattformes (supported by slack) in an easy way. Feedback about double collection will be send to slack too.

**Comment by TheFive** [comment]
@Haikuch Could #18 together with https://chrome.google.com/webstore/detail/clicky-for-slack/bllgmdlgbbmijcoecbnmgeoekhebgmac?hl=de help ? 
Then i would like to force #18, as it is not only for mobile devices.

**Comment by TheFive** [comment]
@Haikuch I have developed a Slack Webhook (for now only alpha), that receives URL via slack and is able to collect them. As there are browser plugins, that allow sending current urls to slack, this can be a solution for your wish (and spare me programming on several browser plattforms and mobile phones...)
Christoph

**Comment by TheFive** [comment]
@Haikuch I assume this is solved by #18.

**Comment by TheFive** [comment]
https://github.com/fwenzel/copy-url

Samle for copy to clipboard in firefox, may be osmbc integration is possible.

**Comment by TheFive** [comment]
OSMBC is supporting the following query syntax:
https://thefive.sabic.uberspace.de/article/searchandcreate?search=searchstring

So it should be no problem to integrate any existing plugin, that is allowing any search engine to be integrated. There are sevaral plugins that allows a search on a right click.
I did not found a plugin, that allows searching for the current url.
