### ISSUE TITLE
Create a list of all contributors of an issue

### ISSUE THREAD

**Issue by Nakaner** [TheFive/osmbc#42]
The Wochennotiz team always adds all contributors of one issue as authors in Wordpress. Only one author is shown in Wordpress at the moment but if you go the author's page at the blog, you will see all issues he has contributed to ([example](http://blog.openstreetmap.de/blog/author/michaelr/))

OSMBC should display (on request) a list of all users who contributed to the issue. This list can manually entered at Wordpress.

**Comment by alexandre-mbm** [comment]
A history for each edition would be interesting. Something so:

![Example of history](https://raw.githubusercontent.com/alexandre-mbm/weeklyosm-integrator/master/design/changing-version.png)

**Comment by TheFive** [comment]
The History of each edit exists. The Question ist just an aggregation work.

**Comment by TheFive** [comment]
Correlates to #39

**Comment by TheFive** [comment]
Closed 0n 0.5.0
