### ISSUE TITLE
Selenium Frontend Tests

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#43]

**Comment by alexandre-mbm** [comment]
[SeleniumHQ?](http://www.seleniumhq.org/)

**Comment by TheFive** [comment]
Not worked with it yet, but i think its SeleniumHQ. Do you have experience with it ?

**Comment by alexandre-mbm** [comment]
No.

**Comment by TheFive** [comment]
I have introduced zombie.js to test the frontend. So selenium is not needed.
