### ISSUE TITLE
add a link to the article, when sending an email from a comment

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#447]
** This is the email OSMBC sends from a comment**
Change in article of WN303
Article Brazilian Nelson A. de Oliveira asks the US community how they deal with Representing census-designated places (CDP), Census County Division (CCD), in oder to work out how they could map statistical boundaries in Brazil. was changed by Peda
comment was added
@derFred: Fairerweise sollte ich dazu sagen, dass ich nicht wusste was ich dazu schreiben soll. Also hatte ich es von 302 auf 303 geschoben damit wir fertig werden 
<End of email>

_Here the proposal:_
Change in article of WN303
Article Brazilian Nelson A. de Oliveira asks the US community how they deal with Representing 
[...]
Also hatte ich es von 302 auf 303 geschoben damit wir fertig werden 
**Answer here: https://thefive.sabic.uberspace.de/article/11852**

**Comment by TheFive** [comment]
I will have a look, it would not surprise me, if there is room for improvment.

But a link to the article should be in the mail (otherwise it is a bug), the title of the article should be clickable.

**Comment by fredao** [comment]
You are right. I searched only at the end, :-( as I do it in github messages. Antiquated traditions. ;-)

**Comment by TheFive** [comment]
i let this open as a marker to review the layout.

**Comment by fredao** [comment]
But not supporting greybeard's setteled habits, please ;-)

**Comment by TheFive** [comment]
At the end, it looks mostly OK. Question would be to put more information in the mail. but it should only be a trigger, that something changed, the information itself should be taken out of osmbc.

![image](https://cloud.githubusercontent.com/assets/6240370/15092150/dad8e7de-1461-11e6-8dfd-dc1c8309c90d.png)
