### ISSUE TITLE
avert warning when leaving unchanged editpage

### ISSUE THREAD

**Issue by Haikuch** [TheFive/osmbc#448]
when leaving the edit view of an article a warning appears because of possible changed data. Would be less annoying if it does not appear when nothing is changed :)

**Comment by TheFive** [comment]
correct, the article view is going to be complete redesigned. I plan to keep the old values (do to the comparison asked for) but on top allow to save "single" values, which will make the "versioning" obsolete. The alert be thrown away in that process.
