### ISSUE TITLE
add mark-as-read button in inbox view

### ISSUE THREAD

**Issue by Haikuch** [TheFive/osmbc#449]
currently it seems to be neccessary to open the article an click the envelope to mark comments as read

**Comment by TheFive** [comment]
My inbox contains mark as read envelopes :-)
![image](https://cloud.githubusercontent.com/assets/6240370/15096977/c1cdbc5e-150d-11e6-9c77-ac6f6cdabb3c.png)

**Comment by Haikuch** [comment]
ok :)
