### ISSUE TITLE
open OSMBC for Spanish, Portuguese, maybe Japanese 

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#45]
![image](https://cloud.githubusercontent.com/assets/1868849/10416099/0b64cc1a-7007-11e5-9086-52456186a162.png)

Hier kann man in etwa die Prioritäten ablesen ;-)

**Comment by alexandre-mbm** [comment]
:+1: for portuguese

**Comment by alexandre-mbm** [comment]
@TheFive, will it take long?

I am making fork of this repository now. What a brazilian could make for the code base beyond this issue?

**Comment by lbarrosop** [comment]
1 VOTE FOR SPANISH

**Comment by alexandre-mbm** [comment]
@lbarrosop, write `:+1:`. And lowercase please.

**Comment by fredao** [comment]
As we are between us thefive understand the idea, I suppose

**Comment by alexandre-mbm** [comment]
@fredao, about supporting more languages or about the vote?

**Comment by fredao** [comment]
@alexandre: The vote logico ;-)

**Comment by alexandre-mbm** [comment]
OK, @fredao and all. No problem.

**Comment by lbarrosop** [comment]
+1 for spanish

**Comment by fredao** [comment]
:)

**Comment by fredao** [comment]
@TheFive ein Bild sagt mehr als Worte: 

![image](https://cloud.githubusercontent.com/assets/1868849/10629426/f8efad5a-77ce-11e5-9b09-7bee154392bd.png)

Sorry - to talk in German, but it is quicker (an for me more differantiated) than my English
Ich gehe davon aus, dass F sich nicht mehr erholen wird, CZ weiss ich nicht genau, Indonesia sieht auch nicht gut aus PT hängt auch nur an einem ... wer wirklich klaglos und ohne zu treten Woche für Woche produziert ist Satoshi und das ES Team. Satoshi müsste ich noch fragen, ob er es tatsächlich nutzen möchte. Die ES sind schon wirklich scharf drauf ... Nun musst Du Dir überlegen, ob es wirklich die viele Arbeit wert ist. ;-)

**Comment by alexandre-mbm** [comment]
Done one time, problems will are finished with indeterminations (personal preferences) and failures in/from the WeeklyOSM's workflow.

**Comment by fredao** [comment]
what do you mean? please in portugues, I will translate for Christoph

**Comment by alexandre-mbm** [comment]
Editei o comentário, incluindo fala em português.

**Comment by fredao** [comment]
@TheFive Alesandre meint: wenn dieser issue gelöst ist, dann wird das sequentielle abarbeiten nicht mehr notwendig sein, denn dann können die einzelnen Sprachen sofort übersetzen, wenn eine ihnen genehme Ausgangssprache vorliegt. Dies macht auch die Übersetzung einzelner Meldungen für die Zielsprachen möglich, was einee asynchronene, arbeitsteilige Übersetzung in die Zielsprachen macht, die dann weniger personenabhängig ist als bisher. Mein Kommentar: volle Zustimmung :)

**Comment by TheFive** [comment]
Current Plan:
I start with #94 and change markdown to markdownDE.

After that i will make the software more flexible and working with markdown?LEFT? and markdown?RIGHT? where ?left? and ?right? can be configured.

With #94 i try to keep compatibility during development of the feature.

As a result, a language will be just a string in a config file, and can easily be extended.

Just open: Categories are now defined multilingual in a blog in JSON, that can be complicated, if we handle several languages.
@fredao: I will find a solution for that, do not offer a compromise yet :-)

**Comment by fredao** [comment]
@TheFive I apologize :( ... did you saw, I withdraw the idea ... and the main secptical just gave a positive response on it :) ... and I fight for an integration! --- because I really see a win/win/win situation :)

**Comment by fredao** [comment]
As a result, a language will be just a string in a config file, and can easily be extended.

sounds really great!

**Comment by TheFive** [comment]
Running in development environment.

**Comment by alexandre-mbm** [comment]
:100:
