### ISSUE TITLE
coulors for the people

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#455]
ist would be nice (if possible) to choose different colors for different people

![colors](https://cloud.githubusercontent.com/assets/1868849/15184585/111253c6-1796-11e6-8905-3b6b939d2dd2.png)

 with different coulors one could read it quicker

**Comment by TheFive** [comment]
For now i use the colors do define WHAT was done. Light Blue is collection and green is markdown.

**Comment by fredao** [comment]
I think your answer is a misunderstanding: the screenshot above is from "show collector" ;-)

**Comment by TheFive** [comment]
I know. 
if you enable "show collector" and "show editor" the colors are blue and green.

**Comment by TheFive** [comment]
![image](https://cloud.githubusercontent.com/assets/6240370/15228375/2754519c-188c-11e6-9253-d8c6d571a653.png)

**Comment by TheFive** [comment]
Only the user itself breaks this coloring rules....

Maybe it is a not necessary idea.

**Comment by TheFive** [comment]
May be we should talk about the goal you want to achive, and not about the way to go.

**Comment by fredao** [comment]
Maybe we should stay with my first screeshot.
![image](https://cloud.githubusercontent.com/assets/1868849/15228840/7422d546-188e-11e6-8659-d7868c3de013.png)

I would like to see very quick WHO collected which article. 
and the solution would be, that we don't have only light blue (for not from me collected articles, but different colors for differnt people.

But if it is to much work, we can drop it. ;-)

**Comment by TheFive** [comment]
As you know, i will let the work be done by you and will just do the fun part :-)

**Comment by fredao** [comment]
LOL :)

**Comment by TheFive** [comment]
Feature will go live in nexts hour.
What has to be done to use ?
Enable the option in the blog view AND define a color for every user in the user editor.
One can use any HTML Color name (see link in editor) or any mixed colorer (see although link in editor to find a color mixer).
