### ISSUE TITLE
Search for links with ' failed

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#458]
I have found the following JSON in the DB:

```
 {
 	"id": "12002",
 	"version": 4,
 	"blog": "WN304",

 	"collection": "https://lists.openstreetmap.org/pipermail/imports/2016-May/004431.html\r\nhttp://wiki.openstreetmap
 		.org / wiki / Data_working_group\ r\ nhttp: //www.abc.net.au/news/2016-02-24/cyclone-winston-entire-villages-wiped-out-on-fiji's-koro-island/7195842",

 		"categoryEN": "Imports",
 	"title": "Correction and improved data for Fiji",
 	"markdownDE": "Andy Townsend [veröffentlicht](https://lists.openstreetmap.org/pipermail/imports/2
 	016 - May / 004431. html) auf der Import Mailingliste die Kommunikation von Kate Learmonth(UNICEF Office of the Pacific Island Countries) mit der[DWG](http: //
 		wiki.openstreetmap.org / wiki / Data_working_group) zum Import nach dem[Wirbelsturm Winston](http: //www.abc.net.au/news/2016-02-24/cyclone-winston-entire-vill
 		ages - wiped - out - on - fiji 's-koro-island/7195842) auf den Fiji Inseln."}
```
which is invalid. Where does it come from and why was it saved ?

**Comment by TheFive** [comment]
Tritt auf, wenn markdownDE eingegeben wird nicht die Collection.

**Comment by fredao** [comment]
The reason was this link:
http://www.abc.net.au/news/2016-02-24/cyclone-winston-entire-villages-wiped-out-on-fiji's-koro-island/7195842

and I suppose the reason is here: fiji's ; the apostrophe is the lethal character ;-)

**Comment by TheFive** [comment]
That is a good hint, it is the full text search, that breaks and it is reclaiming the S behind the ' as problem.
As quickfix i will do not deliver any result for this link in doublette search, but that has still to be fixed (by escaping that character i think).

**Comment by fredao** [comment]
I have choosen an other link to the Fiji cyclone - btw OT: HOT and Ecuador a new earthquake reported :( 6.5 15 min ago
