### ISSUE TITLE
Show number of unedited & uncategorised articles in a blog

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#46]
https://trello.com/c/9UoBPbWu

Count numbers of unedited and uncategorised for a blog. Each user should have a "preferred" language, show the number for his language.

**Comment by alexandre-mbm** [comment]
Who is at this Trello?

**Comment by TheFive** [comment]
Some of the Editors that aro not on github, i take theiir suggestions from there and consolidate it here with a bidirektional link.

**Comment by alexandre-mbm** [comment]
Do I can to participate at Trello?

**Comment by TheFive** [comment]
Of course, but we are communicating in german there, if you are inteeested, send me your enail adress you want to use for trello. (ww.trello,com)

**Comment by alexandre-mbm** [comment]
No, sorry.

**Comment by TheFive** [comment]
Use Bootstrap badgescfor display.

**Comment by TheFive** [comment]
Fixed in 0.7.2
