### ISSUE TITLE
The following part in Collect - demolished the export 

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#460]
Tweet by **Karussell**
Diskussion zur Zweisprachigkeit in OpenStreetMap:
http://forum.openstreetmap.org/viewtopic.php?pid=592295
aka name="Deutsch / Sorbisch"
(Retweets: **0** Favs: **1**)

**Comment by fredao** [comment]
FALSCH, es muss schon der Titel gewesen sein!

“Diskussion zur Zweisprachigkeit in OpenStreetMap:
<..>
aka name="Deutsch / Sorbisch"”

**Comment by fredao** [comment]
Hatte eben in der Spanischen Version gleiches Problrm: 

Ausgabe war

![osmbc_broken](https://cloud.githubusercontent.com/assets/1868849/15396976/b4d905b0-1dde-11e6-9538-2017db056543.png)

**Comment by fredao** [comment]
![image](https://cloud.githubusercontent.com/assets/1868849/15397551/e2a847c4-1de0-11e6-9a2a-3d233ce9be09.png)

**Comment by TheFive** [comment]
Just one question. (as preview was OK). What was demolished, was it a problem in WP ?
If the preview worked fine, OSMBC has generated more or less correct HTML ? But may be WP can not interprete it correct.
I will take out any special characters, more: i am thinking on changing the internal id
from 
blog304#This_is_a_title_with_blanks
to
blog304#11134 where 11134 is just the OSMBC article id.

**Comment by TheFive** [comment]
Just for me to see whats wrong:

Please define demolished export.

**Comment by fredao** [comment]
OK - maybe ruined would be a better expression - 
I'm rebuilding what happened on a site in weeklyOSM :) - 
only to know: the results I got now are different from the results I saw yesterday ... please thee above as well.

1. article in OSMBC
LINK: https://thefive.sabic.uberspace.de/blog/WN305
![image](https://cloud.githubusercontent.com/assets/1868849/15423444/c2aa5834-1e7d-11e6-8f41-97ddd9386b2d.png)

2. Text in the article:
LINK: https://thefive.sabic.uberspace.de/article/12021
![image](https://cloud.githubusercontent.com/assets/1868849/15423481/f8d09446-1e7d-11e6-91ae-77baa2f9cbf4.png)

3. Text im Export 
LINK: https://thefive.sabic.uberspace.de/blog/WN305/preview?lang=DE
und danach halt exportiern 
![image](https://cloud.githubusercontent.com/assets/1868849/15423508/1a50f4b2-1e7e-11e6-9eae-2e765557d960.png)

4. Text in WordPress
LINK: http://www.weeklyosm.eu/wp-admin/post.php?post=5935&action=edit
![image](https://cloud.githubusercontent.com/assets/1868849/15423567/5fbd62d8-1e7e-11e6-8598-36af636daeb2.png)

5. Ergebnis in WordPress
LINK: http://www.weeklyosm.eu/picture-test?preview_id=5935&preview_nonce=0f1b57ebe2&preview=true

![image](https://cloud.githubusercontent.com/assets/1868849/15423596/84f37344-1e7e-11e6-9b1f-08282f150d85.png)


Wie schon gesagt: **diesmal** ist das Ergebnis anders, - es wird gar **nicht** dargestellt, in der anderen Version - **siehe oben** - war 
1. der Text bei der Meldung abgeschnitten
UND
2. die Formatierung des gesamten Blockes 
in dem der VERKÜRZTE Text (siehe wiederum oben - Dritte Meldung von mir "entrevista a Laura Barroso ....", 
der eigentlich hieß: "El Blog OpenCage Data entrevista a Laura Barroso (un miembro activo de weeklyOSM y la mujer a cargo de la edición española) acerca de OSM y Cuba."
- also die Inhaltes dieses Blockes waren alle um eine TAB Stelle nach rechts verschoben.

HTH

**Comment by fredao** [comment]
Abschließend: Ich halte die Generierung des Titels für SEHR hilfreich. Die Übeltäter sind wohl 

![image](https://cloud.githubusercontent.com/assets/1868849/15397551/e2a847c4-1de0-11e6-9a2a-3d233ce9be09.png)

hier in rot eingefärbt.  Nachdem ich diese entfernt hatte, war die Darstellung in Ordnung.

**Comment by fredao** [comment]
Das Problem liegt bei WordPress :(

![image](https://cloud.githubusercontent.com/assets/1868849/15431028/49a053dc-1ea8-11e6-8847-d10ade24259b.png)

NOT A BUG!
A WP PROBLEM.

**Comment by TheFive** [comment]
Please do  not close any issues :-) otherwise they will be marked as solved in my release history.

**Comment by TheFive** [comment]
See #462 for a solution.
