### ISSUE TITLE
Calendar cannot handle cities coat of arms

### ISSUE THREAD

**Issue by malenki** [TheFive/osmbc#461]
The calendar preview shows "error during convert" for wiki calendar template entries containing a cot of arms from the city and thus doesn't show the entry in the calendar:  
https://thefive.sabic.uberspace.de/calendar/preview
![2016-05-21_002518_scr](https://cloud.githubusercontent.com/assets/188565/15443689/8576bc38-1eea-11e6-9f5b-819a3d1381d8.png)

**Comment by TheFive** [comment]
I do not believe, that all these lines are errors so i assume your error message is regarding the first entry. (otherwise you have to be more exact in error reporting :-) )
The first entry is wrong, as it is missing an entry for the town.
it consists of a title, a country and some small flags.

**Comment by TheFive** [comment]
I have fixed the data for Freiberg (and the other) in the wiki, so now the preview is errorless.
