### ISSUE TITLE
automatic translation

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#469]
User @softgrow proposes:
When I drag and drop it uses google.com.de which has German rather than english interface. When translating to English for an English reader you should use google.com to get an English dialog

**Comment by TheFive** [comment]
thats really does not make sense. I will change.

**Comment by softgrow** [comment]
The logic should be that the destination language should be the users dialog so:

- Translating to German https://translate.google.de
- Translating to Japanese https://translate.google.co.jp
- Translating to English https://translate.google.com
and so on..

**Comment by TheFive** [comment]
For simplification reasons i work with translate.google.com :-)
