### ISSUE TITLE
please check the possiblity to save the Bild/Picture 

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#472]
entered or in DE or in EN into the other languages as well. 
At this stage, I always copy the images from DE / EN to ES, RU and JP.

As the copyied picture is only a proposal for other languages it sprares the time to copy it, 
and/but each language would be able to change the picture, if required. 

... and the translator has to adapt the *caption*

**Comment by fredao** [comment]
what I mean, you can see in the history here:
https://thefive.info/article/12108
or here: https://thefive.info/article/11997

**Comment by TheFive** [comment]
Will a simple "copy button" near the google translate button help ?
This could be used for Picture and Upcoming Events.
(But it will only copy from one to the next language)

**Comment by fredao** [comment]
yes! perfect!
