### ISSUE TITLE
in OSM-Terminausblick exits some unnecessary code

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#474]
```
<h2 id="wn307_osm_terminausblick">OSM Terminausblick</h2>
<ul>
<li id="wn307_12109">

[...]

</li></ul>
```

**Comment by TheFive** [comment]
?

**Comment by fredao** [comment]
See here:

http://www.weeklyosm.eu/7608-2

Wochenvorschau und OSM Terminausblick sind unterschiedlich formatiert.
Der Punkt und die Einrückung bei OSM Terminausblick wird durch obigen Code erzeugt.

**Comment by fredao** [comment]
Ich hatte ihn hier herausgefiltert
...
<h2 id="wn307_wochenvorschau">Wochenvorschau</h2>
<ul>
<p><table>
<thead>
<tr>
<th>Wo</th>
<th>Was</th>
<th>Wann</th>
<th>Land</th>
</tr>
</thead>
<tbody>
<tr>
<td>München</td>
<td><a href="https://wiki.openstreetmap.org/wiki/M%C3%BCnchen/Treffen">Stammtisch München</a></td>
<td>09.06.2016</td>
<td><img src="http://blog.openstreetmap.de/wp-uploads//2016/01/de.svg" alt="germany"></td>
</tr>
<tr>
<td>Berlin</td>
<td><a href="https://wiki.openstreetmap.org/wiki/Berlin/Stammtisch">96. Berlin-Brandenburg Stammtisch</a></td>
<td>09.06.2016</td>
<td><img src="http://blog.openstreetmap.de/wp-uploads//2016/01/de.svg" alt="germany"></td>
</tr>
<tr>
<td>Dresden</td>
<td><a href="https://wiki.openstreetmap.org/wiki/Stammtisch%20Dresden">Lange Nacht der Wissenschaften</a></td>
<td>10.06.2016</td>
<td><img src="http://blog.openstreetmap.de/wp-uploads//2016/01/de.svg" alt="germany"></td>
</tr>
<tr>
<td>Zurich</td>
<td><a href="https://wiki.openstreetmap.org/wiki/DE:Switzerland:Z%C3%BCrich/OSM-Treffen#72._OSM-Stammtisch.2FMicromapping-Party_Z.C3.BCrich_Sa._11._Juni_2016">Stammtisch/Micromapping-Party Zürich</a></td>
<td>11.06.2016</td>
<td><img src="http://blog.openstreetmap.de/wp-uploads//2016/02/ch.svg" alt="switzerland"></td>
</tr>
<tr>
<td>Passau</td>
<td><a href="https://wiki.openstreetmap.org/wiki/Passau/Mappertreffen">Mappertreffen Passau</a></td>
<td>13.06.2016</td>
<td><img src="http://blog.openstreetmap.de/wp-uploads//2016/01/de.svg" alt="germany"></td>
</tr>
<tr>
<td>Landshut</td>
<td><a href="https://wiki.openstreetmap.org/wiki/Landshut%20Stammtisch">Landshut Stammtisch</a></td>
<td>14.06.2016</td>
<td><img src="http://blog.openstreetmap.de/wp-uploads//2016/01/de.svg" alt="germany"></td>
</tr>
<tr>
<td>Karlsruhe</td>
<td><a href="https://wiki.openstreetmap.org/wiki/Karlsruhe#N%C3%A4chstes%20Treffen">Stammtisch</a></td>
<td>15.06.2016</td>
<td><img src="http://blog.openstreetmap.de/wp-uploads//2016/01/de.svg" alt="germany"></td>
</tr>
<tr>
<td>Berlin</td>
<td><a href="https://wiki.openstreetmap.org/wiki/Talk:Eisenbahn">DB Open Data Hackday</a></td>
<td>17.06.2016-18.06.2016</td>
<td><img src="http://blog.openstreetmap.de/wp-uploads//2016/01/de.svg" alt="germany"></td>
</tr>
<tr>
<td>Lüneburg</td>
<td><a href="https://wiki.openstreetmap.org/wiki/L%C3%BCneburg/Mappertreffen">Mappertreffen Lüneburg</a></td>
<td>21.06.2016</td>
<td><img src="http://blog.openstreetmap.de/wp-uploads//2016/01/de.svg" alt="germany"></td>
</tr>
<tr>
<td>Bonn</td>
<td><a href="https://wiki.openstreetmap.org/wiki/Bonn/Stammtisch">Bonner Stammtisch</a></td>
<td>21.06.2016</td>
<td><img src="http://blog.openstreetmap.de/wp-uploads//2016/01/de.svg" alt="germany"></td>
</tr>
</tbody>
</table>

</p>
<p>Hinweis:<br />Wer seinen Termin hier in der Liste sehen möchte, <a href="https://wiki.openstreetmap.org/wiki/Template:Calendar">trage</a> ihn in den  <a href="https://wiki.openstreetmap.org/wiki/Current_events">Kalender</a> ein. Nur Termine, die dort stehen, werden in die Wochennotiz übernommen. Bitte <a href="https://thefive.info/calendar/preview"> prüfe die Veranstaltung</a> in unserem öffentlichen Kalendertool und korrigiere bitte die Einträge im Kalender, <a href="https://wiki.openstreetmap.org/wiki/Template:Calendar">wenn notwendig.</a></p>
</ul>
<h2 id="wn307_osm_terminausblick">OSM Terminausblick</h2>
<ul>
<li id="wn307_12109">
<table>
<thead>
<tr>
<th>Wo</th>
<th>Was</th>
<th>Wann</th>
<th>Land</th>
</tr>
</thead>
<tbody>
<tr>
<td>Besenello Trentino</td>
<td><a href="http://www.portobeseno.it/">Portobeseno</a> : several talk about OpenStreetMap</td>
<td>10.06.2016-12.06.2016</td>
<td><img src="http://blog.openstreetmap.de/wp-uploads//2016/02/it.svg" alt="italy"></td>
</tr>
<tr>
<td>Berlin</td>
<td><a href="https://wiki.openstreetmap.org/wiki/Talk:Eisenbahn">DB Open Data Hackday</a></td>
<td>17.06.2016-18.06.2016</td>
<td><img src="http://blog.openstreetmap.de/wp-uploads//2016/01/de.svg" alt="germany"></td>
</tr>
<tr>
<td>http://osm.org/go/0CmcQnN Esino Lario</td>
<td><a href="https://wiki.openstreetmap.org/wiki/2016%20Mapping%20party%20Esino%20Lario%20"> &quot;Mapping party a Esino Lario in preparazione di Wikimania 2016&quot;</a></td>
<td>18.06.2016-19.06.2016</td>
<td><img src="http://blog.openstreetmap.de/wp-uploads//2016/02/it.svg" alt="italy"></td>
</tr>
<tr>
<td>Salzburg</td>
<td><a href="https://wiki.openstreetmap.org/wiki/FOSSGIS%202016/OSM-Sonntag">OSM-Sonntag</a></td>
<td>03.07.2016</td>
<td><img src="http://blog.openstreetmap.de/wp-uploads//2016/02/at.svg" alt="austria"></td>
</tr>
<tr>
<td>Salzburg</td>
<td><a href="https://wiki.openstreetmap.org/wiki/FOSSGIS%202016">FOSSGIS 2016</a></td>
<td>04.07.2016-06.07.2016</td>
<td><img src="http://blog.openstreetmap.de/wp-uploads//2016/02/at.svg" alt="austria"></td>
</tr>
<tr>
<td>Salzburg</td>
<td><a href="https://wiki.openstreetmap.org/wiki/AGIT%202016">AGIT 2016</a></td>
<td>06.07.2016-08.07.2016</td>
<td><img src="http://blog.openstreetmap.de/wp-uploads//2016/02/at.svg" alt="austria"></td>
</tr>
<tr>
<td>Seattle</td>
<td><a href="http://stateofthemap.us/">State of The Map US 2016</a></td>
<td>23.07.2016-25.07.2016</td>
<td><img src="http://blog.openstreetmap.de/wp-uploads//2016/01/us.svg" alt="united states"></td>
</tr>
<tr>
<td>Bonn</td>
<td><a href="//wiki.osgeo.org/wiki/FOSS4G_2016_Code_Sprint">FOSS4G 2016 Code Sprint</a></td>
<td>20.08.2016-22.08.2016</td>
<td><img src="http://blog.openstreetmap.de/wp-uploads//2016/01/de.svg" alt="germany"></td>
</tr>
<tr>
<td>Bonn</td>
<td><a href="http://2016.foss4g.org/">Workshops at FOSS4G 2016</a></td>
<td>22.08.2016-23.08.2016</td>
<td><img src="http://blog.openstreetmap.de/wp-uploads//2016/01/de.svg" alt="germany"></td>
</tr>
<tr>
<td>Bonn</td>
<td><a href="http://2016.foss4g.org/">FOSS4G 2016</a></td>
<td>24.08.2016-26.08.2016</td>
<td><img src="http://blog.openstreetmap.de/wp-uploads//2016/01/de.svg" alt="germany"></td>
</tr>
<tr>
<td>Bonn</td>
<td><a href="//wiki.osgeo.org/wiki/FOSS4G_2016_Code_Sprint">FOSS4G 2016 Code Sprint Part II</a></td>
<td>27.08.2016-28.08.2016</td>
<td><img src="http://blog.openstreetmap.de/wp-uploads//2016/01/de.svg" alt="germany"></td>
</tr>
<tr>
<td>Brüssel</td>
<td><a href="http://2016.stateofthemap.org/">State of the Map 2016</a></td>
<td>23.09.2016-26.09.2016</td>
<td><img src="http://blog.openstreetmap.de/wp-uploads//2016/05/be.svg" alt="belgium"></td>
</tr>
<tr>
<td>Metro Manila</td>
<td><a href="https://sotmasia2016.splashthat.com/">State of the Map Asia</a></td>
<td>01.10.2016-02.10.2016</td>
<td><img src="http://blog.openstreetmap.de/wp-uploads//2016/05/ph.svg" alt="philippines"></td>
</tr>
<tr>
<td>Berlin</td>
<td><a href="https://wiki.openstreetmap.org/wiki/Berlin%20Hack%20Weekend%20October%202016">Hack Weekend</a></td>
<td>15.10.2016-16.10.2016</td>
<td><img src="http://blog.openstreetmap.de/wp-uploads//2016/01/de.svg" alt="germany"></td>
</tr>
<tr>
<td>Karlsruhe</td>
<td>Hack Weekend</td>
<td>29.10.2016-30.10.2016</td>
<td><img src="http://blog.openstreetmap.de/wp-uploads//2016/01/de.svg" alt="germany"></td>
</tr>
</tbody>
</table>

</li></ul>
...

**Comment by fredao** [comment]
OH - wusste nicht, dass ich es hier darstellen kann ... dann ist der Exort nach weekly überflüssig :) - sorry

**Comment by TheFive** [comment]
Thanks, yes i have hardcoded the distraction of the bullet. Hardcoded will allways fail someone in future :-).
So i fave to put that config into the config data.

**Comment by TheFive** [comment]
mm may be a solution ...
```
- EN: "-- no category yet --"
  DE: "-- noch.....
                yet --"
  format:UL
```
So that the format can be UL, LI or OL, this concept is extendible and can help to get more and more OSM Blog Information out of the man code.

**Comment by fredao** [comment]
to be more perecise:
it is the **dot** and the **smaller table** AND only in "OSM Terminausblick" 
afaiks: all others are OK

**Comment by TheFive** [comment]
mm, the smaller table is a class definition, where other hard coded styling is put to the source and has to be distracted there....

**Comment by TheFive** [comment]
I will do a quickfix for the dot. But i assume, i can't do something on the table size, as this is calculated by the browser. 
IN 307 the main issue for the first big column is: 
![image](https://cloud.githubusercontent.com/assets/6240370/15984000/31022336-2fbb-11e6-8974-f7b44a69d3ec.png)

**Comment by fredao** [comment]
The table size will appear correctly, if the dot is eliminazed!

## Manfred Reiter - mobile -
## please excuse typos and brevity
## http://weeklyOSM.eu
Am 11.06.2016 9:59 vorm. schrieb "TheFive" <notifications@github.com>:
