### ISSUE TITLE
Google translate DE->EN

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#477]
ends with this message

![image](https://cloud.githubusercontent.com/assets/1868849/15984466/74f66974-2fcc-11e6-974d-8b6e77b95df7.png)

OS: Ubuntu - Browser: Chrome, FF the same

**Comment by TheFive** [comment]
You have an article number ?

**Comment by TheFive** [comment]
seems to be article independent.

**Comment by fredao** [comment]
yes - but I createc one for  tests  https://thefive.info/article/12192

BTW: will move this one into future - and we can use it, if needed. :)

**Comment by TheFive** [comment]
Problem found. The proxy, that is used to map the external request to the internal server at my hoster hat problems with the long URL name (or some characters in). I have changed from GET to POST and now it works. The Solution is already live.
