### ISSUE TITLE
Add a possibility to find easy commented articles in a blog.

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#48]

**Comment by alexandre-mbm** [comment]
Curiosity of who have not studied the code yet: what you are using to integrate OSMBC and Wordpress?

**Comment by fredao** [comment]
man power ;-)

**Comment by alexandre-mbm** [comment]
> find easy commented articles in a blog

I understood "search on Wordpress"; RSS, XMLRPC, database accesse, etc.

**Comment by TheFive** [comment]
As long as the last editorial step is done in WP in the HTML view, a derper integration between OSMBC and WP is very low priority.

**Comment by alexandre-mbm** [comment]
Except to import previous content, right?

**Comment by TheFive** [comment]
Yes a typical one time one shot unidirectional copy n paste interface.:-)

**Comment by alexandre-mbm** [comment]
How is the current issue?

**Comment by fredao** [comment]
@alexandre-mbm to be fair - as theFive is the only developer we should not discuss features with a minimum chance for realisation and we really don't need!!!

we need for other the languages (ES, PT, JA, Indonesian) the same options as we have for the English weeklyOSM ... the integration of OSMbc into WordPress is really irrelevant

**Comment by fredao** [comment]
@ import: have a look here: http://thefive.sabic.uberspace.de/blog/list?status=published

**Comment by alexandre** [comment]
Sure!

**Comment by alexandre-mbm** [comment]
@fredao, I am not "discussing". I would like of know the ideias...

**Comment by fredao** [comment]
OK :)

**Comment by TheFive** [comment]
Thank you for help,  this Issue is now 100% off topic, It does not help ither people, to understand OSMBC. It does not help me, to sort and priorisr the task to be done,  I will renane it and reoprn the origin one. Please try to kerp the topic of an issue and open a new one if necessary.

**Comment by alexandre-mbm** [comment]
@TheFive, I was not understanding what it is.
