### ISSUE TITLE
a blog in review should accept a collect

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#493]
it is not possible to add a new collect into a blog which is in review

![image](https://cloud.githubusercontent.com/assets/1868849/16378092/18db69aa-3c6a-11e6-8a55-19229335b8b0.png)

Please think about to change it.

Ich werde jetzt in WP nachtragen müssen, incl. der Überschrift etc .. - Blog nochmals öffnen möchte ich nicht - wegen der schon abgeschlossenen 3 Sprachen!

We would like to thank our readers for being patient and also apologise for the delay in publishing the English version.  We would like to thank our readers for being patient and also apologise for the delay in publishing the English version.

**Comment by TheFive** [comment]
.. you can add an article to a review, that is not the problem:
![image](https://cloud.githubusercontent.com/assets/6240370/16390825/e01dc582-3ca4-11e6-9cca-e13332b651b2.png)

But, if language DE is closed and you have the MAIN Lang (left lang) DE, than you can't add a collection, as YOUR blog is already done. That is OK to most users, but - as you are using many languages - a little bit confusing, for users in your situation.
I have no idea how to fix it, without reopening closed blogs to e.g. the german team, with the risk of a collect in an already published blog.

**Comment by TheFive** [comment]
Just posting a picture is not enough for a good error message. I have misinterpreted your query.
May be you meant that, the OK button was disabled.
May be.

Under the assumption that you have meant that the button was disabled, just the info (that counts for every collect) you have to enter a title from at last 6 charachters.

**Comment by fredao** [comment]
I think, it was the 6 character limitaion - I had a "info" - but maye it was to short - thanks for the hint! ;-)

**Comment by TheFive** [comment]
I will change the title to "please enter a title at last 6 characters" but i am pretty sure no one will read :-)

**Comment by fredao** [comment]
nobody, but me ;-)
