### ISSUE TITLE
?reviewComment= parameter is not supported any longer  Go Back to Start

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#494]
bug

**Comment by softgrow** [comment]
I am logged in at page https://thefive.info/blog/WN309 with EN on the left and DE on the right.

I and put text into the box marked "ReviewEN" and press the button and get sent to page https://thefive.info/blog/WN309?reviewComment=finished+review&lang=EN which has the text 

-----------
?reviewComment= parameter is not supported any longer

[Go Back to Start](https://thefive.info/osmbc.html)
-----------
I can workaround this bug by manually notifying others that my review is complete.

**Comment by TheFive** [comment]
Oh, i have just forgotten to implement the last peace of the restructuring.

The fix will contain an excuse for @fredao :-)
