### ISSUE TITLE
maybe a bug?

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#496]
https://thefive.info/article/12573

SrrReal edited the English version of the article above, but doesn't appear as an editor on the right side

![image](https://cloud.githubusercontent.com/assets/1868849/17358102/5bfc386e-5960-11e6-881b-17f5a8dc6e64.png)

here: https://thefive.info/article/12545 ... the same
... and still some more 

Hint: changing the language from DE-EN to EN-DE her edits appear

**Comment by TheFive** [comment]
This works as intended, OSMBC only shows the editor of the "Main" Language. If there is a use case in displaying the union of authors of two languages, we have do discuss how to put that in the GUI. I think for most users (e.g. all DE users) it is not of interest, that an author has written something in english.
