### ISSUE TITLE
Show on the Frontpage in "Last Changes" only title, markdown, markdownEN, Collection and comment - i.e. "category", "categroyEN" and "blog" are not nec 

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#50]
![image](https://cloud.githubusercontent.com/assets/1868849/10416150/13a435ac-700a-11e5-805a-249cd446d834.png)

**Comment by TheFive** [comment]
Related to #71

**Comment by TheFive** [comment]
I think most will be covered by implementing #71. The need of a history is always depending on your current use case. Sometimes you track the weekly editors, but sometimes you would like to understand, why an article is unpublished.

**Comment by alexandre-mbm** [comment]
A solution could be have filters... at top column.
