### ISSUE TITLE
disable user after x month of inactivity

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#506]
If an user is inactive for e.g. 3  month, the access rights should be set to disabled.

An user trying to log in with that status is shown, that he has to ask one of the team members to that the access rights back to full.
Make this configurable in the admin section (duration and wether it is switched on or of).

**Comment by fredao** [comment]
sounds difficult to me, because the CZ team enters only from time to time - but I could ask them

**Comment by TheFive** [comment]
I have seen iin slack that you do that mannually. So i can skip this.
