### ISSUE TITLE
Encoding Problems at Parsing Titles of Other Websites

### ISSUE THREAD

**Issue by Nakaner** [TheFive/osmbc#508]
It seems that OSMBC does not have a look at the encoding of third-party websites while reading their title (`<title>`). For example, if a website is encoded in iso-8859-1 (`<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />`), all umlauts are broken.

You can reproduce this behaviour [here](https://thefive.info/article/searchandcreate?search=https%3A%2F%2Fwww.gesetze-im-internet.de%2Fsatdsig%2FBJNR259000007.html&SearchNow=).

Yes, I know all these f***ing encodings!

**Comment by TheFive** [comment]
Successfully have included iconv in parsing title, using meta and response headers tags.
The converted string is not the original one, but is still not readable :-(
