### ISSUE TITLE
Hint: link at GitHub's header or README.md

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#51]
http://thefive.sabic.uberspace.de/osmbc.html

The `README.md` could explain the current use, the precautions to take.

**Comment by alexandre-mbm** [comment]
Like this:
![selecao_006](https://cloud.githubusercontent.com/assets/957501/10535919/502e5fb4-73bd-11e5-81ba-c670af266649.png)

**Comment by TheFive** [comment]
As the link is only usable by a smaller circle of people, i have put the link not in the upper part of the text. It looks like i am not the only one, looking at the github readme, i have put the software technical part more at the end of the text, tool

**Comment by alexandre-mbm** [comment]
Okay, the commit 16ac113da2ebfcf951d3615860c86ef9a72fbf43.
