### ISSUE TITLE
mailinglist search collector

### ISSUE THREAD

**Issue by Haikuch** [TheFive/osmbc#521]
Add a select menu with mailinglist names on the collection page. When a mailinglist is chosen, one can put a searchword from a mailinglist subject in the collection. OSMBC then searches on 

`https://lists.openstreetmap.org/pipermail/{{MAILINGLISTNAME}}/{{CURRENT_YEAR}}-{{CURRENT_MONTH}}/thread.html`

(like https://lists.openstreetmap.org/pipermail/tagging/2016-September/thread.html)

for the correct link (only within group of direct childrens of first UL list, not older than X days).

**Comment by TheFive** [comment]
I do not believe i am implementing that :-)

**Comment by TheFive** [comment]
Ich werd für die Usability von mailinglisten keinen Finger krumm machen. Tote technik.:-)

**Comment by Haikuch** [comment]
dann sammeln wir also keine news aus den mailinglisten mehr ein?

**Comment by fredao** [comment]
@Haikuch doch - aber nach alter Väter Sitte ;-) ... und habe es gerade eben gemacht ... 
1. Beitrag aufsuchen
2. URL markieren und CTRL+C
3. in OSMBC - Collect klicken und CTRL+V
4. in OSMBC - Search klicken 
fertig - ... und ehrlich - hat mich nicht überfordert ;-)

**Comment by Haikuch** [comment]
mh? reden wir vielleicht von verschiedenen sachen, 

1. ich bekomm ne mail die ich collecten will.
2. clicke den link in der mail signatur (immerhin den gibts..)
3. clicke auf talk archives
4. clicke auf thread
5. suche den richtigen thread
6. clicke drauf
7. kopiere den link aus der url leiste
8. rufe osmbc auf
9. gehe auf collect
10. strg+v ins feld
11. ok abschicken
12. puuh, collect einer einzelnen mail geschafft

1-7 sind bei mir das, was du lapidar 1. Beitrag aufsuchen nennst :)

**Comment by fredao** [comment]
OK - gebe zu, dass das vllt. ein wenig verkürzt war ;-) ; aber nimm es mir ab ... keine Absicht! ;-)
