### ISSUE TITLE
Possibility to send messages to different Slack-channels?

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#522]
![image](https://cloud.githubusercontent.com/assets/1868849/18543674/47fc4ab4-7b31-11e6-9291-14df6987882b.png)

- WN321(JP) review has been started
is important to wake up the proofreaders in a channel

- WN321(JP) is exported to WordPress
- WN321(JP) has been closed
these messages are not importend for the whole channel and they could be sent to a special channel for let's say for Kontrolleure um nicht Controller zu sagen ;-)

**Comment by TheFive** [comment]
i think it is just a configuration change in the slack options. disable notifications, you would not like to see in japanese, and create a new channel.

at the end of the configuration there is a table where you can see which message type is sent out.

**Comment by TheFive** [comment]
hopefully it is solved with: https://github.com/TheFive/osmbc/issues/502

**Comment by fredao** [comment]
+1  
Great - and as we have a DEVOSMBC I will test it :)
