### ISSUE TITLE
Collect for the Community

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#528]
I think it is worth to think about that feature. ;-) Often people @ SotM asked how to communicate news. I talked about that feature you have in mind and it was highly appreciated.

**Comment by TheFive** [comment]
yes, this makes sense. I just have to solve the architectonical issue of different access rights, i had masked out in the architecture for now.

**Comment by TheFive** [comment]
My question is, what should the collectors see ? They need feedback, question is which way.

Quick Version 

a) As they can "login" with OSM, i can show all article collected by a non full access user and display the status of the blog (Category, Blog Number And Blog Publish Status).

This disables all discussions about the article to the collector, and the collector can see the decisions result (Trash, Next Blog, Future, and wether it is published or not).

b) EMail Feedback

i would like to avoid it, as i like to check emails before sending infos out, Question would be, which Feedback to send (manual written like now, automated generated...)

c) Which Information to collect

c1) Title
c2) Link
c3) Optional Markdown
c4) Optional Comment

All information will be displayed to the full access user as usual, so the OSMNames will be shown in the history.

I prefer to implement a) and c).

**Comment by fredao** [comment]
Very nice analysis. +1

**Comment by TheFive** [comment]
See https://github.com/TheFive/osmbc/issues/612
