### ISSUE TITLE
Handling URLs with spaces

### ISSUE THREAD

**Issue by PedaB** [TheFive/osmbc#539]
Collecting URLs with spaces (real space, not %20) works so far, but it stays a space character when entered into the Collection-box. And when you want to edit the article, the link for the Collection does not work anymore, as the space separates links from each other. I.e. when collecting a link with spaces, the space character should be translated to %20.

**Comment by TheFive** [comment]
As discussed OSMBC is using the space as delimiter in the collection box, where links and text can be put in one field.
If links with spares ocures more often, there will be no delimiter to keep the concept of a textbox containing links, and OSMBC has to collect links at its own (e.g. like the change from one comment field to a multiple comment field).
