### ISSUE TITLE
Wrong Title exported

### ISSUE THREAD

**Issue by Nakaner** [TheFive/osmbc#54]
Currently each blog is called "Wochennotiz WN273", "Wochennotiz WN274" etc. This is being exported to Wordpress but it shouldn't. The correct title there would be "Wochennotiz Nr. 273".

**Comment by Nakaner** [comment]
Better: Drop the title at export, because title has to be entered manually at Wordpress at a different field.

**Comment by alexandre-mbm** [comment]
I suggest configuring title in configuration for each idiom
