### ISSUE TITLE
Warn before using create blog

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#542]

**Comment by TheFive** [comment]
Oh, it is already hidden in the admin part.

**Comment by fredao** [comment]
:-) schon shit wo manche Neulinge sofort rumstochern ;-)

**Comment by TheFive** [comment]
![image](https://cloud.githubusercontent.com/assets/6240370/19247402/769dd6c2-8f2b-11e6-9e00-6f24ad59edad.png)
