### ISSUE TITLE
GTranslate is cutting links of of the result.

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#547]
GTranslate terminates after the : before the //
another example: .. the [Accommodation map](http:

**Comment by TheFive** [comment]
text is translated correct by translat.google.com ?

Do you habe a full example ?   E.g. A osmbc link ?

**Comment by TheFive** [comment]
This worked earlier ? Correct ?

**Comment by fredao** [comment]
Yes that worked

## Manfred Reiter - mobile -
## please excuse typos and brevity
## http://weeklyOSM.eu

Am 15.10.2016 8:07 nachm. schrieb "TheFive" <notifications@github.com>:
