### ISSUE TITLE
Language switch

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#562]
doen't work 
nor on a desktop, neither on a phone

**Comment by fredao** [comment]
additional info - 
![image](https://cloud.githubusercontent.com/assets/1868849/19798344/c186a5d8-9cf0-11e6-939f-d38010f76700.png)

here the pull-down doesn't open neither 
As I have choosen DE and EN I cant export neither ES nor PT

**Comment by TheFive** [comment]
it was an issue with starting all necessary javascripts. On local machine it is working again, i just test and rollout the fix.
