### ISSUE TITLE
Show Language Flag not only in German Version

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#564]
sorry, aber ich schreibe jetzt in dt. 
... an mich wurde jetzt mehrfach die Frage herangetragen, ob man die languagesflags auch in den anderen Sprachen haben könnte ...

wenn aufwändig, dann lassen wir das ;-)

**Comment by TheFive** [comment]
kein Problem, muss nut die deutschbremse im Editor rausnehmen. Der Beschluss das Sprache != Landesflagge ist, ist hinfällig ?
Am Ende ist dan natürlich konfigurierbar :-)

**Comment by fredao** [comment]
Danke - ja die Hardliner haben aufgegeben (und sind auch schon z. T. weg) :)

**Comment by TheFive** [comment]
Ich schalte das einfach für alle ein, die Flaggen die nicht benötigt werden sind dann überflüssig.
Die Flaggennamen in der config müssten dann in english übersetzt werden. Zusätzlich blende ich per default die Flaggen aus, und lass sie über ein Flaggensymbol einblenden.
