### ISSUE TITLE
Disallow change of Category & Blog after one language is closed in an article.

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#567]

**Comment by fredao** [comment]
I am strongly against such a change.

**Comment by TheFive** [comment]
Thats the "publish" view, not the "Archive" view. The Problem is, that in a case a already published article is moved in the future, any reference we will make in future is wrong.

My intention is, to have the data in OSMBC as close as possible to the published data, (at the end make any WP unecessary).

See the current case, the article in WP is 100% different from the article in OSMBC.

If an article, that is already published, has to move to an other blog, it is NOT a move of the complete article, it is a move of a partial article. 
So it has to be copied. May be i create a funtion Copy and Collect to make this simpler.
But I hope this is seldom, so a manual copy can be done too.
