### ISSUE TITLE
one can not change Blog in TBC on a mobile phone

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#570]
![image](https://cloud.githubusercontent.com/assets/1868849/20208533/0eba9ca2-a7ef-11e6-9519-1bc1f758cbc9.png)

**Comment by TheFive** [comment]
Oh,  that looks like the full view and the reduced view is not enabled, which phone and landscape or portrait ?

**Comment by fredao** [comment]
Landscape
Motorola Moto G4

**Comment by TheFive** [comment]
The problem that occurs is, that the menu bar starts to use 2 lines in this dimension. It is to big for the phone, but the navbar-toggle breakpoint for bootstrap is 768px (fix).

Workaround: just turn around the phone from landscape to portrait, and the 768px rule toggles the menu and it works.

I just put that to a label bootstrap-4 for the case i switch to bootstrap-4, as i can change the toggling breakpoint there.

**Comment by TheFive** [comment]
Usage of TBC Feature has been decreased.

With this broader team it is not really helpfull, that articles are in a separate space, where not everyone can see it.
