### ISSUE TITLE
Indication of unwritten articles in full-mode

### ISSUE THREAD

**Issue by PedaB** [TheFive/osmbc#575]
when you're in full-mode and your primary language was written, but the secondary language is not, you don't properly get an indication for that. Would be great to e.g. have the yellow background for those articles, too. Or even only for the column of the language that was not written yet.

**Comment by fredao** [comment]
@PedaB ... maybe choosing the right options help ;-)

![image](https://cloud.githubusercontent.com/assets/1868849/20340701/2b78e158-abe3-11e6-887e-a67131083a68.png)
