### ISSUE TITLE
Vorbesetzung von Wochenvorschau 

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#583]
mit den Texten von hier: https://thefive.info/config/calendartranslation

Vorteile: 
wie *bisher* könnte der den Kalender Generierende, die Termine in alle Sprachen eintragen UND es bedürfte keiner Nacharbeit durch die einzelnen Sprachen

Nachteile: 
./.

**Comment by TheFive** [comment]
ä, ich dachte, die Texte würden benutzt, an welchen Stellen soll ich sie einbauen ?

**Comment by fredao** [comment]
ja, die Texte werden benutzt, wenn man den Kalender generiert. 

Da aber die Generierung (anders als ursprünglich gedacht) immer nur ein einziger Trottel übernimmt, diese dann in einer Sprache einpflegt und dann in alle anderen Sprachen überträgt, wäre es schön, wenn er nur die "Ereignisse" hierhin https://thefive.info/article/13566 kopieren müsste und die "Kopfzeilen" dort schon stünden. 

Jetzt ist es so, dass die Kopfzeilen entweder von dem jeweiligen Team angepasst werden :-) , - oder nicht. :( ... Siehe hier https://thefive.info/article/13521 ... bitte ES und IT einstellen. IT hat die Kopfzeile angepasst, ES (evtl. noch ;-) ) nicht. 

Ich hoffe, ich habe mich unklar genug ausgedrückt. Im Englischen wäre es noch deutlich unklarer geworden. ;-)

**Comment by TheFive** [comment]
Alles klar, ich implementiere erst die Lokalisierung der Städtenamen, dann ist der Issue überflüssig :-)

**Comment by TheFive** [comment]
BTW: Ich dachte der Event Kalender wäre für jedes Land individuell konfiguriert :-)
Ich lass mir was einfallen.

**Comment by fredao** [comment]
vergiß es, wenn es zu viel Arbeit macht - dann sollen die Übersetzer doch einfach auch noch die Kopfzeile hineinkopieren - und wenn sie es nicht machen, steht da meistens der ES Text :)

**Comment by TheFive** [comment]
Mir wird schon irgendwie was einfallen.

**Comment by TheFive** [comment]
Ich erlaube mir nur andere Prioritäten.

**Comment by TheFive** [comment]
related to #578 #466
