### ISSUE TITLE
List of editors to use in comments

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#591]
As we have a list of flags to drag and drop into the markdown area
for comments it would be nice to have a list of editors to drag and drop into the comments area 

![image](https://cloud.githubusercontent.com/assets/1868849/21180845/21b5d2ce-c1fb-11e6-8100-e91805397c15.png)

**Comment by TheFive** [comment]
I have thought about a lookup for this, i do not think that a list ov 50 Editors will make sense from display reasons.

**Comment by TheFive** [comment]
May be an autocomplete to solve thes issue ?

**Comment by fredao** [comment]
Auto-complete would be perfect, but I now know how to find the names quickly to address the addressee correctly.
