### ISSUE TITLE
Not Found Towns in geonames leads to convert errors in OSMBC Calendar tool

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#593]
![image](https://cloud.githubusercontent.com/assets/1868849/21229690/bf8bd808-c2e2-11e6-87d1-54e8289b70f9.png)

**Comment by fredao** [comment]
OK - liegt daran, dass der Erfasser den Unterstrich verwendet hat ... Plausibilitätskontrolle beim Kalender tut Not . aber im Wiki!

**Comment by TheFive** [comment]
Mm, may be osmbc should be more tolerant and do not throw an error.
