### ISSUE TITLE
table "overview with review status of all languages"

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#596]
![image](https://cloud.githubusercontent.com/assets/1868849/21452552/fdf1ba2e-c907-11e6-871e-ddaa0d787ac9.png)

The table could contain
or the names of the reviewer
or only a color
or only a number in the first column

**Comment by TheFive** [comment]
As most of your Wishs are titled with "nice to have" this is not very diversifying in the my list of 40 tasks.
