### ISSUE TITLE
Position of button Edit Block Area in new calendar tool

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#599]
could this button be moved to the top of the page - please?

**Comment by TheFive** [comment]
Idea was, if the "autogenerate" of the calender is working with no problems, to automate it in total.
Possibilities:
a) Generate calendar when setting an blog to "Edit"
b) Add a button to a calendar article and download the calendar "on demand".
c) Any other creative idea of our users

**Comment by TheFive** [comment]
P.S. what fredao meant is that, the button to store an event calendar in the WN has to be placed more prominent at the top of the page in the new calendar tool. (https://thefive.info/tool/calendarAllLang)

**Comment by TheFive** [comment]
I would like to move this feature to the Article Editor, or to the blog automation.

Variant a)
There is a button in each calendar article that allowes to generate the calendar.

What i need to know is, that the review possibility i have introduced is not used / needed.

Variant b)

Just when an article goes to edit mode, the calendar is generated.

Same restriction than a) applies and the question, what events should a delayed published issue e.g. in RU or FR show ?

**Comment by fredao** [comment]
I think a *general* review of the flags is necessary each week - before the calendars are written into the "calenadar article"
