### ISSUE TITLE
Which is strategy with the development branch?

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#60]
How collaborators can use it?

**Comment by TheFive** [comment]
I use Atlassian Source Tree ant its suggestion of labelling master, development, hotfixes and releases. All development is done in development, or in local branches taken from development.

**Comment by alexandre-mbm** [comment]
Can the local branches be done from `master`?

**Comment by TheFive** [comment]
You can find a description of the branching modell here.
http://nvie.com/posts/a-successful-git-branching-model/

I would like to keep the master as close as possible to production, so i have to merge your pull request to development, to do testing and integration begore I create a new release, so may be it is better to start a branch from development.

May be you try source tree. It has an ugly user interface, but you do not have to use git with command line.

**Comment by alexandre-mbm** [comment]
I use git at console and I am satisfied.
