### ISSUE TITLE
a box to send a message to editors - outside an article 

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#600]
![image](https://cloud.githubusercontent.com/assets/1868849/21674384/cec601a8-d32d-11e6-9abe-c6ec58afeb12.png)

zur Lage der Box ... sinnvollerweise zwischen Visitors today 
und
AdminView

Hintergrund: Ich sehe, dass drei Franzosen nach dem Schließen der DE in OSMBC drin waren und vermutlich nicht edieren konnten. Nun muss ich nach Slack wechseln um diese zu informieren. Eine Box um diesen eine Email zu senden wäre optimal.

Hinweis: diese Anfrage steht im Konkjunktiv23 ;-)

zwei Beispiele:
@chris @cbkiyanda @procrastigator - I saw you were online. You did not edit an article, maybe because OSMBC had a bug. You should know that OSMBC is online back again and waiting for your edits :wink:

und 
manfred [11:49]  
hi - I see you have still opened https://thefive.info/blog/WN337 in Review ... is that correct?

**Comment by TheFive** [comment]
First you would like to have a channel for each user, than a channel for each language, and at the end I have reimplemented Slack :-).
I think it does not make sense, as communication should be done by communication tools.
If there is a link, which i can open, and you are in the correct mattermost channel / slack channel based on the user name, this could be the help you are searching for.
https://osmde.slack.com/messages/@manfred/details/ should work for the german slack. I wail for this until we have one mattermost.
