### ISSUE TITLE
Making `collect` open to public

### ISSUE THREAD

**Issue by jinalfoflia** [TheFive/osmbc#612]
I have had discussions with @fredao of making the option to collect articles open to everyone. This will help us:

- Publish variety of articles from different parts of the world
- Will help us build interaction with the audience
- Will give us larger collection to filter from

**Cons:**

- Will increase the amount of work we need to do, as we have to review the collections before writing the articles

I'm not sure if this can be done, this is just an idea that came into my mind. We can maybe try this and see if it doesn't add on to our workload and helps in interacting with our audience and getting collections from folks around the world.

Would love to hear feedback and suggestions from others. 

cc: @TheFive

**Comment by TheFive** [comment]
see also #528 , #475

**Comment by TheFive** [comment]
Hi jinalfoflia,

It is on my plan, but i have to enter into a "new security paradigm", for now i have user, that can see all and user that can't see anything. With collect for everybody, there will be the status of being OSM User and have a subset of features in OSMBC.

Before i enter this "new complexity" i would like to improve my automated frontend testing, which needs an improvement to keep the more or less the stable releases.

I am just thinking about switching to selenium or find a solution, to get the current zombie.js test "more readable and flexible".

**Comment by jinalfoflia** [comment]
@TheFive this sounds great! Thank you for referring to all the other tickets that have captured the same idea.

> Before i enter this "new complexity" i would like to improve my automated frontend testing, which needs an improvement to keep the more or less the stable releases.

This makes complete sense 👍

**Comment by TheFive** [comment]
See related issue. Fixed.
