### ISSUE TITLE
Übernahmeknopf ist verschwunden

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#617]
https://thefive.info/tool/calendarAllLang

**Comment by TheFive** [comment]
mm, welches Übernahmeknopf fehlt denn ? Wenn die Events schon im Artikel stehen, gibt es den Übernahmeknopf nicht mehr (Der Knopf löst sich nach Benutzung quasi in Luft auf). Sieht daher erstmal korrekt aus. (in meiner Lokalen Variante taucht der Knopf auch noch auf).

**Comment by fredao** [comment]
hmmm - ich habe 343 offen, Sprache DE und EN, klicke Tools und öffne https://thefive.info/tool/calendarAllLang - da gibt es keinen Knopf (mehr), mit dem ich wie üblich die Upcomming Events in den Blog übernehmen könnte.

**Comment by TheFive** [comment]
Offen, musse auf edit setzte offen ist noch zu früh im prozess

**Comment by TheFive** [comment]
WN341 ist die Zeile für die 341. 
![image](https://cloud.githubusercontent.com/assets/6240370/22854662/0f941504-f074-11e6-8fcb-6a20605fc208.png)
(Aus der DEV)
Grün == Text ist erstellt
Hellgrau == Text wartet auf Erstellung
Dunkelgrau == No Translation
Schrift Weiss == Sprache noch nicht closed
Schrift Schwarz == Sprache Closed

Link "Upcoming Events" =>> führt zum Artikel mit den Upcoming Events in der jeweiligen Sprache

In diesem Beispiel ist ES hellgrau, d.h. noch nicht vorhanden, daher kann die Sprache kopiert werden.

In der Liste in Edit Block tauchen nur Blogs auf die im Edit Mode sind. Hintergrund: ich wollte  vermeiden, das der Kalender "zu früh" kopiert wird, und dann schon alt ist, wenn das Issue veröffentlicht wird.

**Comment by fredao** [comment]
Danke für die Aufklärung ....
die Schriftfarben S/W ist mir jetzt auch klar - danke!

**Comment by TheFive** [comment]
Kein Problem.
