### ISSUE TITLE
Change date format for the EN blog

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#620]
Email: matt@blissett.me.uk
URL:
Comment:
Please could you put the dates in either dd/mm/yyyy or yyyy/mm/dd order? That's much easier to read.

**Comment by fredao** [comment]
The British, Malta, Canada use dd/mm/yyyy as well
The only execption are the US.

I think we should do it 
Thanks in advance.

**Comment by TheFive** [comment]
Than i have to map the "locale" from EN to a EN Variant.

Which variant do you prefer ?

![image](https://cloud.githubusercontent.com/assets/6240370/23037690/a153aba0-f487-11e6-8a4a-eb5a983154d1.png)

This image is EN, if you click the buttons, i can switch to EN-GB, EN-IE, EN-NZ...

Thats all supported by moment.js. I will implement a "locale" mapping, supporting the switch from language code to preferred locale.

**Comment by TheFive** [comment]
And correct, the US guys are crazy with their date format.
