### ISSUE TITLE
using format dd/mm/yyyy for EN in Calendar as well

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#628]
![image](https://cloud.githubusercontent.com/assets/1868849/23528239/6566e536-ff99-11e6-9e6f-d03e8878a93d.png)

**Comment by fredao** [comment]
and here as well please:

![image](https://cloud.githubusercontent.com/assets/1868849/23559108/4060e898-0036-11e7-920b-dae6a086f32a.png)

**Comment by fredao** [comment]
![image](https://cloud.githubusercontent.com/assets/1868849/23746726/43c13eda-04bd-11e7-9fad-6b9d62ed31e7.png)

at least it doesn't work in the new calendar

**Comment by TheFive** [comment]
Seems to be complicate, it works on my local machine :-(

**Comment by TheFive** [comment]
It was a configuration error. It should have not worked on every place.
Please control for all places.

**Comment by TheFive** [comment]
I switched to EN and tested the following:
a) Old Calendar Tool 
b) New Calendar Tool
c) Blog Overview, Preview, Review and Download

all seems to be OK.
Please open up another issue, if you find a place, where i have forgotten to do the localize change.
