### ISSUE TITLE
twitterFAV2OSMBC

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#629]
doesn't work anymore

**Comment by TheFive** [comment]
ok any additional infos ? link to faved tweet ? 

for which period of time you tecognized this behaviour? thanks for support

**Comment by fredao** [comment]
https://twitter.com/calimapnerd/status/837767029239197697

**Comment by TheFive** [comment]
mm, just restarted the server but have no idea, what the problem was. Need a better logging mechanism.

**Comment by TheFive** [comment]
May be an external can implement something based on twitter and use an api to put data in, like it was done with mail2osmbc i think by hakush.
