### ISSUE TITLE
Link to fix Calendar problems

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#648]
![image](https://cloud.githubusercontent.com/assets/1868849/24404521/1edce72c-13c2-11e7-8cdb-1e53a6eb43ea.png)

If we could have these links
https://wiki.openstreetmap.org/wiki/Template:Calendar
https://thefive.info/calendar/preview
behind PARSING?

That would be helpful, if somebody likes to fix calendar issues. ;-)

**Comment by TheFive** [comment]
I assume, you are talking about the new calendar tool ?

**Comment by fredao** [comment]
Yes, of course, I never talk about old or former tools. ;-)

## Manfred Reiter - mobile -
## please excuse typos and brevity
## http://weeklyOSM.eu

Am 28.03.2017 12:38 nachm. schrieb "TheFive" <notifications@github.com>:
