### ISSUE TITLE
Simplify Adding Bookmarklets for Firefox Users

### ISSUE THREAD

**Issue by Haikuch** [TheFive/osmbc#649]
To get the collect bookmarklet in firefox you can put simply a link:

`<a href="javascript: var request=new XMLHttpRequest;request.open('GET','https://thefive.info/api/collect/HxKWInplHC?collection='+document.location,!0),request.onreadystatechange=function(){var a=4,b=200;request.readyState==a&&request.status==b&&(request.responseText&&'http'==request.responseText.substring(0,4)?window.confirm('Send to OSMBC\'s TBC, open Editor?')&&(window.location.href=request.responseText):alert.request.responseText),request.readyState==a&&request.status!=b&&alert('An Error occured '+request.responseText)},request.send(null);" rel="sidebar" title="OSMBC TBC">TBC Collect </a>`

With a click in the link the user can add the Bookmarklet, but he has to **uncheck** "_Load this bookmark in the sidebar_" This only seems to work in firefox. The API token must be replaced of course.

I would like also to offer the simpler collect page, if one wants to collect not to tbc but like regularly:

`<a href="javascript: window.location.href='https://thefive.info/article/searchandcreate?search='+document.location+'&SearchNow='" title="OSMBC Collect" rel="sidebar">Collect Page</a>`

This links could be placed on the user/views.jade page close to the API key. Unfortunately Iam not experienced with the jade language to make a pull request

**Comment by TheFive** [comment]
Thanks for the hint, will be done in one of the next releases.
