### ISSUE TITLE
New Calender Tool - storing maybe posssible without changing the language

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#651]
Situation:

1. Tool, New: Calander tool
This page appears for 1/4 second

![image](https://cloud.githubusercontent.com/assets/1868849/24720129/5edba284-1a3c-11e7-8815-07eced6b95f2.png)

2. Than it disappears and this page comes up 

![image](https://cloud.githubusercontent.com/assets/1868849/24720242/ae6ab27c-1a3c-11e7-94cd-85467626a629.png)

3. By changing the language one by one I can store the calendar-dates into OSMBC.

The first page would be helpful, because there are no so much people who store the calendar-dates ;-)

I hope I could explain what I mean.

**Comment by TheFive** [comment]
if no one reads the calenfar content, i will generate the calendar automated when setting blog to edit for all active languages :-)

**Comment by fredao** [comment]
The first screenshot (above) would be sufficient! So the one who does it could check whether all flags exist. Example #350 USA does not exists. ;-) I could not change it because of restricted internet connection. ;-)
