### ISSUE TITLE
Better CreateDB script for install purposes

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#66]
In the install guide is stated, that createdb can create a database for every environment. For security reasons (i have shut down a production database by mistake), there is a check, whether createdb is run in test environment.
There has to be a CLI for createdb, which supports 
* Creating Database in every environment
* Import some blog, if wanted
* Create an initial user.

**Comment by alexandre-mbm** [comment]
See the diff at [diff](57#issuecomment-148745652) exemplifies this

**Comment by TheFive** [comment]
As long as it is not documented finally, ask the developer for a psql_dump from the production server.
