### ISSUE TITLE
CR-LF bug

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#661]
![image](https://cloud.githubusercontent.com/assets/1868849/26246512/e4498d9e-3c99-11e7-8bd0-c839906086d1.png)

**Comment by fredao** [comment]
Es werden auch neuerdings wohl berechtigte Leerzeichen entfernt

![image](https://cloud.githubusercontent.com/assets/1868849/26246631/725e0646-3c9a-11e7-8252-0ef88155e717.png)

**Comment by TheFive** [comment]
Oh, i will remove pretty print function, that causes the error.

**Comment by TheFive** [comment]
This will remove the solution of https://github.com/TheFive/osmbc/issues/652

**Comment by TheFive** [comment]
May be better:
https://github.com/beautify-web/js-beautify
