### ISSUE TITLE
mocha tests seems to fail in other timeszones

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#67]
See comment: https://github.com/TheFive/osmbc/issues/57#issuecomment-148640029

**Comment by TheFive** [comment]
I have introduced in the before hook of the tests:
 process.env.TZ = 'Europe/Amsterdam';

In case i use:
 process.env.TZ = 'Brazil';

i get the same error than you, so the Europe/Amsterdam variant should fix it.

**Comment by alexandre-mbm** [comment]
Two comments analysing the problem are: [this](57#issuecomment-148706045) and [this](57#issuecomment-148715393). But I do not know the real way.

**Comment by TheFive** [comment]
Yep, i have used that comments 
a) to simulate your test environment with brazil
b) Fix the issue, by telling your mocha test, that they run in Amsterdam.

So your comments where very helpfull.
