### ISSUE TITLE
Field Blog already changed in DB Error message (unexpected)

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#675]
I intended to move an article from WN367 to WN366(Edit)
After pressing SAVE, this message appeared:

![image](https://user-images.githubusercontent.com/1868849/28561048-2b991bda-711d-11e7-911a-e59453eb9de5.png)

Notice: the article was mooved!

**Comment by TheFive** [comment]
Has to be checked, It happend with this article:
https://osmbc.openstreetmap.de/article/15576

The Blog was correct changed, the Error Message seems to be missleading.

**Comment by TheFive** [comment]
Put this on question, there are posts on witholdvalues page on exact the same article in exact the same milisecond. I put this meanwhile on question.

**Comment by fredao** [comment]
user's mouse was the problem :(
