### ISSUE TITLE
Version number differs

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#676]
Situation:
I collected a link in #367.
The collection appeared 2 times - no idea why!
I tried to move one of them into unpublished and the message below appeared:

![image](https://user-images.githubusercontent.com/1868849/28561297-2491d952-711e-11e7-9522-708349bf12a2.png)

Notice: the article was mooved!

**Comment by TheFive** [comment]
I assume a double click on Collect, that opens two tabs with the same article, saving the article is then only possible for the first tab, as the second tab, has "Old Version Stamp". 
This is no bug, it ensures, that you reload your old article before overwriting changes form another (user or tab).
