### ISSUE TITLE
Trash blog doesn't exist

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#677]
Situation: I tried to Trash the following article
https://osmbc.openstreetmap.de/article/15574

The possible blogs to move the article are

367
366(Edit)
Future
but not Trash

**Comment by TheFive** [comment]
We should declare it as feature :-)

**Comment by fredao** [comment]
I don't have any problem with such a feature ;-)

**Comment by TheFive** [comment]
OK, i did not declare it as feature, may be we should ask peda, what is more worse:

a) Checking a long TRASH for may be missdeleted articles (overeager editor...)
b) having Test articles (appears seldom) in unpublished.
