### ISSUE TITLE
Version number differs 

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#678]
Situation:
I wrote this article in DE (before it was absolutely empty) and while I saved it, this error message popped up ;-) 

![image](https://user-images.githubusercontent.com/1868849/28571576-c8cfd6ca-7143-11e7-9cf2-071756fca083.png)

**Comment by TheFive** [comment]
You have to understand, that this message does not have any information, that helps my allocating the problem.

a) What is THIS article ?
b) I assume you used the article Editor. Which one, i know the old editor is disabled, but does your editor have all the new features ? 
Reason: I wondering, why the new editor throws this message, i have implemented that in a way, that this version numbering of articles becomes obsolete ?
How did you collect the article (what is an empty article for you, you can't collect emtpy articles, an article needs an at last 5 chars in a title.)

**Comment by fredao** [comment]
sorry forgot to add the link to the article. :( You are absolutely right, the description above is nonsense! I would have added the link, but forgot it :( ... So I will close the issue and will reopen it, when the same message pops up again. Sorry for this nonsense issue!
