### ISSUE TITLE
Diese Wochennotiz wurde erstellt von ...

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#679]
Hierbei wir bei der DE Version der der WN-Name mit einem Link aus dem OSMBC-Profil übergeben. Dieser Link ist mittlerweile nicht mehr sinnvoll, da wir in WP Änderungen vorgenommen haben.

Man sollte überlegen, ob man überhaupt noch einen Link mitgibt, und wenn ja, dann für alle Sprachen einheitlich. ... evtl. auf das OSM Profil?

**Comment by TheFive** [comment]
Quickfix WN Username leerlassen, dann wird der link nicht generiert.
Ich kann aus WN Author ein Linkfeld machen, dann kann jeder Verlinken wohin er will . Die OSM Authorenlinks gehen aber noch, oder. Nur werden immer seltener eigene Artikel geschrieben.

**Comment by fredao** [comment]
Quick fix ist schon klar. OSM WN Autoren Links sind OK. Hintergrund in WP: Wir fügen schon seit einiger Zeit nicht mehr alle Mitwirkenden bei der Generierung des Blogs ein, da sie ja von OSMBC geliefert werden. ;-) ... Aus diesem Grund ist der mit dem Namen verbundene Link nicht mehr sinnvoll. 

WN Author als individualisierten Linkfeld wäre OK, muss aber nicht sein.
