### ISSUE TITLE
Use Correct Hyphen for Displaying the Date

### ISSUE THREAD

**Issue by Nakaner** [TheFive/osmbc#68]
In German 3.11.2015 - 9.11.2015 is typographically wrong. 3.11.2015–9.11.2015 would be right.

**Comment by TheFive** [comment]
Will be changed with the next update.
Me personally loves the variant with the spaces more, but that is not relevant :-)

**Comment by alexandre-mbm** [comment]
I think that the correct is: `3.11.2015 ‒ 9.11.2015`, with spaces. Where `‒` is  **u2012**.

**Comment by fredao** [comment]
About hyphen or blanc:
No discussion, Michael is right!

**Comment by fredao** [comment]
Nakaner is right!

**Comment by fredao** [comment]
ISO allows:
2005-08-09--2005-08-30: „Vom 9. zum 30. August 2005“

But typographically is Nakaner's version the correct one!

**Comment by alexandre-mbm** [comment]
Note that I did use of `--` but of `‒`.

What about i18n? If it will is there, each language has its conventions.
