### ISSUE TITLE
Add a list to show new registered (e.g. Last month) users

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#682]

**Comment by fredao** [comment]
+1 

and please think about to add
~~Visitors today~~
Visitors yesterday

**Comment by TheFive** [comment]
Visitors Yesterday or Visitors last week ?

**Comment by TheFive** [comment]
In order to support one feature per issue i have created a new question: https://github.com/TheFive/osmbc/issues/683

**Comment by fredao** [comment]
Yesterday would be great

**Comment by fredao** [comment]
Static yesterday

**Comment by TheFive** [comment]
Just have look for #683, i can only show yesterday users, that was NOT online today.
