### ISSUE TITLE
Show Visitors for another period

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#683]
https://github.com/TheFive/osmbc/issues/682#issuecomment-323571386

Here is a request about showing visitors for another period.

As i only track the "last" login and the change history, it is not easy to get out visitors yesterday.
I can show all visitors yesterday, that was NOT visible today (because a visitor today is overwriting the visit yesterday).
So it is easy to have a look in the active user list (which does not take long time on the new server) and sort it by the last login.

A visitors yesterday will need an additional table / feature logging (or as the CCC calls it spying or tracking) the OSMBC Usage (not the changes, they are - in deed - an indicator of OSMBC Usage (but only active usage).

**Comment by TheFive** [comment]
Is it really necessary to have this on the main page ? you can see yesterdays user in the user list by sorting for last access

**Comment by fredao** [comment]
OK I got it

**Comment by TheFive** [comment]
I close this issue. The only stamp (for now) that a has used OSMBC is the Last Visit, and of course every change he did. How often a user visits OSMBC without writing is not tracked yet, and i would not like to introduce it.
