### ISSUE TITLE
Visitors Today, make a link out of every name to jump to the user page.

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#685]
May be a user page, just to show information, and activity, but let not change it.

**Comment by fredao** [comment]
+1

and what do you think about link the names in 
"This weeklyOSM was produced by Anne Ghisla, Nakaner, Polyglot, Rogehm, Spanholz, Spec80, YoViajo, derFred, jcoupey, keithonearth."

to for example:

https://www.openstreetmap.org/user/jcoupey

**Comment by TheFive** [comment]
Waiting for rollout 
https://github.com/TheFive/osmbc/issues/679
