### ISSUE TITLE
Markdown Editor Name results in markdown used

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#687]
The grafical display (markown used) is written to WNAuthor Link in a block instead of the link.

See https://github.com/TheFive/osmbc/issues/679

**Comment by fredao** [comment]
1. In DE wird jetzt "markdown used" für alle ausgegeben. Siehe hier: https://osmbc.openstreetmap.de/blog/WN372/preview?lang=DE

2. Setze ich einen User auf "anonymous" werden zusätzlich einige "markdown used" abgeschnitten.

**Comment by TheFive** [comment]
i will try to rollout the fix tomorrow

**Comment by fredao** [comment]
no worries, we only need it next week again ;-) ... have a nice weekend
