### ISSUE TITLE
enrich the table with OSMBC-changes

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#695]
![image](https://user-images.githubusercontent.com/1868849/31220205-ef5416bc-a9bf-11e7-82d4-646357cfb37b.png)

would be helpful to see who of the newcomers needs support

**Comment by TheFive** [comment]
How should i determine it, planless clicking ? I can add a raise hand festure i need halp, where is that discussed, mattermost ?

**Comment by fredao** [comment]
we have these data here: https://osmbc.openstreetmap.de/usert/list?access=full&sort=OSMBC-changes

for example: 
![image](https://user-images.githubusercontent.com/1868849/31241678-f7ab8242-aa04-11e7-9b7e-9829d757ae02.png)

OK - I can go to  https://osmbc.openstreetmap.de/usert/list?access=full&sort=OSMBC-changes and see what is interesting to me ;-)

**Comment by TheFive** [comment]
Sounds reasonablr

**Comment by TheFive** [comment]
Decided not to implement it.
