### ISSUE TITLE
Upgrade Bower to Yarn

### ISSUE THREAD

**Issue by Spec80** [TheFive/osmbc#702]
bower is being discontinued and might fail at anytime. 

https://bower.io/blog/2017/how-to-migrate-away-from-bower/

**Comment by Spec80** [comment]
So Yarn isn't really only Bower substitute but also a npm one. It joins everything under one `package.json` and `bower_components` go to `node_modules/@bower_components`. Moving to it means to do away with npm it seems.

Running `bower_away` integrates `bower.json` into `package.json` peacefully.

`yarn install` seems much faster and apparently everything gets checksum and cached neatly; no more http checks.
For now `--ignore-engines` is needed. npm doesn't check for engine compatibility and so it seems that the `stoppable` package needs `node >= 7.6.0` because its `awaiting` dependency https://www.npmjs.com/package/awaiting .

**Comment by Spec80** [comment]
Haven't really tested this alternative but if we decide not to go the `yarn` route, maybe a native `npm install`+ a bundler like `webpack` might be the way to go.

**Comment by TheFive** [comment]
Bower is now repaced by npm. No change needed any longer.
