### ISSUE TITLE
Update install.md after Yarn update.

### ISSUE THREAD

**Issue by Spec80** [TheFive/osmbc#704]

**Comment by Spec80** [comment]
Add step to run Yarn.
Update the config.???.json step

**Comment by TheFive** [comment]
yarn is an alternative for npm and the recommended follow up for bower.
Comparison with npm: https://www.sitepoint.com/yarn-vs-npm/

Migration hints to go from bower to yarn
https://bower.io/blog/2017/how-to-migrate-away-from-bower/

As bower is still running for OSMBC i do not directly switch to yarn. (just a little wait & see).

**Comment by TheFive** [comment]
Yarn is not choosen. Basis NPM is still in use. No change planned.
