### ISSUE TITLE
Update createdb.js

### ISSUE THREAD

**Issue by Spec80** [TheFive/osmbc#706]
While installing OSMBC. createdb.js is throwing error TypeError: pg.connect is not a function pointing to a deprecation according to https://stackoverflow.com/questions/45725718/how-to-fix-pg-connect-is-not-a-function-on-node-js

**Comment by Strubbl** [comment]
I also face this issue while setting up a dev env. With issue #680 this issue was fixed for the app itself, but not for the createdb routine.

**Comment by Strubbl** [comment]
To easily reproduce this issue, one could use the docker environment @call-me-matt and i are trying to create: https://github.com/call-me-matt/osmbc-dev-env
