### ISSUE TITLE
Leser wünscht sich ein "Kettensymbol" [einen Link zu diesem Artikel ] 

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#710]
am Ende eines jeden Artikels, damit man diesen verlinken kann. ;-)

<Zitat>
Wenn das Kettensymbol am Absatzende stünde und grau ist, würde es nicht
stören.
</Zitat>

**Comment by osmtools** [comment]
Oder wie wäre es mit einem li:hover, welches das Quadrat durch ein Kettensymbol austauscht und beim "onclick" einfach das # Fragment hinten anhängt... Beispiel gefällig?

https://jsfiddle.net/8vc8a9o7/

Klar, dann muss man sich immer noch die URL (manuell) aus der Browseradresszeile holen - außer man bastel irgendein CopyToClipboard Javascript - , hätte aber sonst keine "großen" Designänderungen und hunderte Kettensymbole in der normalen Ansicht.

**Comment by TheFive** [comment]
An anchor per article should get at last the OK of 5 editors, as for me it will break the layout and readability.

The one click solution looks a little bit better, it has to be checked, that the existing links can be used normally. I knew frim OSMBC development, that this is not standard.

And third, the editors doing fixing after publish should give theit ok, as the html becomes more unreadable.

We should have in mind, that the normal usage of wochennotiz is reading, not generating links.

The question is, wether a browser plugin, which solves the issue, gits better to the need of all readers, then complicating things for a seldom case.

**Comment by Nakaner** [comment]
My initial idea was to add a anchor symbol (either a chain icon or a anchor icon) at the end of the paragraph which is `display: none` by default and becomes visible if the hover event of list item is triggered. CSS should look like this:

```css
li img.liAnchor {
    display: none;
}

li:hover img.liAnchor {
    display: initial;
}
```

HTML would look like this:

```html
<li id="wn381_16862">
  Joe Clever presents his improved tagging proposal
  <a href="https://wiki.openstreetmap.org/wiki/Proposed_features/Fire_Hydrant_Mapping_Version_5">
    Fire Hydrant Mapping version 5
  </a>
  on the Tagging mailing list.
  <a href="#wn381_16862">
    <img class="liAnchor" src="/img/liAnchor.png" width="12" height="12">
  </a>
</li>
```

**Comment by TheFive** [comment]
hi @Nakaner,

is it possible to put as an example in the last issue (one article would be enough). I am not confident with WP and not pretty sure where to put CSS.

thanks.

**Comment by TheFive** [comment]
can i use the same code for weekly AND wochennotiz or do i have to split generation.

may be i will make <li> and </li> configurable.

**Comment by fredao** [comment]
@TheFive at least for weeklyOSM I know where to place the CSS  - in blog.osm.de I have to have a look

**Comment by TheFive** [comment]
Vielleicht hilft, bis ich das mal implementiert habe, ein anchor plugin.

(ungetestetes Beispiel: https://chrome.google.com/webstore/detail/display-anchors/poahndpaaanbpbeafbkploiobpiiieko)

**Comment by TheFive** [comment]
I am still not happy with this idea. Now with a blog in 14 translations, the link has to refer to the correct language. I think this will not be implemented
