### ISSUE TITLE
A link with parentesis () is not parsed correctly to the drag&drop area

### ISSUE THREAD

**Issue by Spec80** [TheFive/osmbc#711]
Case in point:
https://wiki.openstreetmap.org/wiki/Proposed_features/Fire_Hydrant_Extensions_(part_2)

https://osmbc.openstreetmap.de/article/16428

**Comment by TheFive** [comment]
The problem comes than with using markdown in collections

```Some collection [link](https://www.openstreetmap.org/a_brilliant_map) in Markdown```

That is the reason for filtering out the parenthesis in this javascript. But may be there is no reason for doing so.
