### ISSUE TITLE
URL Blacklist of known OSM-Offenders

### ISSUE THREAD

**Issue by PedaB** [TheFive/osmbc#723]
It would be nice if osmbc would contain a blacklist of OSM-offenders. These would be sites that either violate OSM copyright/attribution or are otherwise e.g. clickbait sites or whatever (we had several of those in the past). The blacklist should contain a domain name, a comment and perhaps a date (last checked or something like that) and probably also a reporter.

Whenever someone collects a new article, they should be warned if the domain is in the blacklist. And the editor should also contain a warning (much like the double-link-warning).

**Comment by fredao** [comment]
Skip it
