### ISSUE TITLE
Guest's Inbox doesn't show incoming messages

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#729]

**Comment by TheFive** [comment]
You have more context, a screenshot, where the message is missing.
I just have testet that locally, in my context it looks thats working.

**Comment by fredao** [comment]
![grafik](https://user-images.githubusercontent.com/1868849/36072136-c0214502-0f1a-11e8-8aa7-1c1fa695551b.png)

**Comment by TheFive** [comment]
a, i've got it. Not the inbox is empty, but the badge in the menu is missing.

**Comment by fredao** [comment]
+1

**Comment by TheFive** [comment]
![image](https://user-images.githubusercontent.com/6240370/36073603-a73c5b30-0f33-11e8-8f9f-33e0db17a8dc.png)

**Comment by TheFive** [comment]
Can you send me the "article" link via mattermost ? That i can find our the reason ?
In my small test case it is working.

**Comment by TheFive** [comment]
Solved Mails are not shown in inbox, but on homepage it is clear, that an article was unpublished.
