### ISSUE TITLE
Hier erscheinen einige Gäste nicht (genau diejenigen, die sich nach Zverik angemeldet hatten), weil die Liste voll ist

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#730]
![grafik](https://user-images.githubusercontent.com/1868849/36072310-c57e5104-0f1d-11e8-8eaa-4368675f583f.png)

**Comment by TheFive** [comment]
This works for me as designed. All People that have a login AFTER Zverik have 0 edits or are in that list. OSMBC only welcomes people, that do a change, what is the same as "collect an article" for a guest user, as guest user are only allowed to edit own articles.

**Comment by TheFive** [comment]
@fredao passt das, oder soll ich alle lurker auch auf der Homepage zeigen.

**Comment by fredao** [comment]
passd scho ;-)
