### ISSUE TITLE
Check states Exported and Closed 

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#738]
I thought, i had put them together, but it looks like this is necessary to click twice to close a blog.
@fredao What do you think, would you like to have "two" steps first an export, second a close, or should i put Exporte & Close to one step ?

**Comment by fredao** [comment]
Imho it's great as it is at the moment.
An extra closing of a blog is helpful, becaus sometimes (at least me) check somthing in older (still not cloesed) blogs. So - for me - no changes needed.

**Comment by TheFive** [comment]
Reopend to combin export and closed per language for a blog
