### ISSUE TITLE
combine Did export and Close

### ISSUE THREAD

**Issue by PolyglotOpenstreetmap** [TheFive/osmbc#739]
Hi,

Would it be possible to combine the 2 buttons: Did export and Close into a single button:

Published using Wordpress

Thanks,

Jo

**Comment by TheFive** [comment]
Hi Jo, makes a lot of sense. It is an "artefact" from the first steps with OSMBC where the review was done in WordPress after the export.

**Comment by TheFive** [comment]
This issue will replace: https://github.com/TheFive/osmbc/issues/738
