### ISSUE TITLE
calendar issue

### ISSUE THREAD

**Issue by PolyglotOpenstreetmap** [TheFive/osmbc#754]
Hi,

Do you know why:

| {{Cal|mapevent}} || {{Dm|y=2018|Mar 19}} || <span class="p-name">[[Rennes#Autres ateliers|Cartopartie bâtiments en 3D]], [[Rennes]], [[France]]</span> {{SmallFlag|France}} {{SmallFlag|Rennes|Drapeau Rennes.svg}}

becomes:

Rennes | 19 Mar.2018-03-19–2018-03-20 |   |  
-- | -- | -- | --
Cartopartie bâtiments en 3D | 2018-03-19 |   |  

<tr>
<td>Rennes</td>
<td>19 Mar.2018-03-19–2018-03-20</td>
<td></td>
<td></td>
</tr>
<tr>
<td>Cartopartie bâtiments en 3D</td>
<td>2018-03-19</td>
<td><img src="http://blog.openstreetmap.de/wp-uploads//2016/02/fr.svg" alt="france" /></td>
<td></td>
</tr>
<tr>

I thought it was because of the long dash, but I don't see that on the OSM wiki calendar template.

Jo

**Comment by TheFive** [comment]
a) Everything looks to be fine in 
https://osmbc.openstreetmap.de/calendar/preview
b) in my internal preview for the next issue, it looks to be fine too.

So it looks fixed for me.
