### ISSUE TITLE
missing space before [

### ISSUE THREAD

**Issue by PolyglotOpenstreetmap** [TheFive/osmbc#757]
Hi,

When using automatic translation, I often find that spaces disappear before [.

Sometimes I catch them when proofreading, now I saw it happen while using the translations utility.

**Comment by PolyglotOpenstreetmap** [comment]
Oh, just noticed it also happens after ). Of course, this should only be corrected in case of [...](...). Not everywhere where there are parentheses.

**Comment by PolyglotOpenstreetmap** [comment]
And for the space after ), it's OK if there is no space when there is punctuation following.

**Comment by TheFive** [comment]
@PolyglotOpenstreetmap Is that an deepl or an bing or both issue. I do not touch the translated texts.

There are two options to reduce the problem

a) i skip ANY link before translation and they have to be edited by the editors afterwards. (apply something like a markdown to ascii function before. Sometimes i had the feeling, that the markdown links are not placed well in translation, so this can improve the translation quality.

b) Try to replace all [ without a " " before after translation.

@PolyglotOpenstreetmap, @fredao Do you have a suggestion, which way to go ?

**Comment by PolyglotOpenstreetmap** [comment]
The odd thing is that they have " " before the translation happens. It gets dropped somehow.

The main reason for me to use the translation aid is that the links are preserved, so not bringing them along would be somewhat counterproductive. They have to be moved sometimes, but usually they are alright.
Wouldn't it be possible to find all \b\[ and replace with \b \[ after the translation happened?

**Comment by TheFive** [comment]
Of course, thats possible. That is version b :-) I will implement that.

**Comment by PolyglotOpenstreetmap** [comment]
Thanks
