### ISSUE TITLE
Filter for Calendar

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#766]
looks broken

![grafik](https://user-images.githubusercontent.com/1868849/38613576-acfb8156-3d8a-11e8-9fab-3ff0f0becd58.png)

![grafik](https://user-images.githubusercontent.com/1868849/38613619-c8e05752-3d8a-11e8-96db-de72388ff16e.png)

**Comment by Spec80** [comment]
some extraneous dashes left behind from JADE to PUG migration...
