### ISSUE TITLE
Spelling errors

### ISSUE THREAD

**Issue by jc86035** [TheFive/osmbc#769]
There seem to be a lot of files where there are accumulated spelling errors, so it would probably be easier for someone with write access to fix these.

- "Open Street Map" should, of course, be "OpenStreetMap"
- "Whats New?" should probably be "What's new?" or "Changelog"
- "Change Log" should be "Changelog"
- "refere" should be "refer"
- "Collect" should probably be "Submit" – not a spelling error, but I think this is probably a mistranslation
- "Display _n_ of _T_ articles" should probably be "Displaying _n_ of _T_ results"
- "Inbox Direct Mention:" should be either "Inbox" or "Direct mentions"
- "in review modus" should be "in review mode" or "undergoing review"

**Comment by TheFive** [comment]
Hi,

thanks for your hints. Happy to see them, as you get blind of such details with the time.

For two remarks i have to think about, as this varies with user type.

The main editors are "collecting" articles in the web, editing them and after a review a blog is published. But you are right, for a guest user, "collecting", which means get search in outside and take in, is not the right wording, as guests are putting from outside so your submit makes sense in that case.

Same for Inbox Direct Mention, for editors i distinguish between direct and indirect mentions (mentions to a language team), but that does not exist for guest users.
