### ISSUE TITLE
Remove OK (Only for LANGUAGE) from Collect Window.

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#775]
habe es bei zweien heute gesehen ...
scheint aber ein allgemeines Problem zu sein. 

salut von der SotMFR in Bordeaux auf der Suche nach Mitarbeiter*innen ;-)

**Comment by fredao** [comment]
![Uploading grafik.png…]()
Die Ursache ist die Fehlinterprestation den gelben Knopfes.
ME sollt der gelbe Knopf weg.

**Comment by Spec80** [comment]
![2018-06-02-172408_3200x1080_scrot](https://user-images.githubusercontent.com/26686165/40878498-16b3a77c-668a-11e8-92d5-b2b71cc4960c.png)

If we're talking about removing this yellow button for guests, I'm +1

**Comment by TheFive** [comment]
Makes sense, sometimes an idea, that should reduce work will increase it on other side.
