### ISSUE TITLE
EMAIL for Guest on the first page

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#780]
Nobody reads the text. :( ... It is as always :( ... Do you think, it would be possible to write in RED and bold on the front page that they should write her email address ... :) ... Maybe it could be useful to link a part of my presentation in Milan, where I wrote, why the Email address is important.

**Comment by TheFive** [comment]
I assume, this behavior will not be changed by a color. (But i will give it a try).
At last it would be nice to write to the OpenStreetMap Mail, but i do not know how, or to disable all functionality, until the email is verified.
The question is, how many Collectors we will lose with the second option.
