### ISSUE TITLE
internal wiki: - Sorry, something went wrong and I cannot recover. If you think this might be a bug in Jingo, please file a detailed report about what you were doing here: https://github.com/claudioc/jingo/issues . Thank you!

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#791]
Es ist ja nur, dass wir darüber geredet haben. 
Keine Aufforderung was zu ändern ...

Ich wollte ergänzen 
DE: (wir [berichteten]..(http://blog.openstreetmap.de/blog/2018/09/wochennotiz-nr-426/#wn426_18446))

**Comment by TheFive** [comment]
Just skipped the session sharing between osmbc and osmww and it is working again.
There was a change in session data for osmbc (reduced amount of local stored session data) which i did not reflect in osmww (based on jingo, which is not my source) so i decoupled this.
