### ISSUE TITLE
Full tab does not show up on smartphones

### ISSUE THREAD

**Issue by severinmenard** [TheFive/osmbc#794]
On my Moto G5 Play with Android 7.0, when accessing OSMBC, the (really nice) Full tab does not show up in the UI, it requires to add manually /full to the URL

**Comment by TheFive** [comment]
It does not depend on your Moto G5 Play. 

I have developed the mobile variant based on an iPhone 5 (320 *566 pixel) and decided to disable the full view for this screensize.

In the blog view a third view in the list of
a) Filter Icon, b) Overview Tab, c) Review Tab will destroy the layout and put another line break in that view.

Do you have an idea, how i can solve this issue ?

**Comment by TheFive** [comment]
<img width="181" alt="image" src="https://user-images.githubusercontent.com/6240370/47265261-92e83d80-d525-11e8-9129-a6c429c592a2.png">

**Comment by severinmenard** [comment]
As 90% of my contribution are translation EN to FR, the full interface is really key. It actually exists when using a smartphone, a bit differently (what is not an issue at all) : the two articles are not displayed left/right as on a computer but top/bottom ; therefore there is just one column of text.
What is missing is just the access to this UI already adapted for smartphones screens by clicking on the Full tab.

**Comment by TheFive** [comment]
I have started the mobile version of OSMBC because i want to use the feature of the used library bootstrap. Fine to hear, that this helps in production and that some features are missing there, i will try to find a solution for it.

**Comment by TheFive** [comment]
I will remove the link to the "filter", they are still reachable on the page. This adds room to avoid a line break and display the full tab.
