### ISSUE TITLE
Twitter collection leads to "already changed in DB error"

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#798]
This error seems to occur, if tweet is expanded in article editor not in collection editor.

**Comment by TheFive** [comment]
Suggest to use https://github.com/ryanve/eol to compare strings with linebreaks

**Comment by TheFive** [comment]
Fixed, used internally different eol than than a browser does, which leads to comparison errors in seldom cases, where twitter expander was used.

**Comment by fredao** [comment]
Thanks
