### ISSUE TITLE
pt-pt <-> pt-br

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#801]
pt-pt and pt-br are two languages that are very closely related to each other. Nevertheless they differ partly in the grammar (incl. used tempi), but also in the choice of words. Please check if OSMBC could offer the following possibility:

Each article has a button that copies from pt-pt to pt-br. In case the pt-br group should grow (which is the goal), it would also make sense to reverse the copying from pt-br to pt-pt.  

Then two correct language versions pt-pt and pt-br could be published, which would benefit the needs of readers in different language areas.

I kindly ask you to check whether such an extension would be feasible for OSMBC and could be implemented at a reasonable cost of time.

**Comment by TheFive** [comment]
Have to check 3 things

a) Is it possible to configure OSMBC with 5 char language codes (e.g. pt-br).
b) Can i rename one existing language (also necessary for JP)
c) Copying is like translation with no translator, this is simple to implement :-)

**Comment by fredao** [comment]
> Have to check 3 things
> 
> a) Is it possible to configure OSMBC with 5 char language codes (e.g. pt-br).

it could be for as well pt and br ... so no necessity to use 5 characters

> b) Can i rename one existing language (also necessary for JP)

see a 

> c) Copying is like translation with no translator, this is simple to implement :-)
amazing :)

**Comment by fredao** [comment]
VIELEN DANK! - THANKS! MUITO OBRIGADO!!!!

**Comment by lucaslasota** [comment]
Wow, that's amazing!! Thank you very much! The blog will reach a huge public!

**Comment by TheFive** [comment]
Check a)
Some tests with PT-PT as language are working as expected.
Check b) 
Still open
Check c)
Already implemented by Drag n Drop
