### ISSUE TITLE
reopen deleted former comments 

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#804]
osmbc(TheSwavu)
WN454(EN) has been reviewed: OK. Had a second pass through (don't know what happened to the comments from my first go maybe I didn't save them). Fixed a few more typos. (User Review, Full Review)

**Comment by TheFive** [comment]
It is deleted, i think i have to change that.

What do you think about two options
A) reopen blog and delete revies (if there are substantial changes review is outdatef)
B) reopen blog continue review (keep review comments, review start and switch direct to review mode)

**Comment by fredao** [comment]
Imho B) Looks fine to me

**Comment by TheFive** [comment]
Will try to offer both variants. Error Type a) is someone is closing blog too early. Error type 2 is, someone is starting review to early. both need a reopen blog at the end

**Comment by TheFive** [comment]
I have checked in development.

If there is only a "startreview" this "startreview" is deleted. But as soon as there are review comments, they will be kept (together with the start time of the review.) The user has the chance to make the mistake to delete all reviews after reopening the blog.

As a result all combinations are possible. you can reopen a block you can delete reviews but this does not depend on each other.

I have improved source code and wrote an additional test case, to ensure, this behavior is kept in future changes.
