### ISSUE TITLE
Add anchors to articles sections

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#807]
For the sake of simplicity, I will simply quote an email that reached us. 

Can you please add anchors to each sections of your articles.
Exemple : https://weeklyosm.eu/archives/12067#Community
If I click on this link, I expect my browser to open the article "12067" and to focus (set offset) to point on the section named "Community.

And so on :

    https://weeklyosm.eu/archives/12067#Imports
    https://weeklyosm.eu/archives/12067#Events
    ...

In fact, i'm used to copy/paste link to your articles but I want to give a link to a specific section of your articles.

Please, make it works on all languages (I'm a french 🙂)
Thank you for your excellent web site. And your beloved RSS feed !

**Comment by TheFive** [comment]
See although:
https://github.com/TheFive/osmbc/issues/710

btw: as soon as the OSMBC weeklyExport is working (will need some month) the WP id is known by OSMBC, as the blog is generated by OSMBC and the ID is needed for updates (a new language is an update).

**Comment by TheFive** [comment]
https://weeklyosm.eu/archives/wn459_community

**Comment by Binnette** [comment]
Thanks @fredao to have track down my mail here 😎 
I do not know that the source code of https://weeklyosm.eu/ was available on GitHub. So I will create another issue here 👍

**Comment by fredao** [comment]
@Binnette - OpenData & OpenSource ;-)
