### ISSUE TITLE
Check send Mail to guests

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#808]
It looks like, that mail configurations as Editor still are send out, if you are guest.

**Comment by fredao** [comment]
Ich weiss nicht, ob ich das richtig verstehe. Nur zur Info: Ich schaue mir jeden Neuling an und enable bei jedem die Zusendung von E-Mail. Bis vor Kurzem hatte ich auch noch die offensichtliche Sprachzugehörigkeit enabled.

**Comment by TheFive** [comment]
The problem is, that if an Editor is configuring emails is changed to guest, than - it looks like - that the email rules of editor still applies. But guest should recieve a reduced set of emails.

**Comment by TheFive** [comment]
Code Review done, User Config Filter is respecting Guest Status
