### ISSUE TITLE
Mixed Content

### ISSUE THREAD

**Issue by kleper** [TheFive/osmbc#809]
The site is trying to load mixed content and in some browsers many icons do not load.

Mixed Content: The page at 'https://osmbc.openstreetmap.de/blog/WN478/Full' was loaded over HTTPS, but requested an insecure image 'http://blog.openstreetmap.de/wp-uploads//2016/01/de.svg'. This content should also be served over HTTPS.

**Comment by TheFive** [comment]
This is a content issue, the unsecure link is defined here

https://osmbc.openstreetmap.de/config/calendarflags


In former times weekly and blog was not secured.

**Comment by kleper** [comment]
It's not just some content, look how my screen looks like they don't load a lot of icons and it's due to mixed content in the application.
I enclose the browser log so you can see this complete error. I can't use the platform because of this problem and it happens in several browsers, I already test in Firefox and Chrome.

Thank you.

[osmbc.openstreetmap.de-1569123027258.log](https://github.com/TheFive/osmbc/files/3639314/osmbc.openstreetmap.de-1569123027258.log)


![screenshot-osmbc openstreetmap de-2019 09 21-22_28_06](https://user-images.githubusercontent.com/5655663/65381854-26d70200-dcbf-11e9-8907-a32b57f24786.png)

**Comment by fredao** [comment]
@kleper come to the desk this moring. I explain it to you. It has nothing to do with the OSMBC itself. And I explain How you can help to solve this "cosmetic" problem.
