### ISSUE TITLE
Clickable links in edit mode

### ISSUE THREAD

**Issue by PedaB** [TheFive/osmbc#81]
it would be great if the links in edit mode could be clickable as well. Not sure if that's possible for a normal text area, but it woul speed up the process of writing entries.

**Comment by fredao** [comment]
+1

**Comment by alexandre-mbm** [comment]
@fredao, if or when you prefer, the code `:+1: ` does :+1:

**Comment by TheFive** [comment]
Should i display all links in a collection behind the comment ?

Now i display there all links, if they are referenced in other articles. I can use that table, to display all links.

**Comment by fredao** [comment]
@alexandre, I am old fashioned

**Comment by alexandre-mbm** [comment]
@fredao, no... `+1` is more precise.

**Comment by fredao** [comment]
@alexandre-mbm, queria sempre falar mais preciso que possivel ;-)
