### ISSUE TITLE
Missing width/height for Language image-tags

### ISSUE THREAD

**Issue by tordans** [TheFive/osmbc#815]
My RSS Reader (https://reederapp.com/) does not handle the svg-image-tags without a width/height attribute well.

The rendered article looks like this 
![IMG_4210](https://user-images.githubusercontent.com/111561/69171389-22329c80-0afc-11ea-8196-b42b88d44b58.png)

The corresponding code in rss 

```
<li id="wn486_21264">Kreuzschnabel luckily <a href="https://forum.openstreetmap.org/viewtopic.php?id=67927">spotted</a> <img src="https://blog.openstreetmap.de/wp-uploads/2016/12/de.svg" alt="(de)" /> (automatic <a href="https://translate.google.com/translate?sl=auto&amp;tl=EN&amp;u=https://forum.openstreetmap.org/viewtopic.php?id=67927">translation</a>) a mass displacement…
```
Source: http://weeklyosm.eu/feed

I think a solution to this would be to change the image tag like
`<img src="https://blog.openstreetmap.de/wp-uploads/2016/12/de.svg" alt="(de)" width="20" />`
or maybe
`<img src="https://blog.openstreetmap.de/wp-uploads/2016/12/de.svg" alt="(de)" style="max-width: 25px" />`

However, I could not find any code that generates this image. Maybe its not part of OSMBC but part of wordpress?

**Comment by TheFive** [comment]
The Language flags are generated by an included markdown library.

The Editor places a ```![(pt)](https://blog.openstreetmap.de/wp-uploads/2016/12/pt.svg)``` into the Text field, and the library is generating the HTML. (so you could not find the generation in the OSMBC source itself).

I already include ```https://www.npmjs.com/package/markdown-it-imsize``` which can help, as it allows to add =20x20 as image size. 

So this can be a become a configuration issue, but before some interpretations for the language indicator item configuration has to be changed from html link to markdown interpretation.

Additional i can not oversee, wether this change in generated HTML Code will cause trouble on other sides.
