### ISSUE TITLE
guest account without email addresses

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#817]
some people use the guest account without email address. 
It is difficult to get in contact with them - in urgent cases only via osm.org and a message ...
... and I fear that these contributors don't get information, if somebody send a comments in an article

**Comment by TheFive** [comment]
Should i make email adress obligatory ?

After logging in with the OSM Account i can try only to allow the page user properties, as long as there is no validated email. This reduces the effort to come in contact with a guest, but it increases the effort to collect a news for a guest (while he feels already completely identified with his username). 

What i already have implemented is the following (you can go to your user page and switch temporary to guest at the buttom of your properties

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/6240370/80814402-1af3dc80-8bcc-11ea-9c39-2aef903ee33e.png">

**Comment by TheFive** [comment]
(The Switch to Guest feature for testing purposes is close to the full logout link)
