### ISSUE TITLE
Implement translation to all languages

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#820]
For now OSMBC is requesting texts from the API and Suggesting them for SAVE.

So a call of a translation API does not change the Aricle yet.

It is planned to have a translate button, that pushes all possible e.g. Deepl translations.

For this the article has to be saved with all translated languages.

the following corner cases can occur:

Source is empty -> Nothing to do
one or several destination languages are already filled in (e.g. with No Translation or with a manual translation) -> ignore this language from translation.

A second question comes up, is it necessary to distinguish automated translated text from reviewed automated translated text. (this is of course very helpfull with microsoft translator).

In the current implementation this is done implicit, as a human has to SAVE the translation, with the assumption from the system, that it will review the translation before.

If 10 languages are translated in one shot, it can (to be discussed) helpfull to mark a text as unreviewed.

This can be a "checkmark" every user can put on a text, with some GUI Support,
or a simple <automated translation> text before the translation, that has to be deleted by a human.

**Comment by fredao** [comment]
1. Maybe we should exclude BR, because it is copied from PT. And PT adds a lot of automatic translation links into the final PT-PT version. (I will talk to Lucas!) 
2. ... to be continued

**Comment by ThomasBarris** [comment]
I am opposing the idea translating all available languages when a translation is requested. I don't want to be responsible for text that I don't understand at all. If I don't understand a language I have no idea which word should carry the links. Maybe a text in a language can have a state such as "recommended translation", displayed in the text field in italic and light red background. Once one starts editing or pushs the save button it can turn to normal text

**Comment by fredao** [comment]
@ThomasBarris 

Imho only native speakers can decide if they want a direct "pre" translation in their text field. Only they can judge whether deepl.com translations save them typing and speed up the work process. We still want to achieve two proofreadings for every article. It is not planned to publish automatic translations.

**Comment by severinmenard** [comment]
I do not use Deepl for translating from EN to FR, but if OSMBC contributors do and would restrain their contributions if they cannot use the tool anymore, it seems logical to get a license if there is no free alternative (I do mean free and not gratis). Otherwise, I prefer to still have the choice to translate myself or with Deepl rather than the system proposing automatic translation by default.

**Comment by TheFive** [comment]
Hi,

i will try to make it as convenient as possible and keep the decision what to use at team level.

I think, deepl can help to make a regulary issue possible for languages, that does not fullfill @fredaos rule, that there has to be 3 people for driving a language on a 52 weeks per year basis.

On the other hand, there are teams, who are happy with their teamsize, and have the power to do a manual translation in total.

My personal opinion with deepl is, that automated translation of languages i know is very good, and we will learn to get benefit from it, (or stop payment of OSMF of a not used tool).

May be the idea of translating an article to all languages is too hard, so i will ad a switch in the admin section, which defines, that a language belongs to ALL and will be used for that.

Reading @thomasbarris and @severinmenard concerns, created the idea, that it is may be better to have a feature to translate ALL articles from one choosen language (mainly EN, eventually DE i think) to a specific one, so that the team, responsible for a language, can decide how to work and 
(may be) save some time by translating the completed EN issue and go direct to the review view, without clicking in every article.

**Comment by TheFive** [comment]
I will not implement rmthis isdue.

It is possible to translate a finalise the translation of one issue (all unwritt er n articles) from another language.

This keeps control of translator usage in the language teams
