### ISSUE TITLE
A separate page for simultaneous publication in several languages would be useful. 

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#822]
Recent situation:
The idea at the beginning was that each language publishes her version.
That works or would work for CZ, TR and JP ... (RU - doesn't publish in weeklyosm.eu)

Recent sitation
https://wiki.openstreetmap.org/wiki/File:Pub_1.png

EN | ES | PT | JP | FR | IT | BR
are ready to publish - yes ES without a review :-( 

To realise the export one has to open the issue - here #513, close each language and export each language. 

Within the recent release closing a language is only possible for two languages. (See screenshot below) 

https://wiki.openstreetmap.org/wiki/File:Pub_2.png 

To close one has to switch several times the languages. 

A separate page could solve that problem.

**Comment by TheFive** [comment]
Temporary implemented as part of the blog propoerty editor. But a separate page, with a more prominent link to come to makes sense.
Although the reviewer comments has to be added to that page

**Comment by fredao** [comment]
Perfect solution

**Comment by fredao** [comment]
Thank you
