### ISSUE TITLE
Hint: label for priority, at least for the lowest

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#83]
My suggestion: `for after`, yellow, to indicate an unforeseen future and a long term

**Comment by fredao** [comment]
@alexandre, que queres dizer? Nis no entendemos.

**Comment by fredao** [comment]
@alexandre-mbm, que queres dizer? Nos no entendemos.

**Comment by alexandre-mbm** [comment]
@fredao, você pode apagar seu comentário com o vocativo errado, se quiser.

Eu estou sugerindo um rótulo para marcar coisas (questões) menos importantes. Essa _issue_une-se à sugestão #80 e busca encontrar formas de transmitir aos colaboradores (observadores) quais são as prioridades do projeto mesmo entre o que são apenas melhorias desejáveis.

**Comment by fredao** [comment]
@alexandre-mbm, OK vou passar está informação para @thefive em alemão

**Comment by fredao** [comment]
@TheFive : @alexandre-mbm schlägt vor die issues zu priorisieren. Rangliste quasi, damit Mitarbeiter und "Kunden" die Stellenwerte der Issues sehen können.

**Comment by TheFive** [comment]
@alexandre-mbm I tried it with milestones.
For now i have 3 categories:

a) Get a version that has "rizzoma" features for the german team, just do the typical necessary changes, that has to be done after a rollout.
b) Implement more languages
c) Do all new issues occoured and not closed before during and after a) and b)

**Comment by fredao** [comment]
@alexandre-mbm ... <<você pode apagar seu comentário com o vocativo errado, se quiser.>>, mais e possivel num cellular?

**Comment by alexandre-mbm** [comment]
@fredao, you can try to execute the Desktop Version even from phone.

**Comment by alexandre-mbm** [comment]
@TheFive, same with the milestones I yet think at least one label for "low priority".
