### ISSUE TITLE
PrePublishing Page

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#830]
a special page to publish more than two language would be helpful.
It should contain:
1. Langauage Symbolds as on the front page 
DE | EN | ES | PT | TR | RU | JP | FR | IT | BR | ZH
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2. Number of reviews (as we have it on the front page)
3. Download button as we have it on the Preview Page
4. Close button as we have it on the "blog" page 

Reason:
Such a "pre-publishing" site would save someone from having to go through the whole process:

ad 3: the download button from the preview page on a "Pre.Publishing" page would save: open the preview page for **each language** (currently 12), there: "Start download" and close the page again

ad 4: the "Close button" on this "Pre-Publishing" page saves you having to switch languages in the blogs for each individual language and then trigger the Close button ... At the end of the process, return to the normal editor languages.

**Comment by TheFive** [comment]
I will pimp up the Edit Blog Page as Blog Management, and copy all requested features into it.

**Comment by TheFive** [comment]
Fixed in 3.4.4
