### ISSUE TITLE
syntax error at or near "imaginaire"

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#831]
https://osmbc.openstreetmap.de/usert/list?access=guest returns the syntax error above ...

for sure it will be again the ' in the users name. 

As this user doesn't belong to the team he/she/it could be removed ;-)

**Comment by TheFive** [comment]
The relevant query has to be changed to be more "flexible" with "'" signs.
meanwhile I have kept the user in the database, but removed him from guest. Ask me, if any trouble occurs with him.
