### ISSUE TITLE
https://osmbc.openstreetmap.de/config/automatictranslatetext 

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#836]
opening "(" and closing brackets ")" must be removed manually when using the automatic translation, as they cannot be removed in https://osmbc.openstreetmap.de/config/automatictranslatetext -

**Comment by TheFive** [comment]
Did a quick fix.
a) entered a sample to enter string with quotes in YAML for DE. Please do similar for other languages.
(i would like to give you as much  configuration option as possible.
b) updated the sample text, to show the link in more realistic markdown szenarios and avoid missinterpretation of the markdown ">" sign.

**Comment by fredao** [comment]
done - THANKS

**Comment by TheFive** [comment]
(git will have to close my fixed issues)
