### ISSUE TITLE
collecting deepl translation errors with automatic translation 

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#837]
please observe ... to be continued
... AND ... 
1. **de** is the placeholder for the de-icon 
2. imho no problem to switch the source language (here de) to the target language (here en) manually

RESULTS
1. Wer sich an der Aktion beteiligen möchte, kann nun im Wiki nachlesen (fr) > **de** was zu tun ist 
EN: Anyone wishing to participate can now read up on the wiki (fr)> what **de**to do and
ES: puede leer en la wiki (fr)> qué **de**hacer y qué herramientas
PT: agora ler no wiki (fr)> o que **de**fazer e

2. ausagekräftigen täglichen Auswertungen begleitet. > **de**
EN: meaningful daily evaluations. **>de**                                                  PERFECT :-)
ES: evaluaciones diarias significativas. **>de**                                          PERFECT :-)
PT: diárias significativas. **>de**                                                                 PERFECT :-)

3. The Strava Club erinnert (en) > **de** die Benutzer daran
EN: he Strava Club reminds (en)> **de**users that they ...                        Looks OK - a space between de and users would be fine 

4.

**Comment by TheFive** [comment]
Please let me close the issues. (i still find crazy what you have introduced, but i am still searching for an easy solution)

**Comment by TheFive** [comment]
This issue should be solved with the 3.8.2 version. Please report any issues best in a new ticket.
