### ISSUE TITLE
special statistics needed for "form-for-active-contributor-membership-other"?

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#838]
https://join.osmfoundation.org/active-contributor-membership/application-form-for-active-contributor-membership-other/

weeklyOSM has at least one editor known to me, who does NOT fulfil mapping requirements for membership according to the rule https://join.osmfoundation.org/active-contributor-membership/application-form-for-active-contributor-membership-mapping/.

He can prove his activity for weeklyOSM via his heatmap. Will the MWG require further proof? Which ones?
Should we have a discussion with the MWG?

**Comment by TheFive** [comment]
The MWG should decide :-).
If it does not trust the heatmap screenshot, you (or me) can verify that.
At last it should be possible to export all actions done by him, but i assume, this should not be necessary.
