### ISSUE TITLE
Heatmap separators other than white?

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#839]
white separators are ok 
![heat2](https://user-images.githubusercontent.com/1868849/91633235-e90e4d80-e9e6-11ea-8295-5801e753da8b.png)

here separators other than white would be nice - if possible - 
![heatmap](https://user-images.githubusercontent.com/1868849/91633195-a8aecf80-e9e6-11ea-81b5-d990b11e65ff.png)

**Comment by TheFive** [comment]
you are right, github is doing that in grey, not in white, that looks "better".
As it is integrated code i will have a look, wehter i can change it.

**Comment by fredao** [comment]
if it is easy and quickly done! OK! - otherwise we take it as it is. ;-)

**Comment by TheFive** [comment]
<img width="773" alt="image" src="https://user-images.githubusercontent.com/6240370/91634283-9d13d680-e9ef-11ea-85d2-dae37ceaeb4b.png">

Just an extension of existing SQL returning 0 values.

Will go in prod next 1-2 days, when I do some updating on the server

**Comment by fredao** [comment]
Great, thanks

## Manfred Reiter - mobile -
## please excuse typos and brevity
## http://weeklyOSM.eu

TheFive <notifications@github.com> schrieb am Sa., 29. Aug. 2020, 12:04:
