### ISSUE TITLE
"no transalation to rest"

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#847]
Frage sollte sein, ob das NT auch bei Gast eingebaut werden könnte, dann könnte nämlich ... der Eintragende entscheiden, ob es bsp nur in der DE Version erscheinen soll. 

Bei näherem Hinsehen, kann das aber auch die Truppe entscheiden. ;-)

**Comment by TheFive** [comment]
Was ist die Frage, funzt das net, oder muss ich da noch was programmieren ?

**Comment by fredao** [comment]
not necessary
