### ISSUE TITLE
hide all --unpublished-- in all lists

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#85]
kein weiterer Text :)

Priority: LOW

**Comment by TheFive** [comment]
I thought unpublished for Articles in a blog, that are may be of interest but will not be published.
For that a visibility is good.
If the article is really "TRASH" you can move it there, may be i will implement a regular empty trash later on.

**Comment by fredao** [comment]
Better - sorry, I didn't know the trash! thanks!
