### ISSUE TITLE
OSMCAL Integration

### ISSUE THREAD

**Issue by thomersch** [TheFive/osmbc#852]
Hi TheFive et al!

You might have seen that I'm working on [OSMCAL](https://osmcal.org), which shall <del>totally revolutionize</del> help with calendaring stuff in OSM. I have [built an extension for the wiki](https://github.com/thomersch/OSMCALWikiWidget) that shall replace the current mechanism. That way no-one will have to parse wiki syntax anymore.

OSMCAL has a [stable API](https://app.swaggerhub.com/apis-docs/osmcal/osmcal-api/2.1) (with localization support!) and [configurable JavaScript widgets](https://jbelien.github.io/openstreetmap-calendar-widget/).

I would be willing to help integrate OSMCAL into osmbc, just let me know what you envision and how we could make this as easy as possible for the weekly team.

**Comment by TheFive** [comment]
Hi Thomas,

You are in the list of people i have to contact, just because the calendar.
OSMCAL was the project i have planned for the time OSMBC is complete :-)


Suncobalt is doing the conversion after some substantial changes in the Wiki structure for the calendar, i did not like to follow.

Since theb OSMBC is requesting a JSON from his server, that contains all information.

OSMBC enrich this with Geo Names Translation and  filter events, that should not be shown in weeklyOSM automatic. (Do you do that already?)

Do you have an API example, OSMBC is just iterating over a json, may be i can easily switch that to your API.

Christoph

**Comment by TheFive** [comment]
https://osmcal.org/documentation/

**Comment by TheFive** [comment]
i see, the returned json is similar to suncobalt's.
```
 "copyright":"The data is taken from http://wiki.openstreetmap.org/wiki/Template:Calendar and follows its license rules.",
   "events":[
      {
         "Big":"",
         "EventType":"Meeting",
         "country":"Taiwan",
         "description":"OSM x Wikidata #21",
         "end":"2020-10-05",
         "start":"2020-10-05",
         "state":"",
         "town":"Taipei"
      },
```
what i miss in your JSON is the country. (may be only in the documentation).
weeklyOSM is using it to display the the country flags
<img width="804" alt="image" src="https://user-images.githubusercontent.com/6240370/95502112-9d699f00-09a9-11eb-9b46-da47d2333307.png">

**Comment by thomersch** [comment]
> You are in the list of people i have to contact, just because the calendar.

Perfect :)

> OSMBC enrich this with Geo Names Translation and filter events, that should not be shown in weeklyOSM automatic. (Do you do that already?)

The data already contains the coordinates and a short geocoding representation - which personally I find more handy than just a country flag, because I won't be travelling across Germany for a Stammtisch and on the other hand some Swiss people might be more interested in an event in Freiburg than across the country.

Example:

```json
"location": {
	"short": "Manila, Philippines",
	"detailed": "\"Online\", Maria Orosa Street, Ermita, Manila, Philippines",
	"coords": [
		120.979947,
		14.583352
	],
	"venue": "\"Online\""
}
```

By the way, you can [try the live API in Swagger](https://app.swaggerhub.com/apis-docs/osmcal/osmcal-api/2.1#/Events/get_v2_events_), just hit "Try it out" on an endpoint.

The API does also support localized dates by setting the `Accept-Language` header: If you set it to e.g. "de", it will return localized human dates as such:

```json
"date": {
	"human": "12. Oktober 19:00 – 20:00",
	"human_short": "12. Oktober",
	"whole_day": false,
	"start": "2020-10-12T19:00:00-04:00",
	"end": "2020-10-12T20:00:00-04:00"
}
```

**Comment by fredao** [comment]
> 
> The data already contains the coordinates and a short geocoding representation - which personally I find more handy than just a country flag, because I won't be travelling across Germany for a Stammtisch and on the other hand some Swiss people might be more interested in an event in Freiburg than across the country.

the coordinates are very welcome, but the flags allow everybody a quick check, whether it is in the Philipines or in Luxembourg. ;-)

**Comment by thomersch** [comment]
> the coordinates are very welcome, but the flags allow everybody a quick check

Doesn't every OpenStreetMapper know their location in lat/lng and can calculate great circle distance in their mind!? ;)
By the way I had to think for a quite a moment to remember the flag of Luxembourg.

Anyway, you're obviously free to do with the data whatever you want, independent of what I think of country flags. I just didn't want to put the whole geocoding result in every event response, since it's a quite a blob and I don't want to be that dependent on a certain third-party data structure.

**Comment by fredao** [comment]
>  I just didn't want to put the whole geocoding result in every event response, since it's a quite a blob and I don't want to be that dependent on a certain third-party data structure.

1. Could you please explain this sentence a little bit? 
2. I am pretty sure that OSMCAL supplies the associated countries, or are they not recorded?

**Comment by pyrog** [comment]
> I just didn't want to put the whole geocoding result in every event response

Simply put the **country** ISO 3166-1-alpha-2 **code** 😃 
So it's easy to localise it in the user language and show the flag (there is a tons of [country flags](https://github.com/topics/country-flags) repositories in GitHub).

**Comment by thomersch** [comment]
> Could you please explain this sentence a little bit?

OSMCAL does not ask the event organizer to specify the country, it is inferred from the location on map. Reverse geocoding is performed by Nominatim and I save away the whole result from it and format it appropriately for the lists and API, e.g.:

<img width="411" alt="Screenshot 2020-10-09 at 15 27 19" src="https://user-images.githubusercontent.com/948605/95588706-07cf1d80-0a44-11eb-83e8-707d4e9fbb54.png">

The response payload of Nominatim is quite elaborate and I do not want to put all of it for the whole list of events the API is providing, this would be waste for most API consumers.

> Simply put the country ISO 3166-1-alpha-2 code

Next person coming along asking for the state, then city, then street, then house number, ... I don't want to supply everything for every conceivable use case. It is not impossible to get the country code from lat/lng, if you must.

**Comment by pyrog** [comment]
>I don't want to supply everything for every conceivable use case. It is not impossible to get the country code from lat/lng, if you must.

Ok, but you suggest to use it in OSM BC for weekly OSM. This wonderfull project need country 😉

**Comment by fredao** [comment]
> Next person coming along asking for the state, then city, then street, then house number, ... I don't want to supply everything for every conceivable use case. It is not impossible to get the country code from lat/lng, if you must.

OK - do I understand correctly: The developer asks the customer to change his requirements?

**Comment by thomersch** [comment]
> The developer asks the customer to change his requirements?

Yes, this is called consulting and I'm getting paid a lot for it, usually ;)

But seriously, I am currently arguing that this might be out scope and you can do it yourself.

**Comment by fredao** [comment]
But please tell me seriously: Is it really a problem for those who enter the data to ask for the country? Is this a KO criterion?

**Comment by thomersch** [comment]
fredao, I think this is going off rails.

Christoph, if you have questions or specific requests about the API, please let me know, I'll be happy to discuss and help.

**Comment by TheFive** [comment]
Hi thomersch,

a) OSMBC has a working method to read the wiki calendar, wich is by history the more or less official calendar.
b) OSMCAL offers data, but it looks incomplete if compare the osmcal site with the wiki calendar.
c) i have to integrate an additional API to get the new API with less data running.

Ok What is the benefit for me and weekly OSM to do so :-)

I understand, that you are interested in avoiding redundant data.
```
"date": {
	"human": "12. Oktober 19:00 – 20:00",
	"human_short": "12. Oktober",
	"whole_day": false,
	"start": "2020-10-12T19:00:00-04:00",
	"end": "2020-10-12T20:00:00-04:00"
}
```
Then it would make sense to skip the field "human" "human_short" (in java script done by moment.js) and whole day (just a if with start and end :-)

If this additional API is creating more work for me, it will influence my priorities.

Beside the discussion about this field (i understand your side, you may be mine)

What is the migration plan ?

The calendar generation is semi automated in OSMBC, its a matter of some clicks. 
If i integrate the new API, the editors will have the options to use osmcal OR the suncobalt wiki calendar.

So editors will decide by content. May be a radical switch of weeklyOSM support the migration process from wiki to osmcal a little bit. (this is the so called force of developers in openstreetmap, we should not misuse).

What is the plan to have the calendar still in our main OpenStreetMap wiki page ?
(it is now on the landing page of the wiki, this shows our culture, that team events are important for us, May be the layout of the calendar speaks other words :-) )



Christoph

**Comment by thomersch** [comment]
I am a bit saddened that the tone is pretty confrontational here. If you do not want “outside“ participation, I‘ll leave, that‘s fine, but I want to help out here and improve things. Telling me that for the history of things you always did something the one or other way is alright, but it makes me feel unwanted here.

I just wanted to let you know that I might be breaking the wiki mechanism in the future by switching to osmcal in the wiki. Telling me that you have to do this with _less_ data is dishonest, since you get much more data, which e.g. enables you to reverse geocode properly and stop showing german users “Munich“ instead of “München”.

The API is not designed to absolutely reduce redundancy above everything else. It is to offer a good integration experience for most people. At the moment you only show ISO-style dates, without any localization. Using the `human_short` field would instantly improve your formatting.

I think Jonathan hacked together his fully-fledged JavaScript library for OSMCAL in an afternoon. He‘s a wizard, but still, I think you should be do the same thing quickly (or just use his code).

**Comment by TheFive** [comment]
I just love your idea, to simplify calendar management for the users., and i tried to move the discussion back from one country field to the real problem, that is how we do the switch from the wiki calendar to the osmcal.
If we solve this topic with the editors (they are responsible for the content) you and me will find a solution for the API.

**Comment by thomersch** [comment]
> and i tried to move the discussion back from one country field to the real problem

It certainly did not help to complain about date fields. Please let stay real here.

The work to integrate osmcal into the wiki and replacing it is on its way and is now a matter of time. Upcoming events are a dynamic thing and as soon as I‘ll replace the widget in the wiki, I‘ll make sure all the events from it will be transferred to osmcal.

**Comment by thomersch** [comment]
By the way, here you are:

```javascript
fetch("https://osmcal.org/api/v2/events/")
	.then(resp => {
		if(resp.ok) {
			return resp.json();
		}
	})
	.then(data => {
		var geocodingPromises = [];

		for (var i = data.length - 1; i >= 0; i--) {
			var evt = data[i];
			if (evt.location) {
				geocodingPromises.push(geoCode(evt));
			}
		}

		Promise.all(geocodingPromises);
	});

function geoCode(evt) {
	var crds = evt.location.coords;
	return fetch("https://nominatim.openstreetmap.org/reverse?format=jsonv2&zoom=3&lat="+crds[1]+"&lon="+crds[0])
	.then(resp => {
		return resp.json();
	})
	.then(data => {
		evt.location.look_at_me_i_am_a_country_code = data.address.country_code;
		console.log(evt);
	});
}
```

**Comment by TheFive** [comment]
:-) Thanks.
may be i will extend my geonames API, to keep translating city names in local languages.

As a developer you know, the the pure source is may be 40 % of developing effort. Still have to do the nocking and mocha tests.

And sorry for the comparison with the Date field, this was not fair.

i will try to get this in, what are your time plans ?

**Comment by thomersch** [comment]
> may be i will extend my geonames API, to keep translating city names in local languages.

Good point! Not sure, if you‘re aware, but you can give Nominatim the `Accept-Language` header, which automatically give you the place name in the given language.

> As a developer you know, the the pure source is may be 40 % of developing effort

Sure, sure, I also do not expect you to name the variables as dumb as I did ;)

> i will try to get this in, what are your time plans ?

Honestly, I am pretty much good to go. The pull request for the wiki is pending and I‘m sure I‘ll find some volunteer to copy over events from one system to the other, if necessary.

**Comment by TheFive** [comment]
Ok, then i have to reschedule my plans.

**Comment by TheFive** [comment]
Alpha Version ready for testing in preprod.

**Comment by fredao** [comment]
Link, please

## Manfred Reiter - mobile -
## please excuse typos and brevity
## http://weeklyOSM.eu

TheFive <notifications@github.com> schrieb am Fr., 20. Nov. 2020, 13:03:

**Comment by TheFive** [comment]
See mattermost. Won't put it public,

**Comment by TheFive** [comment]
Otherwise i have to exclude Guests, to avoid confusion.

**Comment by fredao** [comment]
👍

## Manfred Reiter - mobile -
## please excuse typos and brevity
## http://weeklyOSM.eu

TheFive <notifications@github.com> schrieb am Fr., 20. Nov. 2020, 13:07:

**Comment by TheFive** [comment]
Some topic i have seen in the Migration:

a) OSMCAL does not have a "BIG" Flag.  This was used in the old calendar generator to show so marked BIG Events with a longer period than the normal "Stammtisch umme Ecke". 
b) Providing a venue and a location there are now conferences that have an ONLINE Venue but a location. (in wiki it was ONLINE or Located). I assume a simple change can help. Using a table with location (town) and a separat checkmark column for online venues.

**Comment by thomersch** [comment]
fyi the events in the wiki calendar have run dry, so the replacement has taken place: https://github.com/thomersch/OSMCALWikiWidget/issues/3

**Comment by TheFive** [comment]
Thanks for information, i try to get beta productive.
But just before going live i have seen that
'https://nominatim.openstreetmap.org/reverse?format=jsonv2&zoom=10&lat=52.517037&lon=13.38886&accept-language=FR'

Zoom Level 10 does mostly give a good answer. But in this sample, it returns the postal code as name.
Decreasing the zoom level to 7 will return berlin (what i had expected) but that is the federal state for all geocoding.

Any simple idea to fix this ?

**Comment by TheFive** [comment]
I try, hopefully this fix is working generic.
```  if (loc.addresstype === "postcode" && loc.address && loc.address.state) event.town = loc.address.state;```

**Comment by TheFive** [comment]
Running. Please open an issue in case of errors.
