### ISSUE TITLE
Cannot edit own comment

### ISSUE THREAD

**Issue by tordans** [TheFive/osmbc#856]
I tried editing my own comment at https://osmbc.openstreetmap.de/article/23933
I see an edit icon, can edit the text. But once I click save nothing happens and after a reload the edit is not visible.

The console shows an error message when clicking save and the error message from the terminal is
> OSM User >tordans< has not enough access rights

> POST https://osmbc.openstreetmap.de/article/23933/EditComment/0?reload=false 403

It was my own comment.

Suggested change:

- either users can edit their own comment
_or_
- the edit-icon shows an alert-message "edit not possible"

**Comment by TheFive** [comment]
I will investigate that, you are right, this does not make any sense.
