### ISSUE TITLE
open a second view in a second tab 

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#86]
![image](https://cloud.githubusercontent.com/assets/1868849/10599613/ec5f2bea-7703-11e5-8294-f064e364417b.png)

**Comment by fredao** [comment]
right click on Full EN and open it in a different tab 

priority LOW ;-)

**Comment by TheFive** [comment]
Will use a double click to solve. Does not need a popup. Otherwise i have to go back to HTML Links in the buttons, wich disturb my very small aesthetic feeling.
