### ISSUE TITLE
Linkcheck for twitter returns bad request (400)

### ISSUE THREAD

**Issue by call-me-matt** [TheFive/osmbc#868]
Linkchecks for twitter do not work, but always display a bad request (400) error.
This is, because twitter replies only to known agents.
![image](https://user-images.githubusercontent.com/34400929/108808713-7e118e00-75a7-11eb-9111-a5a2fa4d9b38.png)

Possible solutions are: set a user agent or ignore twitter when checking links

See routes/article.js line 982 and compare:
```
curl -X GET https://twitter.com/weeklyOSM -A "Googlebot/2.1"
```
with
```
curl -X GET https://twitter.com/weeklyOSM -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.20 (KHTML, like Gecko) Chrome/19.0.1036.7 Safari/535.20"
```

**Comment by TheFive** [comment]
mm i assume you are talkint about article number 24376 in WN552 (the word twittert is used there).

currently there is no problem with the link check

<img width="85" alt="image" src="https://user-images.githubusercontent.com/6240370/109217709-7247e680-77b6-11eb-8acb-54cf58ea7d5d.png">

**Comment by call-me-matt** [comment]
I have this frequently with all twitter links. Strange it doesnt happen to you.
What is the result of the curls above? Here, one is empty while the other returns the page.

**Comment by TheFive** [comment]
Fascinating may be it is a time dependency, you are working in osmbc in publish time and not on Thursday.

I will check your PR

**Comment by TheFive** [comment]
Seems go be fixed by changing configuration on server
