### ISSUE TITLE
Use informal translations

### ISSUE THREAD

**Issue by call-me-matt** [TheFive/osmbc#876]
Using the translate button, text from English is translated to German using formal language. As we are addressing our readers in informal language, this should be adapted.
Solution: When using the deepl API for translations, set the formality-flag (https://www.deepl.com/docs-api/translating-text/request/) to "less".

**Comment by TheFive** [comment]
this was part of the test, i think the result was that we do not use less.

i will try to offer this as config for the editors, especially as this festure seems not to be  restricted to german language

**Comment by call-me-matt** [comment]
by the way: I noticed that TheSwavu reviewed this week with "(...) Otherwise just the usual UK spelling", so when adapting the languages, maybe switch also between ENUS and ENGB?

**Comment by TheFive** [comment]
The languages now can be configured (for now only in config.production.json on the server). Please inform me, if there is a need to change. Currenty the beta is used to support the DE-less -DE-more... for all languages allowing more or less translations to check the quality of the different translations

**Comment by TheFive** [comment]
Implemented. Currently defined per language in config file. (only admin access)
