### ISSUE TITLE
English only - should be visible in the preview

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#88]
![preview](https://cloud.githubusercontent.com/assets/1868849/10605769/5664f554-772e-11e5-853e-94a8fe302e75.png)

Even if it appeares in the html ;-)
I delete it with pleasure in html, but I check the preview boxes very often. (I suppose not only me ;-)

Priority: middle ;-)

**Comment by TheFive** [comment]
I have change the behavior of the preview.

If there is nothing to show (preview is empty) it takes the text of the Markdown, so it is clear, that a text needs no translation.

**Comment by fredao** [comment]
OK - I got it ... sorry for asking :)

**Comment by TheFive** [comment]
Will change the feature with the next version.
