### ISSUE TITLE
Email to long absent editors

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#880]
do you see a possibility to send an email like follows after an absence of 3 month?

`Hello, 

Greetings from the weeklyOSM team. 

You have not been active for at least 3 months now. That is a pity, because we have always appreciated your contributions. 
You also know that we are only a small community of volunteers and need every helping hand. We would hate to lose you. 
Please sign up again and help us maintain weeklyOSM. 

Best regards

weeklyteam`

**Comment by TheFive** [comment]
Requirement is skipped.
