### ISSUE TITLE
additional button in "Edit Blog Details"

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#883]
An additional button for "Review Start" like the buttons "Close WNXXX(Language)" in "Edit Blog Details" would be helpful.

![grafik](https://user-images.githubusercontent.com/1868849/140878767-4f59bb67-c817-43a1-8f29-d3b355860ef5.png)

**Comment by fredao** [comment]
The same for "Set WNXXX(langugage) ready for review"

**Comment by TheFive** [comment]
preview available in BETA version
