### ISSUE TITLE
request is deprecated

### ISSUE THREAD

**Issue by Strubbl** [TheFive/osmbc#885]
see also https://github.com/request/request/issues/3142
we should find an alternative. maybe one, which can handle utf-8 in urls easily, e.g. urls like https://www.openstreetmap.org/user/%E6%B8%A4%E6%B5%B7%E8%A5%BF%E5%B2%B8/diary/398000.

**Comment by TheFive** [comment]
i have started to migrate top axios already (for some cases)

**Comment by TheFive** [comment]
see #833
