### ISSUE TITLE
Translation url not operational when url contains blank space (%20)

### ISSUE THREAD

**Issue by pierzen** [TheFive/osmbc#886]
In osmbc, I translate to french adding translation url from the links toolbar. I found that translation url with blank space where inoperational. Going to translate.google.com, I found a different  (new?) formulation of the translation url that does work.  

More details below.

While Translating https://osmbc.openstreetmap.de/article/25962, I found that there were four url pointing to OSM diaries but only one of the four link provided by the osmbc tool bar was operational. 

I then investigated a bit, and realised that the three links not working have a blank space represented by %20
https://www.openstreetmap.org/user/Erick%20tamba/diary/398116
https://www.openstreetmap.org/user/Maria%20Nabuwembo/diary/398125
https://www.openstreetmap.org/user/Vickystickz/diary/398126
https://www.openstreetmap.org/user/Sheila%20Job/diary/398147

See example below for Erick tamba
1. osmbc google **translate to FR link**
https://translate.google.com/translate?sl=auto&tl=FR&u=https://www.openstreetmap.org/user/Erick%20tamba/diary/398116

2. **Url link alternative** 
I found, going directly to https://translate.google.com is a different formulation of the url
If I enter the uri in the left box, ask for Fr translation and click on the link provided by google in the right box. The link is 
https://www-openstreetmap-org.translate.goog/user/Erick%20tamba/diary/398116?_x_tr_sl=auto&_x_tr_tl=fr&_x_tr_hl=fr

**Comment by TheFive** [comment]
Thanks for doing the research.

As the URL and the representation is used on several places in the code i will have to build a small module around it, to become more flexible in future.

Hint formyself: 

- in an url is replaced by -- (i am pretty sure that -- will be replaced by --- but i do not know an url with --)
