### ISSUE TITLE
BETA - bug - unselect languages

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#888]
![grafik](https://user-images.githubusercontent.com/1868849/147853800-af6aabe0-bf80-4a68-98b8-48f34ae9bce2.png)

unselect languages doesn't work

**Comment by TheFive** [comment]
Workaround until fixed:

Choose a language that is left of the language you want to skip
In your sample set the ES Language to EN to disable ES.

Fix will be delivered in short term.

Christoph
