### ISSUE TITLE
No distinction between active and non active languages in EditBlog

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#889]
This is the recent EDIT BLOG DETAILS
![grafik](https://user-images.githubusercontent.com/1868849/147876104-e3c92f28-cde4-41f3-b338-31c4739cd32c.png)
so far so good. 
Perfect for all languages - for those we publish (KO and ZH) and for those we don't (SW and BR)
One can directly close all languages. 

In **BETA** it looks like
![grafik](https://user-images.githubusercontent.com/1868849/147876190-1eae274a-e2c6-4cc8-8c42-d0343e432a33.png)

Languages we publish are looking OK, because one can close these languages
Languages we don't publish one must
1.  "Set ready for review" and then
2.  Close this language. 
Normally no problem: two clicks instead of one. 

I tried it with RU and CZ and was very astonished that these languages we don't publish at all
now appear in the LIVE version of OSMBC.
![grafik](https://user-images.githubusercontent.com/1868849/147876504-7642fc21-e105-4966-8cec-5f551f018c9f.png)

Although none of the languages contains an article, the languages are visible. I tried to make a language disappear by opening RU again.

However, this did not have the desired effect.

**Comment by TheFive** [comment]
Everything is working as designed :-(.

If you set a language ready for review for convenience the calendar is generated.
the generated calendar marks the language as active (there is exact one markdown)

So unused languages will get no action buttons in the edit view, or i can disable them. (to get a language active you still can set your own language to that one temporary and all language active mechasm is off for that languabe.
