### ISSUE TITLE
A solved comment is still visible as a comment in Overview

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#89]
btw: in full as well ...

but ...
priority very low :)

**Comment by TheFive** [comment]
Do you have a sample ?
I have checked 5 articles with a comment, there where all open. And i have changed one to solved (and corrected this change :-)) in production, and the solved article was not marked as commented.

**Comment by fredao** [comment]
http://thefive.sabic.uberspace.de/article/9990

**Comment by TheFive** [comment]
(Comment Is Open)

If the comment is solved, please edit the article and set the Comment Status to solved just below the comment field.

**Comment by TheFive** [comment]
![image](https://cloud.githubusercontent.com/assets/6240370/10614539/2c26c556-775b-11e5-82f0-92bf00196a25.png)
