### ISSUE TITLE
Open a language which is not "pre"selected

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#895]
Up to now, regardless of the languages set, you can open the editor window by simply clicking on a language. This is very helpful if, for example, you want to copy the picture into the different languages. 

This function is no longer included in the BETA. 

![grafik](https://user-images.githubusercontent.com/1868849/148456040-3e2da804-47c2-45bc-a51d-4b11d66209fa.png)

**Comment by TheFive** [comment]
This feature is currently skipped, as the fix design (two languages) is gone.

I will think of a "handy" alternative or something similar.

Main usage is the picture i assume. 

Would it help to have a shortcut to show "all" languages ? (that was my first idea)

**Comment by fredao** [comment]
> 

to be fair ...
all your solutions were much better than my first idea ;-)
