### ISSUE TITLE
Horizontal distance (padding) of the languages on homepage

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#902]
Produktiv
![grafik](https://user-images.githubusercontent.com/1868849/149293575-c98151b0-b85f-4956-8de4-84d75d9bbc2a.png)

BETA
![grafik](https://user-images.githubusercontent.com/1868849/149293810-e00392a5-e870-423f-91a6-9c6d90f2aae4.png)

I know this is nitpicking.
In "Produktiv", the distance between the individual languages is narrower. This also makes it possible to read the "Last Changes" in one line.

**Comment by fredao** [comment]
Alles nur Gewohnheitssache ... kann weg  ;-)

**Comment by TheFive** [comment]
tried several margin and padding classes for bootstrap, does not really work.

it looks like that growing the window will give the left (language) table more and more room instead of increasing the room for the history table on the right

**Comment by TheFive** [comment]
I will give a col sizing for the right column, to avoid linebreaks here a try.
This will may be force a break of the columns a little bit earlier.

**Comment by fredao** [comment]
I'm really happy with the way it works. THANK YOU.
