### ISSUE TITLE
Status display looks like a button, this is missleading

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#905]
The black Edit button in

https://osmbc.openstreetmap.de/BETA/blog/edit/WN599

 is useless

![image](https://user-images.githubusercontent.com/1868849/149501285-b07a0bce-5512-443d-8ef8-b560c16d9105.png)

**Comment by TheFive** [comment]
Layout is missleading. Will change the layout, so that the "EDIT" can be recognized as status of the blog.
