### ISSUE TITLE
Edit Button for Comments

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#907]
in Beta the Edit button for comments is missing

![grafik](https://user-images.githubusercontent.com/1868849/149757339-c6009c4a-d7e1-4085-9701-17d35b6bc67e.png)

the former version allowed to edit a comment

![grafik](https://user-images.githubusercontent.com/1868849/149757651-9aa25702-dbcd-4e0b-9188-f84f661a020c.png)

**Comment by TheFive** [comment]
oh you found a forgetten glyphicon :-). That was removed in bootstrap 4. i have to change to font awesome.

looks to be that this happened for the translation review (in the case of blog translation) and defining an order of articles, changed that although.
