### ISSUE TITLE
caught Problem with Deepl Translation

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#910]
Is there a way to catch this error message and not enter it in the text field? 

![grafik](https://user-images.githubusercontent.com/1868849/150600582-c8b3ba79-c120-4e67-ac3a-a0bd00f881fc.png)

**Comment by TheFive** [comment]
does this appear when translating a singe article or s complete blog.

Do you have a suggestion how to handle deepl translation problems with blog translations. should the article simply keep to be emty with no information to the user.

may be this can be written in the comment ?

**Comment by fredao** [comment]
I translated the whole blog  ... My fault ... I know :-(
