### ISSUE TITLE
Delete space between Title and collection

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#913]
BETA

![grafik](https://user-images.githubusercontent.com/1868849/150691283-1f6f20f4-01dc-4201-b039-92010a6a20f3.png)

Production
![grafik](https://user-images.githubusercontent.com/1868849/150691357-b3351792-4a80-4d6d-998f-9ac71f73b7a6.png)

**Comment by TheFive** [comment]
#911 
looks like casting out the devil with the beast. Bugfix for 911 introduced this error.
