### ISSUE TITLE
Missing menu line at the top in BETA on tablet

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#915]
BETA on tablet
![grafik](https://user-images.githubusercontent.com/1868849/151596938-028b45f3-9027-4bb8-bf7c-fad76231cb04.png)

production on tablet 
![grafik](https://user-images.githubusercontent.com/1868849/151597043-ac5fa1b9-e15a-4e2b-a893-3f6a080ed325.png)

**Comment by TheFive** [comment]
Did you experience any other missing (or oversized) UI Elements on tablet.

Bootstrap allows to decide for every element to hide or show it depending on device size

**Comment by TheFive** [comment]
Can you specify your Screen Size (pixel).

This is the 800x600 online test:

<img width="961" alt="image" src="https://user-images.githubusercontent.com/6240370/151660293-f265a887-a2fb-4a5e-a2bd-dd1461f90b62.png">


You can find the menu bar

<img width="820" alt="image" src="https://user-images.githubusercontent.com/6240370/151660442-0cb47315-6044-44a9-b4f1-f5a92ae983ce.png">


the next test step in Safari looks this way

<img width="1410" alt="image" src="https://user-images.githubusercontent.com/6240370/151660455-542c4eac-58a5-415e-a148-79d5ed9afc06.png">

**Comment by fredao** [comment]
Thx, in landscape it's fine
