### ISSUE TITLE
Set Ready for Review works only if triggert twice

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#926]
![image](https://user-images.githubusercontent.com/6240370/169640956-d64f4cf0-1779-4bb2-9d35-b48fef1fbfb7.png)

**Comment by TheFive** [comment]
Is it possible, that the creation of the event article is consuming the time ?
@fredao

**Comment by fredao** [comment]
will check it asap

**Comment by TheFive** [comment]
Question: i do that in "sync", so that if an error occurs, someone can be informed. But if you do not wait for the result (what is a typical behavior in web usage is), the information is lost. So i can start generating the Event Article without waiting for the result. If there is a problem it will pop up in the Review process.

**Comment by TheFive** [comment]
Will fix the problem with issue #929
