### ISSUE TITLE
Error searching for a special HTTP String

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#93]
Searching in production for 
http://www.gisdoctor.com/site/2015/10/12/reasons-openstreetmap/

does not find all results.
Especially the article
http://thefive.sabic.uberspace.de/article/9997 
creates problems. It is only found, if there is a space behind the Link.
This space is not needed in the other articles. CRAZY.

**Comment by fredao** [comment]
and it has nothing todo with the slash at the end?

**Comment by TheFive** [comment]
I dont think so, as the others articles are found with a slash.
Unproved hypothesis now is that the markdown is beginning with a [, wich looks unusual, is the reason.

**Comment by TheFive** [comment]
It looks like, if i add a space before the [GIS Doctor] it works. I have to look, wether i can do that space by default between collection and markdown in the index.

**Comment by fredao** [comment]
Only to know:
I added a blank in the English Markdown as well and searched again.
It looks like you are searching in German only. (That is not a problem ... only to know. ;-))
