### ISSUE TITLE
Cannot set article as first of a section when in review

### ISSUE THREAD

**Issue by Strubbl** [TheFive/osmbc#934]
ATM, we are reviewing the next WN. The article https://osmbc.openstreetmap.de/article/27040 shall be listed as first of the "did you know" category, but all options except "None" are grayed out in the Predecessor option.

**Comment by Strubbl** [comment]
Uh, i cannot even change the category anymore

**Comment by fredao** [comment]
When a language is closed, these changes are no longer possible. This is a lock by design. 

I had jumped to the conclusion that we could not expect any proofreading this week. 

 Please excuse me for not having thought of this.

**Comment by Strubbl** [comment]
Thanks for the explanation. i did not know this.

**Comment by TheFive** [comment]
Please let me close any issue. Put a comment, that it is solved. but closing issues with the wrong label stage will put them in the Changelog.
