### ISSUE TITLE
Markdown plugin for language flags

### ISSUE THREAD

**Issue by TheFive** [TheFive/osmbc#938]
A markdown plugin for language flags is required.

This should generate relative path to WeeklyOSM (as configured) fir Export and expand these path with the weekly domain for Preview.

Allthough a internal HTML presentation is required for Deepl Translation to create an easy Turndown (invert markdown prozess) plugin.

**Comment by TheFive** [comment]
I plan to use an rmoji parser for that.

Will result in a language flag syntax (:DE:) i di not expect that to collidate with An non existin emoji need.

**Comment by Strubbl** [comment]
If the emoji search algorithm is not greedy, there is a smiley which is `:D` or one that is `:P` and some more.

**Comment by TheFive** [comment]
see
https://github.com/TheFive/osmbc/issues/941
