### ISSUE TITLE
Allow to download multiple in blog details

### ISSUE THREAD

**Issue by call-me-matt** [TheFive/osmbc#940]
When exporting blog posts to wordpress, every language has to be downloaded and imported separately. It would be a big advantage if one could select and download multiple languages at once and format them in multi-language syntax for wordpress.
At best a heading would be formatted as well.
Blue print for the multi-language formatting:
`[:en]weeklyOSM 623[:es]semanarioOSM 623[:ja]週刊OSM 623[:cz]týdeník 623[:ru]Еженедельник OSM 623[:fr]hebdoOSM 623[:pl]Tygodnik OSM 623[:de]Wochennotiz 623[:pt]semanárioOSM 623[:zh]週刊OSM 623[:tr]HaftalıkOSM 623[:pb]OSM semanal 623[:it]Notiziario Settimanale OSM 623[:ko]주간 OSM 623[:sw]OSMkilawiki 623[:cn]OSM周刊 623[:]`

**Comment by TheFive** [comment]
All languages that are closed ?

that will be just an internal for loop.

Who is the Audience, just to avoid erreors.

The really NICE solution would be WP offers an API to push the complete test to.

that requires all post review changes to be done in OSMBC, otherwise there is the risc of deleting changes.

**Comment by call-me-matt** [comment]
Yes, it is as simple as that. All languages that are closed will work for 99% of our needs and be a big help. The aim rephrased: I as the publisher of the weeklyOSM do not want to download and import every post language by language, but with one copy for the headline and one copy for the post for all languages at once.
The API might be a next step, but that's also an additional risk (error prone for editors and also for abuse of the API).

**Comment by TheFive** [comment]
You are aware, that there are languages in weeklyOSM that are not in OSMBC ?
so the full export needs a manual merge. Contain although risks
i would expect WP to mitigate e.g. API abuse by filtering on static IP, (may be be nginx, if WP is not put direct to the front).
The editor risk could be mitigated by a 4 eyes principle in the process (but i do not think it is necessary).

But the API has much more problems, e.g. it has to generate the blog, find its name....

**Comment by call-me-matt** [comment]
I agree, let's start with the multiple download feature first. It would already cut efforts for each weekly post by a lot and comes with way less risk than an API integration that definitely needs good testing beforehand.

**Comment by TheFive** [comment]
my very long term vision is to replace WP by a static files server and a html generator for websites like hugo. :-)
(but there are still some open points in this vision)

**Comment by call-me-matt** [comment]
Looking forward to our next release!

**Comment by TheFive** [comment]
online

**Comment by call-me-matt** [comment]
Almost perfect. But the language tags need to be lower case in order to be recognized by wordpress. And the headers include an additional bracket.
