### ISSUE TITLE
Upcoming Events

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#953]
It would be nice if the Upcoming Events were generated again.

**Comment by TheFive** [comment]
Tried it in the DE Article editor, needs some time but it worked.

Where have you experienced the Problem ?

**Comment by fredao** [comment]
Sorry, maybe I was to quick again. :-(

**Comment by TheFive** [comment]
just do a hint, that i can close the issue, thats enough. i have to check, the labels for the issue, that my Changelog is not mixedup with unresolved closed issues.
