### ISSUE TITLE
OSMCal Icon is too large

### ISSUE THREAD

**Issue by Strubbl** [TheFive/osmbc#961]
at the moment, the generated calendar has the OSMCal Icon, which is way too large. Can we give it a fixed smaller size, e.g. width/height=16px, during generation of the calendar? https://weeklyosm.eu

![grafik](https://user-images.githubusercontent.com/97055/196245107-3e6a52b8-204b-4a89-9590-c7e01e16f141.png)

**Comment by Strubbl** [comment]
In the review page the calendar preview it looks okay. Icon size is limited to a height of 16 px and thus looks okay.

**Comment by TheFive** [comment]
Weekly OSM Output
```
<a href="https://osmcal.org/event/1340/">
<img src="https://osmcal.org/static/osmcal/favicon.png" height="16"/>
```

The Same restriction is used in osmbc.openstreetmap.de on review page, here it is working
```
 <a href="https://osmcal.org/event/1340/">
<img src="https://osmcal.org/static/osmcal/favicon.png" height="16"/>
</a>
```

in my "local test environment" this is generated
```
 <a href="https://osmcal.org/event/1224/">
<img src="https://osmcal.org/static/osmcal/favicon.png" alt="osmcalpic" width="16" height="16">
</a>
```

I will check for the differrence, but what is different in the WP environment and he OSMBC Production environment, that the height is ignored in WP ?

**Comment by TheFive** [comment]
changing
```
osmcalpic: <img src="https://osmcal.org/static/osmcal/favicon.png" height=16 witdh=16/>
```
to 
```
osmcalpic: <img src="https://osmcal.org/static/osmcal/favicon.png" height=16 width=16/>
```

hopefully will fix this issue ?

**Comment by Strubbl** [comment]
I see no difference between your two lines

**Comment by Strubbl** [comment]
I just fiddled around with the Firefox web inspector directly on the weeklyosm.eu page. And i found out, that adding the width fixes the issue. Only providing the height didn't seem to scale the icon down to 16x16

**Comment by Strubbl** [comment]
I see with the current WN this issue is fixed
