### ISSUE TITLE
Open external links in a new tab

### ISSUE THREAD

**Issue by call-me-matt** [TheFive/osmbc#971]
When users click a link, this is opened in the same tab. As we do not want to lose our readers and to enhance usability - it would be great to add a _blank target to our links when exporting to html.

Alternatively, this [plugin](https://wordpress.org/plugins/open-external-links-in-a-new-window/) allows to globally add this feature - also for our previous posts.

I would prefer a solution without plugin, though.

**Comment by TheFive** [comment]
Have to look, wether it is configurable in markdown-it, or how to do a modification which is stable against any markdown it updates.

**Comment by TheFive** [comment]
https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md

search for _blank

**Comment by call-me-matt** [comment]
Also got feedback that this feature would be good in OSMBC as convenience function for editors who proof read articles.

**Comment by call-me-matt** [comment]
There is also this plugin: https://www.npmjs.com/package/markdown-it-link-attributes
