### ISSUE TITLE
Unicode issue with title extraction

### ISSUE THREAD

**Issue by Strubbl** [TheFive/osmbc#973]
e.g. add the following article https://lists.openstreetmap.org/pipermail/talk-de/2022-December/117890.html to OSMBC and see the broken title: `[Talk-de] Konferenzprogramm ver�ffentlicht | Weihnachtsgru� aus der Koordinierungsstelle`

**Comment by TheFive** [comment]
this is my really shortest fix i have ever done in OSMBC :-)
