### ISSUE TITLE
Better titles for collected toots

### ISSUE THREAD

**Issue by call-me-matt** [TheFive/osmbc#981]
If a toot is added as article, the pre-filled title is always the same and does not use the actual title  from the linked page.

AS-IS:
the title is always: En OSM Town | Mapstodon for OpenStreetMap

TO-BE
Take the actual title of the linked page, in the example:
eeklyOSM: &quot;👉 https://www.weeklyosm.eu/archives/16390 👈  Issu…&quot; - En OSM Town | Mapstodon for OpenStreetMap

How to reproduce:
got to https://en.osm.town, chose any post and add it to OSMBC, for example: https://en.osm.town/@weeklyOSM/110089639818050574

On the linked page, there is also a "domain title" in a script body, maybe a regex gets confused by that?
```
<script id="initial-state" type="application/json">{"meta":{"streaming_api_base_url":"wss://en.osm.town","access_token":"nRr-GUJEDRFPxWaktrHaCikM9Yw5qlZoGvWX6mUzWjA","locale":"en","domain":"en.osm.town","title":"En OSM Town | Mapstodon for OpenStreetMap","admin":"10939...
```

Examples:
https://osmbc.openstreetmap.de/article/28351
https://osmbc.openstreetmap.de/article/28204
https://osmbc.openstreetmap.de/article/28014

**Comment by call-me-matt** [comment]
maybe a bug in cheerio lib, as the function seems to be [correctly used](https://github.com/TheFive/osmbc/blob/966c04ce9a8ec8d754b1db4850698d8f9670b264/model/htmltitle.js#L49)?

**Comment by call-me-matt** [comment]
I tried the code outside of OSMBC and it works just fine. So maybe the page is not fully loaded when the title is retrieved?

**Comment by TheFive** [comment]
looks that ssrf reacts on "@" 

<img width="813" alt="image" src="https://user-images.githubusercontent.com/6240370/228142724-da59fbca-5204-4a9a-bb67-1c8b1e049360.png">

https://www.npmjs.com/package/ssrf

i would suggest that we build a dedicated mastondon converter, wich ignores url check (and replaces is by a check against mastonon standard format, which can be handled by a regex). this may be needs, that the original url is forewarded to the converter (may be by forewarding two urls or using ssrf in the converter).

The more interesting question is, what is a good title for a titleless toot ?

**Comment by TheFive** [comment]
Simple suggestion
Toot By @XXX from dd.mm.yyyy 

(titles are only suggested and can be changed by editor, if it is helpful for the process)

**Comment by Strubbl** [comment]
> Simple suggestion
> Toot By @xxx from dd.mm.yyyy

This. Or one can take the first 100 chars (if they are no URL) and add …

**Comment by TheFive** [comment]
currently i have just fixed the ssrf rejection of mastodon urls, so the standard mastodon title is now taken.

i would like to have a similar tweet (ä) toot  -> collection process as in twitter. but as toots can be very long, the toots have to be truncated.
