### ISSUE TITLE
Keep Lead picture width and height parameters during translation

### ISSUE THREAD

**Issue by Strubbl** [TheFive/osmbc#991]
When i translate a lead picture article, the markdown parameter for the width & height is lost. E.g. : https://osmbc.openstreetmap.de/article/28600

`![lead picture](https://weeklyosm.eu/wp-content/uploads/2023/06/671_T_all.png =1169x737)`

gets translated to

`![lead picture](https://weeklyosm.eu/wp-content/uploads/2023/06/671_T_all.png)`

Please keep the ` =1169x737` also after translating.

**Comment by TheFive** [comment]
Introduced a turn down service for the markdown-it-imsize plugin.
